import { ArrowLeft, Check, Database, GitMerge, Layers, RefreshCw, Sparkles, Tags as TagsIcon } from 'lucide-react';
import { useState } from 'react';
import { Link } from 'react-router-dom';
import * as il from '@/api/inspectionLabels';
import type { LabelComponent } from '@/api/inspectionLabels';
import { useAuth } from '@/auth/AuthContext';
import { Button, PageHeader } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Table, Td, Th } from '@/components/ui/Table';
import { fmtDate } from '@/lib/format';

const field = 'h-7 rounded-sm border border-line bg-canvas px-2 text-xs focus:border-ink focus:outline-none';

// Setup → Inspection: variant sets (per ref × component, OUR exemplars only, replace keeps history), new-variant candidates, editable shot lists, findings-tag vocabulary (confirm / merge), read-only WatchM8 export
export default function InspectionSetupPage() {
  il.ensureSeed(); const { user } = useAuth(); const manager = user?.accessTier === 'manager'; const [tick, setTick] = useState(0); const bump = () => setTick((t) => t + 1);
  const [ref, setRef] = useState(il.allVariantSets()[0]?.ref ?? ''); const [comp, setComp] = useState<LabelComponent>('dial'); const set = il.variantSetFor(ref, comp);
  const [promote, setPromote] = useState<Record<string, { key: string; tells: string }>>({}); const [merge, setMerge] = useState<Record<string, string>>({}); const [lists, setLists] = useState<Partial<Record<LabelComponent, string>>>({});
  const refs = Array.from(new Set(il.allVariantSets().map((v) => v.ref))); const quality = il.labelQuality(); const wm8 = il.watchm8Export();
  return <div data-testid="inspection-setup-page" data-tick={tick} className="space-y-4">
    <Link to="/setup" className="inline-flex h-8 items-center gap-1 text-xs text-ink-500 hover:text-ink"><ArrowLeft size={12} /> Setup</Link>
    <PageHeader title="Setup · Inspection" subtitle="Variant sets · guided shot lists · findings tags · WatchM8 export (read-only). Exemplars are our own photos — job id, chosen by, date, version; replacing keeps history." />
    <div className="grid grid-cols-2 gap-4">
      <Card title="Variant sets" subtitle="Per ref × component · MK1 · MK2 · … each 1–3 exemplars on the same shot + one-line tells" testId="variant-sets-card" action={<span className="flex items-center gap-1"><select data-testid="vs-ref" value={ref} onChange={(e) => setRef(e.target.value)} className={field}>{refs.map((r) => <option key={r} value={r}>{r}</option>)}</select><select data-testid="vs-component" value={comp} onChange={(e) => setComp(e.target.value as LabelComponent)} className={field}>{il.COMPONENTS.map((c) => <option key={c.key} value={c.key}>{c.label}</option>)}</select></span>}>
        {set ? <ul data-testid="vs-variants" className="space-y-2">{set.variants.map((v) => <li key={v.key} data-testid={`vs-variant-${v.key}`} className="rounded-md border border-line p-2">
          <div className="flex items-center gap-2 text-xs"><span className="rounded-sm bg-ink px-1.5 font-mono font-bold text-white">{v.key}</span><span className="text-ink-700">{v.tells}</span><span className="ml-auto text-[10px] text-ink-400">{v.exemplars.length} exemplar{v.exemplars.length === 1 ? '' : 's'}{v.history.length ? ` · ${v.history.length} replaced` : ''}</span></div>
          <div className="mt-1.5 flex flex-wrap gap-1.5">{v.exemplars.map((e) => <figure key={e.id} data-testid={`vs-exemplar-${e.id}`} className="w-[110px]"><img src={e.url} alt="" className="h-16 w-full rounded-sm object-cover ring-1 ring-line" /><figcaption className="text-[9px] text-ink-500">{e.jobId} · {e.chosenBy} · {fmtDate(e.at)} · v{e.version}{manager && <button type="button" data-testid={`vs-replace-${e.id}`} onClick={() => { il.replaceExemplar(set.id, v.key, e.id, `https://picsum.photos/seed/${e.id}-v${e.version + 1}/320/240`, e.jobId); bump(); }} className="ml-1 inline-flex items-center gap-0.5 text-brand underline"><RefreshCw size={8} /> replace</button>}</figcaption></figure>)}</div>
        </li>)}</ul> : <p data-testid="vs-none" className="text-xs text-ink-400">No variant set for {ref} · {il.componentLabel(comp)} — rows fall back to typeahead text; “None of these” opens a candidate.</p>}
        <div className="mt-3 border-t border-line pt-2">
          <div className="mb-1 inline-flex items-center gap-1 text-[11px] font-semibold uppercase tracking-wide text-ink-500"><Sparkles size={11} /> New-variant candidates <span data-testid="vs-candidates-count" className="rounded-full bg-canvas px-1.5 text-[10px] ring-1 ring-line">{il.pendingCandidates().length}</span></div>
          <ul data-testid="vs-candidates" className="space-y-1.5 text-xs">{il.allCandidates().map((c) => <li key={c.id} data-testid={`vs-candidate-${c.id}`} data-status={c.status} className="flex flex-wrap items-center gap-2 rounded-md bg-canvas px-2 py-1.5">{c.photoUrl && <img src={c.photoUrl} alt="" className="h-9 w-12 rounded-sm object-cover" />}<span className="font-mono">{c.ref} · {il.componentLabel(c.component)}</span><span className="text-ink-500">{c.jobId} · {c.by} · {fmtDate(c.at)}</span><span className="rounded-sm bg-surface px-1.5 text-[10px] uppercase ring-1 ring-line">{c.status}{c.promotedAs ? ` → ${c.promotedAs}` : ''}</span>
            {c.status === 'pending' && manager && <span className="ml-auto flex items-center gap-1"><input data-testid={`vs-promote-key-${c.id}`} placeholder="MK4" value={promote[c.id]?.key ?? ''} onChange={(e) => setPromote({ ...promote, [c.id]: { key: e.target.value, tells: promote[c.id]?.tells ?? '' } })} className={`${field} w-16 font-mono`} /><input data-testid={`vs-promote-tells-${c.id}`} placeholder="one-line tells" value={promote[c.id]?.tells ?? ''} onChange={(e) => setPromote({ ...promote, [c.id]: { key: promote[c.id]?.key ?? '', tells: e.target.value } })} className={`${field} w-44`} /><Button size="sm" variant="primary" data-testid={`vs-promote-${c.id}`} disabled={!promote[c.id]?.key?.trim()} onClick={() => { il.promoteCandidate(c.id, promote[c.id].key.trim(), promote[c.id].tells.trim()); bump(); }}>Promote</Button><Button size="sm" data-testid={`vs-reject-${c.id}`} onClick={() => { il.rejectCandidate(c.id); bump(); }}>Reject</Button></span>}</li>)}{!il.allCandidates().length && <li className="text-ink-400">None yet — “None of these — new variant?” on a row opens one.</li>}</ul>
        </div>
      </Card>
      <div className="space-y-4">
        <Card title="Inspection shots" subtitle="Fixed shot list per component · one per line · saved lists drive the guided capture everywhere" testId="shot-lists-card">
          <div className="grid grid-cols-2 gap-2">{il.COMPONENTS.map((c) => <label key={c.key} className="text-[11px] text-ink-500"><span className="font-semibold text-ink">{c.label}</span> <span data-testid={`shots-count-${c.key}`}>· {il.shotLists[c.key].length} shots</span>
            <textarea data-testid={`shots-edit-${c.key}`} rows={Math.max(2, il.shotLists[c.key].length)} value={lists[c.key] ?? il.shotLists[c.key].map((s) => s.label).join('\n')} onChange={(e) => setLists({ ...lists, [c.key]: e.target.value })} className="mt-0.5 w-full rounded-sm border border-line bg-canvas px-2 py-1 font-mono text-[11px] text-ink focus:border-ink focus:outline-none" />
            {lists[c.key] !== undefined && <Button size="sm" data-testid={`shots-save-${c.key}`} onClick={() => { il.setShotList(c.key, lists[c.key]!.split('\n')); setLists({ ...lists, [c.key]: undefined }); bump(); }}><Check size={11} /> Save list</Button>}</label>)}</div>
        </Card>
        <Card title="Inspection tags" subtitle="Per-component vocabulary · new tags stay flagged until a manager confirms or merges" testId="tags-card">
          <div className="space-y-2">{il.COMPONENTS.filter((c) => il.tagsFor(c.key).length).map((c) => <div key={c.key} className="text-xs"><span className="mr-2 font-semibold text-ink">{c.label}</span>
            <span className="inline-flex flex-wrap gap-1 align-middle">{il.tagsFor(c.key).map((t) => <span key={t.tag} data-testid={`tag-${c.key}-${t.tag}`} data-status={t.status} className={`inline-flex items-center gap-1 rounded-full border px-2 py-0.5 font-mono text-[11px] ${t.status === 'new' ? 'border-amber-300 bg-amber-50 text-amber-900' : 'border-line text-ink-700'}`}>#{t.tag} <span className="text-[9px] text-ink-400">{t.uses}</span>
              {t.status === 'new' && manager && <><button type="button" data-testid={`tag-confirm-${c.key}-${t.tag}`} onClick={() => { il.confirmTag(c.key, t.tag); bump(); }} title="Confirm" className="text-emerald-700"><Check size={10} /></button><select data-testid={`tag-merge-${c.key}-${t.tag}`} value={merge[`${c.key}:${t.tag}`] ?? ''} onChange={(e) => setMerge({ ...merge, [`${c.key}:${t.tag}`]: e.target.value })} className="h-5 rounded-sm border border-line bg-surface text-[10px]"><option value="">merge into…</option>{il.tagsFor(c.key).filter((x) => x.tag !== t.tag && x.status === 'confirmed').map((x) => <option key={x.tag} value={x.tag}>#{x.tag}</option>)}</select>{merge[`${c.key}:${t.tag}`] && <button type="button" data-testid={`tag-merge-go-${c.key}-${t.tag}`} onClick={() => { il.mergeTag(c.key, t.tag, merge[`${c.key}:${t.tag}`]); bump(); }} className="text-brand"><GitMerge size={10} /></button>}</>}</span>)}</span></div>)}</div>
        </Card>
      </div>
    </div>
    <Card title="Data out · WatchM8 export" subtitle={<span className="inline-flex items-center gap-2"><Database size={12} /> Read-only from RS · every opinion label + photo ids · also mirrored to m3ke as <code>inspection_opinion</code> · label quality: {quality.submitted} blind 2nd opinions · {quality.agree} agree · {quality.disagree} disagree{quality.rate !== null ? ` · ${quality.rate}% agreement` : ''}</span>} bodyClassName="p-0" testId="wm8-card">
      <Table><thead><tr><Th>When</Th><Th>Job</Th><Th>Ref · era</Th><Th>Component</Th><Th>Opinion</Th><Th>Variant</Th><Th>Tags</Th><Th className="text-right">Photos (controlled)</Th><Th>By</Th><Th>Flags</Th></tr></thead>
        <tbody>{wm8.map((r) => <tr key={r.id} data-testid={`wm8-${r.id}`}><Td className="text-xs text-ink-500">{fmtDate(r.at)}</Td><Td className="font-mono text-xs">{r.jobNumber}</Td><Td className="font-mono text-xs">{r.ref} · {r.serialEra}</Td><Td className="text-xs">{il.componentLabel(r.component)}</Td><Td className="text-xs">{il.opinionLabel(r.opinion)} · {r.confidence}</Td><Td className="font-mono text-xs">{r.variant ?? '—'}</Td><Td className="font-mono text-[11px]">{r.tags.map((t) => `#${t}`).join(' ') || '—'}</Td><Td className="text-right text-xs tabular">{r.photoIds.length} ({r.controlledPhotos})</Td><Td className="text-xs">{r.by} · r{r.revision}</Td><Td className="text-[10px] uppercase text-ink-500">{[r.secondOpinion && '2nd', r.specimen && 'specimen'].filter(Boolean).join(' · ')}</Td></tr>)}</tbody></Table>
    </Card>
    <p className="inline-flex items-center gap-1 text-[11px] text-ink-400"><Layers size={11} /> Seam flagged in docs/KEEPER-HANDOFF/11-INTEGRATIONS.md as <b>WatchM8</b> · <TagsIcon size={11} /> tags render inline as chips inside notes on every row.</p>
  </div>;
}
