import { AlertTriangle, Camera, Check, Download, FileSignature, Lock } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import * as ap from '@/api/appraisals';
import type { Appraisal, AppraisalFields, AppraisalPurpose } from '@/api/appraisals';
import { Button, PageHeader } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { fmtDate } from '@/lib/format';

const inp = 'mt-0.5 h-8 w-full rounded-sm border border-line bg-canvas px-2 text-[13px] focus:border-ink focus:bg-surface focus:outline-none disabled:opacity-60';
const F: { k: keyof AppraisalFields; l: string }[] = [{ k: 'clientName', l: 'Client name' }, { k: 'maker', l: 'Maker' }, { k: 'model', l: 'Model' }, { k: 'reference', l: 'Reference #' }, { k: 'serial', l: 'Serial #' }, { k: 'movement', l: 'Movement' }, { k: 'caliber', l: 'Caliber' }, { k: 'jewels', l: 'Jewels' }, { k: 'beatRate', l: 'Beat rate' }, { k: 'caseSize', l: 'Case size' }, { k: 'caseMaterial', l: 'Case material' }, { k: 'crownCrystal', l: 'Crown / crystal' }, { k: 'dial', l: 'Dial' }, { k: 'bracelet', l: 'Bracelet / strap' }, { k: 'condition', l: 'Condition (from inspection)' }, { k: 'styleNo', l: 'Style No.' }];
const longDate = (iso: string) => new Date(`${iso}T12:00:00`).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

// The document — reproduces the reference layout; printed via the browser's PDF engine (Download PDF)
export const AppraisalDocument = ({ a }: { a: Appraisal }) => { const f = a.fields; return <article data-testid="appraisal-document" data-status={a.status} className="appraisal-doc mx-auto w-[816px] bg-white px-14 py-12 font-serif text-[13px] leading-relaxed text-black shadow-md print:shadow-none">
  <header className="text-center"><h1 className="text-[26px] font-bold tracking-wide" data-testid="apr-title">{ap.COMPANY.name} Appraisal Report</h1><p className="mt-1 text-[11px] text-gray-700">{ap.COMPANY.line}</p><hr className="mt-3 border-t-2 border-black" /></header>
  <div className="mt-5 flex items-end justify-between"><div data-testid="apr-date">{longDate(a.date)}</div><div className="text-right"><div className="text-[15px] font-semibold" data-testid="apr-purpose">Appraisal Report for {a.purpose}</div><div className="font-mono text-[11px] text-gray-600" data-testid="apr-number">{a.number}</div></div></div>
  <div data-testid="apr-client" className="mt-4 bg-gray-100 px-3 py-1.5 text-[14px] font-semibold">Client: {f.clientName}</div>
  <p className="mt-4" data-testid="apr-description"><span className="font-semibold">Item description:</span> One {f.maker} {f.model} wristwatch, reference {f.reference}, serial number {f.serial}. {f.caseSize} {f.caseMaterial} case with {f.crownCrystal.charAt(0).toLowerCase()}{f.crownCrystal.slice(1)}. {f.dial}. Fitted with a {f.bracelet}. {f.movement} movement, {f.caliber}, {f.jewels}, beating at {f.beatRate}.</p>
  <p className="mt-2 text-[12px] italic text-gray-800" data-testid="apr-authenticity">{a.authenticity}</p>
  <div className="mt-5 grid grid-cols-[1fr_300px] gap-6">
    <table className="w-full border-collapse text-[12.5px]"><tbody>{[['Maker', f.maker], ['Model', f.model], ['Movement', `${f.movement} · ${f.caliber}`], ['Dial / features', f.dial], ['Bracelet / strap', f.bracelet], ['Condition', f.condition], ['Style No.', f.styleNo]].map(([k, v]) => <tr key={k} className="border-b border-gray-300"><th className="w-[130px] py-1.5 pr-3 text-left align-top font-semibold">{k}</th><td className="py-1.5 align-top" data-testid={`apr-field-${k.toLowerCase().replace(/[^a-z]+/g, '-').replace(/^-|-$/g, '')}`}>{v}</td></tr>)}</tbody></table>
    <div className="grid grid-cols-2 gap-2 self-start">{[['Reference photo', a.beforePhotoUrl, 'apr-photo-before'], ['After service', a.afterPhotoUrl, 'apr-photo-after']].map(([cap, url, tid]) => <figure key={cap as string} data-testid={tid as string} data-present={!!url}>{url ? <img src={url as string} alt="" className="h-[110px] w-full rounded-sm border border-gray-300 object-cover" /> : <div className="grid h-[110px] place-items-center rounded-sm border border-dashed border-gray-400 text-[10px] text-gray-500">{cap === 'After service' ? 'after-work photo pending' : 'no photo'}</div>}<figcaption className="mt-0.5 text-center text-[10px] text-gray-600">{cap as string}</figcaption></figure>)}</div>
  </div>
  <div data-testid="apr-total" data-value-source={a.valueSource} className="mt-6 flex items-center justify-between border-2 border-black px-4 py-2.5"><span className="font-semibold">Total estimated retail replacement cost:</span><span className="flex items-center gap-2"><span className="print:hidden">{a.valueSource === 'placeholder' && <span data-testid="apr-value-badge" className="rounded-sm bg-amber-100 px-1.5 py-0.5 text-[10px] font-sans font-semibold uppercase text-amber-900">Placeholder · unconfirmed</span>}{a.valueSource === 'confirmed' && <span data-testid="apr-value-badge" className="rounded-sm bg-emerald-100 px-1.5 py-0.5 text-[10px] font-sans font-semibold uppercase text-emerald-900">Confirmed</span>}{a.valueSource === 'none' && <span data-testid="apr-value-badge" className="rounded-sm bg-rose-100 px-1.5 py-0.5 text-[10px] font-sans font-semibold uppercase text-rose-900">No comparable data — enter manually</span>}</span><span data-testid="apr-value" className="text-right text-[18px] font-bold">{a.value !== null ? ap.fmtValue(a.value) : '—'}</span></span></div>
  <div className="mt-8 flex items-end gap-10"><div className="w-[280px]" data-testid="apr-signature" data-signed={a.status === 'final'}><div className="h-[64px]">{a.signatureUrl ? <img src={a.signatureUrl} alt="signature" className="h-[64px]" /> : <div className="h-[64px] text-[10px] italic text-gray-400 print:text-transparent">unsigned draft — finalize to stamp signature</div>}</div><div className="border-t border-black pt-1 text-[12px]">{ap.SIGNER.name}{a.signedAt && <span className="text-gray-600"> · signed {fmtDate(a.signedAt)}</span>}</div></div></div>
  <p className="mt-8 text-[9.5px] leading-snug text-gray-500" data-testid="apr-disclaimer">{ap.DISCLAIMER}</p>
</article>; };

export default function AppraisalPage() {
  const { id = '' } = useParams(); const [a, setA] = useState<Appraisal | null>(null); const [err, setErr] = useState<string | null>(null); const [valueInput, setValueInput] = useState(''); const file = useRef<HTMLInputElement>(null);
  useEffect(() => { void ap.getAppraisal(id).then((x) => { setA(x); setValueInput(x.value !== null ? String(x.value) : ''); }).catch((e) => setErr(e.message)); }, [id]);
  if (err) return <div className="text-sm text-rose-700">{err}</div>; if (!a) return null;
  const locked = a.status === 'final';
  const save = (patch: Parameters<typeof ap.updateAppraisal>[1]) => ap.updateAppraisal(a.id, patch).then(setA).catch((e) => setErr(e.message));
  const onFile = (f?: File | null) => { if (!f) return; const r = new FileReader(); r.onload = () => void ap.attachAfterPhoto(a.id, String(r.result)).then(setA); r.readAsDataURL(f); };
  return <div data-testid="appraisal-page" data-status={a.status} className="space-y-4">
    <style>{`@media print { body * { visibility: hidden; } .appraisal-doc, .appraisal-doc * { visibility: visible; } .appraisal-doc { position: fixed; inset: 0; margin: 0; width: auto; box-shadow: none; } }`}</style>
    <div className="flex items-start justify-between gap-4 print:hidden"><PageHeader title={`Appraisal ${a.number}`} subtitle={`${a.jobNumber} · ${a.fields.clientName} · ${locked ? `Final · signed by ${a.signedBy}` : 'Draft — auto-pulled fields and the placeholder value stay editable until you confirm them'}`} testId="appraisal-header" />
      <div className="flex shrink-0 items-center gap-2"><Link to={`/jobs/${a.jobId}`} data-testid="apr-back"><Button>← Job</Button></Link><Button data-testid="apr-download" onClick={() => window.print()}><Download size={13} /> Download PDF</Button>{!locked && <Button variant="primary" data-testid="apr-finalize" disabled={a.valueSource !== 'confirmed'} title={a.valueSource !== 'confirmed' ? 'Confirm the appraised value first' : undefined} onClick={() => void ap.finalizeAppraisal(a.id).then(setA).catch((e) => setErr(e.message))}><FileSignature size={13} /> Finalize & sign</Button>}{locked && <span data-testid="apr-locked" className="inline-flex items-center gap-1 rounded-sm bg-moss-50 px-2 py-1 text-xs font-medium text-moss-700"><Lock size={11} /> Locked · signed {fmtDate(a.signedAt!)}</span>}</div></div>
    <div className="grid grid-cols-[380px_1fr] gap-4 print:block">
      <div className="space-y-3 print:hidden">
        <Card title="Report" testId="apr-meta-card"><div className="grid grid-cols-2 gap-2 text-xs text-ink-500"><label>Date<input type="date" data-testid="apr-date-input" value={a.date} disabled={locked} onChange={(e) => void save({ date: e.target.value })} className={inp} /></label><label>Purpose<select data-testid="apr-purpose-select" value={a.purpose} disabled={locked} onChange={(e) => void save({ purpose: e.target.value as AppraisalPurpose })} className={inp}>{ap.PURPOSES.map((p) => <option key={p}>{p}</option>)}</select></label></div></Card>
        <Card title="Appraised value" subtitle={a.comparables.length ? `Placeholder = average of ${a.comparables.length} past invoices for ref ${a.fields.reference}: ${a.comparables.map(ap.fmtValue).join(', ')}` : `No invoice history for ref ${a.fields.reference} — no comparable data, enter manually`} testId="apr-value-card" className={a.valueSource === 'placeholder' ? 'border-l-[3px] border-amber-500' : a.valueSource === 'none' ? 'border-l-[3px] border-rose-500' : 'border-l-[3px] border-moss'}>
          <div className="flex items-center gap-2"><span className="text-sm">$</span><input data-testid="apr-value-input" type="number" min={0} step={50} value={valueInput} disabled={locked} onChange={(e) => setValueInput(e.target.value)} className={`${inp} mt-0 font-mono`} /><Button size="sm" variant="primary" data-testid="apr-value-confirm" disabled={locked || valueInput === ''} onClick={() => void save({ value: Number(valueInput) })}><Check size={12} /> Confirm</Button></div>
          <div className="mt-2 text-xs" data-testid="apr-value-state">{a.valueSource === 'placeholder' && <span className="inline-flex items-center gap-1 text-amber-800"><AlertTriangle size={11} /> Placeholder — unconfirmed until you edit or confirm it</span>}{a.valueSource === 'confirmed' && <span className="text-moss-700">Confirmed by appraiser</span>}{a.valueSource === 'none' && <span className="text-rose-700">Blank — enter a figure manually</span>}</div>
        </Card>
        <Card title="After-work photo" subtitle="Distinct from the intake reference photo — stored on the job as its own “after-work” slot" testId="apr-after-card"><input ref={file} type="file" accept="image/*" capture="environment" className="hidden" data-testid="apr-after-input" onChange={(e) => { onFile(e.target.files?.[0]); e.target.value = ''; }} /><div className="flex items-center gap-3">{a.afterPhotoUrl ? <img src={a.afterPhotoUrl} alt="" data-testid="apr-after-thumb" className="h-16 w-24 rounded-sm object-cover ring-1 ring-moss" /> : <div className="grid h-16 w-24 place-items-center rounded-sm border border-dashed border-line text-[10px] text-ink-400">none yet</div>}<Button size="sm" data-testid="apr-after-capture" disabled={locked} onClick={() => file.current?.click()}><Camera size={12} /> {a.afterPhotoUrl ? 'Replace' : 'Capture / upload'}</Button><Button size="sm" data-testid="apr-after-sample" disabled={locked} onClick={() => void ap.attachAfterPhoto(a.id, `https://picsum.photos/seed/after-${a.id}/640/480`).then(setA)}>Use sample</Button></div></Card>
        <Card title="Fields · auto-pulled from the job" subtitle="Edit anything that reads wrong; nothing here was retyped" testId="apr-fields-card"><div className="grid grid-cols-2 gap-2 text-xs text-ink-500">{F.map(({ k, l }) => <label key={k} className={k === 'condition' || k === 'clientName' ? 'col-span-2' : ''}>{l}<input data-testid={`apr-input-${k}`} value={a.fields[k]} disabled={locked} onChange={(e) => void save({ fields: { ...a.fields, [k]: e.target.value } })} className={inp} /></label>)}<label className="col-span-2">Authenticity statement<textarea data-testid="apr-input-authenticity" value={a.authenticity} disabled={locked} rows={3} onChange={(e) => void save({ authenticity: e.target.value })} className="mt-0.5 w-full rounded-sm border border-line bg-canvas px-2 py-1 text-[12px] focus:border-ink focus:outline-none disabled:opacity-60" /></label></div></Card>
      </div>
      <div className="overflow-auto rounded-md bg-ink-100/40 p-4 print:p-0"><AppraisalDocument a={a} /></div>
    </div>
  </div>;
}
