import { Printer, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import * as api from '@/api/client';
import type { JobCategoryKey, JobReportFilter, JobReportRow, QuickReportKey, ReportStatusKey } from '@/api/client';
import { fmtDate, fullName } from '@/lib/format';

const chip = (on: boolean) => `rounded-full border px-2.5 py-1 text-xs font-medium transition-colors ${on ? 'border-amber-400 bg-amber-400 text-[#161b22]' : 'border-white/15 text-slate-300 hover:bg-white/5'}`;
const field = 'rounded-md border border-white/10 bg-[#0f131a] px-2 py-1.5 text-xs text-slate-100';

// RW Reports — modeled on the legacy RolliWorks Reports screen: quick presets, combinable filters, results table, real 8.5×11 print layout
export default function RwReportsPage() {
  const [f, setF] = useState<JobReportFilter>({}); const [rows, setRows] = useState<JobReportRow[]>([]); const [at, setAt] = useState('');
  useEffect(() => { api.getJobReport(f).then((r) => { setRows(r.rows); setAt(r.generatedAt); }); }, [f]);
  const tog = <K extends 'statuses' | 'categories'>(k: K, v: NonNullable<JobReportFilter[K]>[number]) => setF((x) => { const cur = (x[k] ?? []) as string[]; return { ...x, [k]: cur.includes(v) ? cur.filter((y) => y !== v) : [...cur, v] }; });
  const quick = api.QUICK_REPORTS.find((r) => r.key === f.quick); const active = !!(f.quick || f.from || f.to || f.movementOnly || f.statuses?.length || f.categories?.length);
  const summary = [quick?.label, f.from && `from ${fmtDate(f.from)}`, f.to && `to ${fmtDate(f.to)}`, f.movementOnly && 'movement services only', ...(f.statuses ?? []).map((k) => api.REPORT_STATUSES.find((s) => s.key === k)!.label), ...(f.categories ?? []).map((k) => api.JOB_CATEGORIES.find((c) => c.key === k)!.label)].filter(Boolean).join(' · ') || 'All jobs · no filters';
  return <div data-testid="rw-reports-page" className="space-y-4">
    <div className="flex flex-wrap items-end justify-between gap-3 print:hidden"><div><h1 className="text-lg font-semibold text-white">Reports</h1><p className="text-xs text-slate-400">Quick reports load instantly · filters combine with a preset or stand alone · Print renders US Letter</p></div><button data-testid="report-print" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-md bg-amber-400 px-4 py-2 text-sm font-semibold text-[#161b22]"><Printer size={15} /> Print Report</button></div>

    <section data-testid="quick-reports" className="grid grid-cols-2 gap-2 print:hidden sm:grid-cols-3 lg:grid-cols-6">{api.QUICK_REPORTS.map((r) => <button key={r.key} data-testid={`quick-${r.key}`} aria-pressed={f.quick === r.key} onClick={() => setF((x) => ({ ...x, quick: x.quick === r.key ? undefined : (r.key as QuickReportKey) }))} className={`rounded-xl border p-3 text-left ${f.quick === r.key ? 'border-amber-400 bg-amber-400/10' : 'border-white/10 bg-[#1f2630] hover:bg-white/5'}`}><div className="text-sm font-semibold text-white">{r.label}</div><div className="mt-0.5 text-[11px] text-slate-400">{r.blurb}</div></button>)}</section>

    <section data-testid="report-filters" className="space-y-3 rounded-xl border border-white/10 bg-[#1f2630] p-4 print:hidden">
      <div className="flex flex-wrap items-center gap-3 text-xs text-slate-300"><label className="flex items-center gap-1.5">Intake from <input data-testid="filter-from" type="date" value={f.from ?? ''} onChange={(e) => setF({ ...f, from: e.target.value || undefined })} className={field} /></label><label className="flex items-center gap-1.5">to <input data-testid="filter-to" type="date" value={f.to ?? ''} onChange={(e) => setF({ ...f, to: e.target.value || undefined })} className={field} /></label>
        <label className="flex items-center gap-1.5"><input data-testid="filter-movement" type="checkbox" checked={!!f.movementOnly} onChange={(e) => setF({ ...f, movementOnly: e.target.checked || undefined })} /> Movement services only</label>
        {active && <button data-testid="filter-clear" onClick={() => setF({})} className="ml-auto inline-flex items-center gap-1 rounded-md border border-white/15 px-2.5 py-1 text-xs text-slate-200 hover:bg-white/5"><X size={12} /> Clear Filters</button>}</div>
      <div><div className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-slate-500">Job status</div><div className="flex flex-wrap gap-1.5" data-testid="filter-statuses">{api.REPORT_STATUSES.map((s) => <button key={s.key} data-testid={`status-${s.key}`} aria-pressed={f.statuses?.includes(s.key)} onClick={() => tog('statuses', s.key as ReportStatusKey)} className={chip(!!f.statuses?.includes(s.key))}>{s.label}</button>)}</div></div>
      <div><div className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-slate-500">Categories</div><div className="flex flex-wrap gap-1.5" data-testid="filter-categories">{api.JOB_CATEGORIES.filter((c) => !['in_progress', 'in_testing', 'awaiting_inspection'].includes(c.key)).map((c) => <button key={c.key} data-testid={`category-${c.key}`} aria-pressed={f.categories?.includes(c.key)} onClick={() => tog('categories', c.key as JobCategoryKey)} className={chip(!!f.categories?.includes(c.key))}>{c.label}</button>)}</div></div>
    </section>

    <section data-testid="report-results" className="print-area rounded-xl border border-white/10 bg-[#1f2630] print:border-0 print:bg-white print:text-black">
      <div className="print-header hidden print:block"><h1>{quick?.label ?? 'Job report'} — RolliWorks</h1><p>{summary}</p><p>Generated {at && `${fmtDate(at)} ${new Date(at).toLocaleTimeString()}`} · {rows.length} job{rows.length === 1 ? '' : 's'}</p></div>
      <div className="flex items-center justify-between border-b border-white/10 px-3 py-2 text-xs text-slate-400 print:hidden"><span data-testid="report-summary">{summary}</span><span data-testid="report-count" className="font-semibold text-white">{rows.length} job{rows.length === 1 ? '' : 's'} match your criteria</span></div>
      <table data-testid="report-table" className="w-full text-xs"><thead><tr className="text-left text-[10px] uppercase tracking-wide text-slate-500 print:text-black"><th className="px-3 py-1.5 font-medium">Client</th><th className="px-3 py-1.5 font-medium">Watch</th><th className="px-3 py-1.5 font-medium">Estimate #</th><th className="px-3 py-1.5 font-medium">Job type</th><th className="px-3 py-1.5 font-medium">Status</th><th className="px-3 py-1.5 font-medium">Intake</th><th className="px-3 py-1.5 font-medium">Due</th><th className="px-3 py-1.5 text-right font-medium">Days</th></tr></thead>
        <tbody>{rows.map((r) => <tr key={r.job.id} data-testid={`report-row-${r.job.id}`} className="border-t border-white/5 print:border-gray-300"><td className="px-3 py-1.5"><Link to={`/rw/jobs/${r.job.id}`} className="font-medium text-slate-100 hover:underline print:text-black">{fullName(r.job.client)}</Link><span className="ml-1.5 font-mono text-slate-500">{r.job.number}</span></td><td className="px-3 py-1.5 text-slate-300 print:text-black">{r.job.watch.brand} {r.job.watch.model} <span className="font-mono text-slate-500">{r.job.watch.reference}</span></td><td className="px-3 py-1.5 font-mono text-slate-400 print:text-black">{r.estimateNumber ?? '—'}</td><td className="px-3 py-1.5 text-slate-300 print:text-black">{r.jobType}</td><td className="px-3 py-1.5 text-slate-300 print:text-black">{r.statusLabel}</td><td className="px-3 py-1.5 text-slate-400 print:text-black">{fmtDate(r.intake)}</td><td className="px-3 py-1.5 text-slate-400 print:text-black">{r.due ? fmtDate(r.due) : '—'}</td><td data-testid={`report-days-${r.job.id}`} className={`px-3 py-1.5 text-right font-mono ${r.overdue ? 'font-bold text-rose-400 print:text-red-700' : 'text-slate-300 print:text-black'}`}>{f.quick === 'approval_wait' && r.waitingDays !== undefined ? `${r.waitingDays} waiting` : r.overdue ? `${Math.abs(r.days!)} overdue` : r.days !== undefined ? r.days : '—'}</td></tr>)}{!rows.length && <tr><td colSpan={8} className="px-3 py-6 text-center text-slate-500">No jobs match your criteria.</td></tr>}</tbody></table>
    </section>
  </div>;
}
