import clsx from 'clsx';
import { AlertTriangle, Mail, RefreshCw, Tag, Truck, Undo2 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import * as api from '@/api/client';
import type { InboundCounts, ShipStage, ShipmentWithRefs } from '@/api/client';
import { AgeChip, CreateLabelSheet, TrackingPanel } from '@/components/shipping/ShippingBits';
import { Button } from '@/components/ui/Button';
import { fmtDate, fmtMoney, fmtTime, fullName } from '@/lib/format';

const STAGES: { key: ShipStage; label: string }[] = [{ key: 'label_requested', label: '1 · Label Requests' }, { key: 'label_sent', label: '2 · Labels Sent (outstanding)' }, { key: 'in_transit', label: '3 · In Transit' }, { key: 'delivered_unscanned', label: '4 · Delivered — awaiting arrival scan' }];
const th = 'px-3 py-1.5 text-left text-[11px] font-semibold uppercase tracking-wide text-ink-500';
const td = 'px-3 py-2 text-xs text-ink-700';

// Pre-arrival flow: same stage-tab pattern as Intake. Carrier calls go only through src/api/carriers/parcelpro.ts.
export default function InboundShippingPage() {
  const [params, setParams] = useSearchParams(); const stage = (params.get('stage') as ShipStage) || 'label_requested'; const track = params.get('track');
  const [rows, setRows] = useState<ShipmentWithRefs[]>([]); const [counts, setCounts] = useState<InboundCounts | null>(null); const [create, setCreate] = useState<string | null>(null); const [flash, setFlash] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(() => api.getInboundBoard().then((b) => { setRows(b.rows); setCounts(b.counts); }), []);
  useEffect(() => { void load(); }, [load]);
  const go = (patch: Record<string, string | undefined>) => { const p = new URLSearchParams(params); Object.entries(patch).forEach(([k, v]) => (v ? p.set(k, v) : p.delete(k))); setParams(p); };
  const run = async (f: () => Promise<unknown>, m: string) => { try { setError(null); await f(); await load(); setFlash(m); setTimeout(() => setFlash(null), 3000); } catch (e) { setError(e instanceof Error ? e.message : 'Failed'); } };
  const list = rows.filter((r) => r.stage === stage); const arriving = list.filter((r) => r.arrivingToday);
  const kpis = counts ? [['labels-to-send', 'Labels to send today', counts.label_requested, 'stage 1', 'label_requested'], ['outstanding', 'Outstanding labels', counts.label_sent, counts.red30 ? `${counts.red30} over 30 days` : 'none over 30 days', 'label_sent'], ['in-transit', 'In transit', counts.in_transit, 'carrier has scanned', 'in_transit'], ['arriving-today', 'Arriving today', counts.arrivingToday, 'out for delivery', 'in_transit'], ['unscanned', 'Delivered, unscanned', counts.delivered_unscanned, 'needs arrival scan', 'delivered_unscanned']] as const : [];
  const Row = ({ r, children }: { r: ShipmentWithRefs; children: React.ReactNode }) => <tr data-testid={`ship-row-${r.id}`} className={clsx('border-t border-line/70', r.stage === 'delivered_unscanned' && r.unscannedHours > 4 && 'bg-rose-50/60')}><td className={td}><button data-testid={`ship-open-${r.id}`} onClick={() => go({ track: r.id })} className="font-mono font-medium text-brand hover:underline">{r.estimate.number}</button>{r.reissued && <span className="ml-1 rounded-sm bg-amber-100 px-1 text-[10px] text-amber-800">reissued</span>}</td><td className={td}><Link to={`/clients/${r.clientId}`} className="hover:underline">{fullName(r.client)}</Link></td>{children}</tr>;
  return <div data-testid="inbound-shipping-page" className="flex h-full flex-col">
    <div className="mb-3"><h1 className="text-xl font-semibold tracking-tight text-ink">Shipping — Inbound</h1><p className="mt-0.5 text-xs text-ink-500">Everything before a package reaches Intake · Arrival. Four stages, left to right · every action stamped who / station / when · carrier via the Parcel Pro adapter (stub)</p></div>
    {counts && <div data-testid="inbound-kpi-row" className="mb-4 grid grid-cols-5 gap-3">{kpis.map(([k, l, v, hint, st], i) => <button key={k} data-testid={`kpi-${k}`} onClick={() => go({ stage: st, track: undefined })} style={{ animationDelay: `${i * 40}ms` }} className={clsx('animate-rise rounded-md bg-surface p-3.5 text-left shadow-card transition-[transform,box-shadow] hover:-translate-y-px hover:shadow-pop', k === 'unscanned' && v > 0 && 'ring-1 ring-rose-300')}><div className="text-[11px] font-semibold uppercase tracking-wide text-ink-500">{l}</div><div data-testid={`kpi-${k}-value`} className="tabular mt-1.5 text-2xl font-semibold leading-none tracking-tight text-ink">{v}</div><div className={clsx('mt-1.5 text-[11px]', k === 'outstanding' && counts.red30 ? 'font-semibold text-rose-700' : 'text-ink-400')}>{hint}</div></button>)}</div>}
    <nav data-testid="inbound-stage-tabs" className="mb-3 flex gap-1 border-b border-line">{STAGES.map((s) => <button key={s.key} data-testid={`inbound-tab-${s.key}`} onClick={() => go({ stage: s.key })} className={clsx('-mb-px inline-flex h-9 items-center gap-2 border-b-2 px-3 text-[13px] font-medium', stage === s.key ? 'border-ink text-ink' : 'border-transparent text-ink-500 hover:text-ink')}>{s.label}{counts && <span data-testid={`inbound-count-${s.key}`} className="tabular rounded-full bg-canvas px-1.5 text-[11px] text-ink-500 ring-1 ring-line">{counts[s.key as keyof InboundCounts]}</span>}</button>)}</nav>
    {flash && <div data-testid="inbound-flash" className="mb-2 rounded-sm bg-moss-50 px-3 py-1.5 text-xs font-medium text-moss-700">{flash}</div>}
    {error && <div data-testid="inbound-error" className="mb-2 rounded-sm bg-rose-50 px-3 py-1.5 text-xs text-rose-700">{error}</div>}
    {stage === 'in_transit' && arriving.length > 0 && <div data-testid="arriving-today" className="mb-3 rounded-md border border-sky-200 bg-sky-50 p-3"><div className="mb-1 inline-flex items-center gap-1.5 text-xs font-semibold text-sky-800"><Truck size={13} /> Arriving today · {arriving.length} out for delivery</div><ul className="text-xs text-ink-700">{arriving.map((r) => <li key={r.id} data-testid={`arriving-${r.id}`}><button onClick={() => go({ track: r.id })} className="font-mono text-brand hover:underline">{r.estimate.number}</button> · {fullName(r.client)} · {r.carrier} {r.trackingNumber} · {r.lastEvent?.location} · insured {fmtMoney(r.declaredValue)}</li>)}</ul></div>}
    <div className="min-h-0 flex-1 overflow-auto rounded-md bg-surface shadow-card"><table className="w-full"><thead><tr>
      <th className={th}>Est #</th><th className={th}>Client</th>
      {stage === 'label_requested' && <><th className={th}>Declared value</th><th className={th}>Dest.</th><th className={th}>Requested</th><th className={th}>Age</th><th className={th} /></>}
      {stage === 'label_sent' && <><th className={th}>Tracking #</th><th className={th}>Carrier</th><th className={th}>Label sent</th><th className={th}>Outstanding</th><th className={th} /></>}
      {stage === 'in_transit' && <><th className={th}>Tracking #</th><th className={th}>Last event</th><th className={th}>ETA</th><th className={th} /></>}
      {stage === 'delivered_unscanned' && <><th className={th}>Tracking #</th><th className={th}>Delivered</th><th className={th}>Unscanned for</th><th className={th} /></>}
    </tr></thead><tbody>
      {list.map((r) => <Row key={r.id} r={r}>
        {stage === 'label_requested' && <><td className={td}><span data-testid={`ship-value-${r.id}`} className="rounded-sm bg-amber-50 px-1.5 py-0.5 font-mono font-semibold text-amber-900">{fmtMoney(r.declaredValue)}</span></td><td className={td}>{r.destinationState}</td><td className={td}>{fmtDate(r.requestedAt)}</td><td className={td}><AgeChip days={r.ageDays} testId={`ship-age-${r.id}`} green={7} red={9999} /></td><td className={`${td} text-right`}><Button size="sm" variant="primary" data-testid={`ship-create-${r.id}`} onClick={() => setCreate(r.id)}><Tag size={12} /> Create label</Button></td></>}
        {stage === 'label_sent' && <><td className={`${td} font-mono`}>{r.trackingNumber}</td><td className={td}>{r.carrier}</td><td className={td}>{fmtDate(r.labelSentAt!)}</td><td className={td}><AgeChip days={r.outstandingDays} testId={`ship-outstanding-${r.id}`} /></td><td className={`${td} text-right`}><span className="inline-flex gap-1"><Button size="sm" data-testid={`ship-resend-${r.id}`} onClick={() => run(() => api.resendLabelEmail(r.id), 'Label email re-queued to Outbox')}><Mail size={12} /> Resend</Button><Button size="sm" data-testid={`ship-followup-${r.id}`} onClick={() => run(() => api.followUpLabel(r.id), 'Follow-up reminder queued')}><RefreshCw size={12} /> Follow up</Button><Button size="sm" data-testid={`ship-void-${r.id}`} onClick={() => run(() => api.voidAndReissue(r.id), 'Label voided · back to Label Requests (reissue)')}><Undo2 size={12} /> Void + reissue</Button></span></td></>}
        {stage === 'in_transit' && <><td className={`${td} font-mono`}>{r.trackingNumber}</td><td className={td}><span data-testid={`ship-last-${r.id}`}>{r.lastEvent ? `${r.lastEvent.status} · ${r.lastEvent.location}` : '—'}</span>{r.lastEvent && <span className="ml-1 text-ink-400">{fmtDate(r.lastEvent.at)} {fmtTime(r.lastEvent.at)}</span>}</td><td className={td}>{r.eta ? fmtDate(r.eta) : '—'}</td><td className={`${td} text-right`}><Button size="sm" data-testid={`ship-sim-${r.id}`} onClick={() => run(() => api.simulateTrackingEvent(r.id), 'Tracking event simulated')}>Simulate tracking event</Button></td></>}
        {stage === 'delivered_unscanned' && <><td className={`${td} font-mono`}>{r.trackingNumber}</td><td className={td}>{fmtDate(r.deliveredAt!)} {fmtTime(r.deliveredAt!)}</td><td className={td}><span data-testid={`ship-unscanned-${r.id}`} className={clsx('inline-flex items-center gap-1 rounded-full px-1.5 py-0.5 text-[10px] font-semibold', r.unscannedHours > 4 ? 'bg-rose-100 text-rose-800' : 'bg-canvas text-ink-600')}>{r.unscannedHours > 4 && <AlertTriangle size={10} />} {r.unscannedHours}h</span></td><td className={`${td} text-right`}><Link to="/intake" data-testid={`ship-arrival-${r.id}`} className="text-brand hover:underline">Scan at Arrival →</Link></td></>}
      </Row>)}
      {!list.length && <tr><td colSpan={8} className="px-3 py-8 text-center text-xs text-ink-400">{stage === 'delivered_unscanned' ? 'Nothing delivered without a check-in — the way it should be by end of day.' : 'Nothing in this stage.'}</td></tr>}
    </tbody></table></div>
    {create && <CreateLabelSheet id={create} onClose={() => setCreate(null)} onDone={(m) => { void load(); setFlash(m); setTimeout(() => setFlash(null), 4000); go({ stage: 'label_sent' }); }} />}
    {track && <TrackingPanel id={track} onClose={() => { go({ track: undefined }); void load(); }} />}
  </div>;
}
