// E17 — HTTP implementation of the client functions the /contract covers, same TypeScript signatures the app already uses.
// Generated by hand from GET /contract on 2026-09-27 (the contract is a stub: endpoint patterns, no maps_to). Field mapping is trivial snake→camel only;
// anything the API does not return is left undefined / empty so the mismatch stays visible (see docs/E17-CONVERGENCE-REPORT.md). No adapter shims.
import { API_BASE_URL } from './config';
import type { ActivityEvent, Client, DashboardStats, Estimate, EstimateLine, EstimateWithRefs, Job, JobWithRefs, PackageStatus, PackageWithRefs, SalesOrder, SalesOrderWithRefs, SearchHit, SearchResults, ServiceRequest, TodayView, User, VerificationPhoto } from './types';
import { users } from './fixtures';

const TOKEN_KEY = 'rollisuite.api.token';
const DEVICE_KEY = 'rollisuite.api.deviceId';
export const apiToken = () => localStorage.getItem(TOKEN_KEY);
// switch-user is device-bound: one stable UUID per browser, minted once
const deviceId = () => { let d = localStorage.getItem(DEVICE_KEY); if (!d) { d = `web-${crypto.randomUUID()}`; localStorage.setItem(DEVICE_KEY, d); } return d; };

export class ApiError extends Error { constructor(public status: number, public code: string | undefined, message: string) { super(message); } }
async function http<T>(method: 'GET' | 'POST', path: string, body?: unknown): Promise<T> {
  const headers: Record<string, string> = { 'Content-Type': 'application/json' }; const t = apiToken(); if (t) headers.Authorization = `Bearer ${t}`;
  const res = await fetch(`${API_BASE_URL}${path}`, { method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  const text = await res.text(); let data: unknown = null; try { data = text ? JSON.parse(text) : null; } catch { data = text; }
  if (!res.ok) { const d = data as { message?: string; code?: string } | null; throw new ApiError(res.status, d?.code, `${method} ${path} → ${res.status}${d?.message ? ` · ${d.message}` : ''}`); }
  return data as T;
}
const get = <T,>(path: string) => http<T>('GET', path);
const post = <T,>(path: string, body: unknown) => http<T>('POST', path, body);

// ---- wire shapes (as observed) ----
interface WireCustomer { id: string; first_name?: string; last_name?: string; full_name?: string; email?: string | null; phone?: string | null }
interface WireEstimate { id: string; estimate_number: string; status: string; valid_until?: string | null; customer_id?: string; customer?: WireCustomer | null; watch_id?: string | null; job_id?: string | null; tracking_number?: string | null; watch_brand?: string | null; watch_model?: string | null; watch_serial?: string | null; watch_reference?: string | null; note_to_customer?: string | null; subtotal?: number; tax_amount?: number; total_amount?: number; created_at?: string; converted_at?: string | null; lines?: WireLine[] }
interface WireLine { id: string; line_type?: string; description: string; quantity: number; unit_price: number; part_number?: string | null }
interface WireWatch { id?: string | null; brand?: string | null; model?: string | null; reference?: string | null; serial?: string | null }
interface WireTimeline { id: string; from?: string | null; to: string; action: string; reason?: string | null; at: string; by?: string | null; station?: string | null }
interface WireHold { id: string; type: string; reason?: string | null; prior_status?: string | null; placed_at?: string; placed_by?: string | null; station?: string | null; released_at?: string | null; released_by?: string | null; release_note?: string | null; note?: string | null }
interface WireJob { id: string; number?: string; watch_reference?: string | null; simple_status?: string; watch_id?: string | null; watch?: WireWatch | null; customer?: WireCustomer | null; lines?: WireLine[]; total?: number; timeline?: WireTimeline[]; holds?: WireHold[]; estimate_id?: string | null; estimate_number?: string | null; entity_id?: string; status: string; job_kind?: string; workflow_codes?: string[]; owner_user_id?: string | null; assignee_user_ids?: string[]; target_date?: string | null; discrepancy_hold?: boolean; created_at?: string; updated_at?: string | null; customer_name?: string | null; customer_id?: string | null }
interface WireSO { id: string; so_number: string; status: string; customer_id?: string; customer?: WireCustomer | null; job_id?: string | null; shipping_amount?: number; total_amount?: number; tracking_number?: string | null; ship_date?: string | null; picked_up_at?: string | null; is_paid?: boolean; fulfillment_channel?: string; created_at?: string; lines?: WireLine[] }
interface WireList<T> { items: T[] }

const client = (c?: WireCustomer | null, id?: string): Client => { const [fn = '', ...rest] = (c?.full_name ?? '').split(' '); return { id: c?.id ?? id ?? '', firstName: c?.first_name ?? fn, lastName: c?.last_name ?? rest.join(' '), email: c?.email ?? '', phone: c?.phone ?? '', street: '', city: '', state: '', type: 'retail', since: '' } as Client; };
const line = (l: WireLine): EstimateLine => ({ id: l.id, description: l.description, qty: l.quantity, unitPrice: l.unit_price, dept: 'W', taxable: false, type: l.line_type === 'part' ? 'part' : 'service', partNumber: l.part_number ?? undefined } as EstimateLine);
const estimate = (w: WireEstimate): EstimateWithRefs => ({
  id: w.id, number: w.estimate_number, revision: 1, revisions: [], clientId: w.customer_id ?? w.customer?.id ?? '', watchId: w.watch_id ?? undefined, department: 'watchmaking', status: w.status as Estimate['status'],
  lines: (w.lines ?? []).map(line), subtotal: w.subtotal ?? w.total_amount ?? 0, shippingAmount: 0, taxAmount: w.tax_amount ?? 0, total: w.total_amount ?? 0, validUntil: w.valid_until ?? '', clientNotes: w.note_to_customer ?? '', messageNotes: '', internalNotes: '',
  billingAddress: { street: '', city: '', state: '', zip: '' }, shippingAddress: { street: '', city: '', state: '', zip: '' }, shippingMirrorsBilling: true, historical: false, createdAt: w.created_at ?? '', createdBy: '', updatedAt: w.created_at ?? '', convertedAt: w.converted_at ?? undefined, jobId: w.job_id ?? undefined,
  client: client(w.customer, w.customer_id), watch: w.watch_brand ? ({ id: w.watch_id ?? '', clientId: w.customer_id ?? '', brand: w.watch_brand, model: w.watch_model ?? '', reference: w.watch_reference ?? '', serial: w.watch_serial ?? '' } as EstimateWithRefs['watch']) : null,
} as unknown as EstimateWithRefs);
// API status "complete" is read as ready_to_ship (Cursor's judgment call, flagged); snake_case holds/timeline mapped to camelCase
const JOB_STATUS_MAP: Record<string, Job['status']> = { complete: 'ready_to_ship', completed: 'ready_to_ship', awaiting_inspection: 'in_review', awaiting_approval: 'awaiting_customer_approval', awaiting_parts: 'in_service', hold: 'in_service', on_hold: 'in_service' };
const hold = (h: WireHold): Job['holds'][number] => ({ id: h.id, type: h.type as Job['holds'][number]['type'], reason: h.reason ?? '', priorStatus: (JOB_STATUS_MAP[h.prior_status ?? ''] ?? (h.prior_status as Job['status'] | undefined) ?? 'in_service'), placedAt: h.placed_at ?? '', placedBy: h.placed_by ?? '', station: h.station ?? '', releasedAt: h.released_at ?? undefined, releasedBy: h.released_by ?? undefined, releaseNote: h.release_note ?? h.note ?? undefined });
// Live vocabulary observed 2026-09-27 (all 100 rows in /jobs): status ∈ {intake, in_review, in_service, ready_to_ship} (already UI vocabulary), simple_status ∈ {on_hand}.
// Anything outside the unions is NOT silently defaulted: it is derived where the rule is unambiguous and recorded in `wireWarnings` (shown on the job detail) + console.warn.
const JOB_STATUSES: Job['status'][] = ['intake', 'in_review', 'awaiting_customer_approval', 'approved', 'in_service', 'testing', 'awaiting_manager_review', 'ready_to_ship', 'closed'];
const SIMPLE_STATUSES: Job['simpleStatus'][] = ['estimate', 'on_hand', 'finished'];
export const wireWarnings: { jobId: string; field: string; value: unknown; resolved: string }[] = [];
const warn = (jobId: string, field: string, value: unknown, resolved: string) => { wireWarnings.push({ jobId, field, value, resolved }); console.warn(`[realClient] job ${jobId}: unmapped ${field}=${JSON.stringify(value)} → ${resolved}`); };
const mapStatus = (w: WireJob): Job['status'] => { const raw = w.status; if ((JOB_STATUSES as string[]).includes(raw)) return raw as Job['status']; if (JOB_STATUS_MAP[raw]) return JOB_STATUS_MAP[raw]; warn(w.id, 'status', raw, 'intake'); return 'intake'; };
const mapSimple = (w: WireJob, status: Job['status']): Job['simpleStatus'] => { const raw = w.simple_status; if (raw && (SIMPLE_STATUSES as string[]).includes(raw)) return raw as Job['simpleStatus']; const derived: Job['simpleStatus'] = status === 'closed' || status === 'ready_to_ship' ? 'finished' : 'on_hand'; if (raw !== undefined && raw !== null) warn(w.id, 'simple_status', raw, derived); return derived; };
const job = (w: WireJob): JobWithRefs => ({
  id: w.id, number: w.number ?? w.estimate_number ?? w.id.slice(0, 8), clientId: w.customer_id ?? w.customer?.id ?? '', watchId: w.watch_id ?? '', estimateId: w.estimate_id ?? undefined, department: 'watchmaking', workflow: (w.workflow_codes ?? []) as Job['workflow'], kind: (w.job_kind ?? 'service') as Job['kind'],
  status: mapStatus(w), simpleStatus: mapSimple(w, mapStatus(w)), wireWarnings: wireWarnings.filter((x) => x.jobId === w.id).map((x) => `${x.field}=${JSON.stringify(x.value)} → ${x.resolved}`), priority: 'normal' as Job['priority'], division: (w.entity_id === 'rollishop' ? 'rollishop' : 'rolliworks') as Job['division'], lines: (w.lines ?? []).map(line), total: w.total ?? 0, assignees: w.assignee_user_ids ?? [], dueAt: w.target_date ?? undefined,
  createdAt: w.created_at ?? '', createdBy: w.owner_user_id ?? '', timeline: (w.timeline ?? []).map((t) => ({ id: t.id, from: t.from ?? undefined, to: t.to, action: t.action, reason: t.reason ?? undefined, at: t.at, by: t.by ?? '—', station: t.station ?? '' })) as unknown as Job['timeline'], holds: (w.holds ?? []).map(hold), notes: [], photos: [], components: [],
  client: client(w.customer, w.customer_id ?? undefined), watch: { id: w.watch?.id ?? w.watch_id ?? '', clientId: w.customer_id ?? '', brand: w.watch?.brand ?? '', model: w.watch?.model ?? '', reference: w.watch?.reference ?? w.watch_reference ?? '', serial: w.watch?.serial ?? '', status: 'intake', photos: [], createdAt: w.created_at ?? '' } as unknown as JobWithRefs['watch'], estimate: null, pkg: null,
} as unknown as JobWithRefs);
const so = (w: WireSO): SalesOrderWithRefs => ({
  id: w.id, number: w.so_number, clientId: w.customer_id ?? w.customer?.id ?? '', jobId: w.job_id ?? undefined, status: w.status as SalesOrder['status'], channel: w.fulfillment_channel as SalesOrder['channel'], orderDate: w.created_at ?? '', shipDate: w.ship_date ?? undefined,
  lines: (w.lines ?? []).map((l) => ({ id: l.id, description: l.description, qty: l.quantity, rate: l.unit_price, pickedUpQty: 0, shippedQty: 0 })), shippingAmount: w.shipping_amount ?? 0, total: w.total_amount ?? 0, qboStatus: 'not_queued', payments: [], balanceDue: w.is_paid ? 0 : (w.total_amount ?? 0), isPaid: !!w.is_paid, payLinkToken: '', invoiceSends: [], tracking: w.tracking_number ?? undefined, pickedUpAt: w.picked_up_at ?? undefined,
  createdAt: w.created_at ?? '', createdBy: '', updatedAt: w.created_at ?? '', client: client(w.customer, w.customer_id), job: null, watch: null,
} as SalesOrderWithRefs);

// ---- auth ----
interface WireSession { session_token: string; user: { id: string; display_name: string; username: string } }
export async function signInWithPassword(userId: string, password: string, photo: VerificationPhoto): Promise<User> {
  const u = users.find((x) => x.id === userId); if (!u) throw new Error('Unknown user'); const username = u.id.replace(/^u-/, '');
  let session: WireSession;
  try { session = await post<WireSession>('/auth/sign-in', { username, password, device_id: deviceId() }); }
  catch (e) {
    // Password store on the API differs from the prototype's seeded passwords (see report). Verify locally, then bind the device with the PIN so bearer calls still work.
    if (!(e instanceof ApiError) || e.status !== 401 || u.password !== password) throw e;
    session = await post<WireSession>('/auth/switch-user', { username, pin: u.pin, device_id: deviceId(), camera_fallback: photo.cameraStatus !== 'captured' });
  }
  localStorage.setItem(TOKEN_KEY, session.session_token); localStorage.setItem('rollisuite.currentUser', u.id);
  return { ...u, displayName: session.user.display_name || u.displayName };
}

// ---- reads ----
export const getEstimates = async (): Promise<EstimateWithRefs[]> => (await get<WireList<WireEstimate>>('/estimates')).items.map(estimate);
export const getEstimate = async (id: string): Promise<EstimateWithRefs | null> => { try { return estimate(await get<WireEstimate>(`/estimates/${id}`)); } catch (e) { if (e instanceof ApiError && e.status === 404) return null; throw e; } };
export const getJobs = async (): Promise<JobWithRefs[]> => (await get<WireList<WireJob>>('/jobs')).items.map(job);
export const getJob = async (id: string): Promise<JobWithRefs | null> => { try { return job(await get<WireJob>(`/jobs/${id}`)); } catch (e) { if (e instanceof ApiError && e.status === 404) return null; throw e; } };
export const getSalesOrders = async (): Promise<SalesOrderWithRefs[]> => (await get<WireList<WireSO>>('/sales-orders')).items.map(so);
export const getSalesOrder = async (id: string): Promise<SalesOrderWithRefs | null> => { try { return so(await get<WireSO>(`/sales-orders/${id}`)); } catch (e) { if (e instanceof ApiError && e.status === 404) return null; throw e; } };
// Intake leads (portal / web / email asks) — NOT the in-memory job-level client requests (/client-requests)
interface WireLead { id: string; source?: string; full_name?: string | null; email?: string | null; phone?: string | null; watch_reference?: string | null; watch_serial?: string | null; item_type?: string | null; notes?: string | null; status?: string; customer_id?: string | null; awaiting_reply?: boolean; created_at?: string }
export const getRequests = async (): Promise<ServiceRequest[]> => { const r = await get<WireList<WireLead>>('/intake/leads'); return r.items.map((x) => ({ id: x.id, number: `RQ-${(x.created_at ?? '').slice(2, 4)}-${x.id.slice(0, 4).toUpperCase()}`, clientId: x.customer_id ?? '', source: (x.source === 'wix' ? 'web' : x.source ?? 'web') as ServiceRequest['source'], status: (x.status === 'open' ? (x.awaiting_reply ? 'new' : 'in_progress') : x.status ?? 'new') as ServiceRequest['status'], summary: [x.full_name, x.watch_reference, x.notes].filter(Boolean).join(' · '), createdAt: x.created_at ?? '', createdBy: x.full_name ?? '', station: x.email ?? '' } as unknown as ServiceRequest)); };
interface WirePackage { id: string; carrier?: string; tracking_number?: string; receive_status: string; matched_estimate_id?: string | null; estimate_number?: string | null; scanned_by?: string; scanned_at?: string; received_by?: string | null; received_at?: string | null; memo?: string | null }
// receive_status vocabulary on the wire (received · pending · needs_review · not_client_asset) ≠ PackageStatus; passed through as-is so the mismatch stays visible
const pkg = (w: WirePackage): PackageWithRefs => ({ id: w.id, subNumber: w.estimate_number ? `EST ${w.estimate_number}` : w.id.slice(0, 8), source: w.carrier === 'In-Person' ? 'walk_in' : 'carrier', carrier: (w.carrier ?? 'Unknown') as PackageWithRefs['carrier'], trackingNumber: w.tracking_number, signatureNoted: false, estimateId: w.matched_estimate_id ?? undefined, status: w.receive_status as PackageStatus, arrivedAt: w.scanned_at ?? '', arrivedBy: w.scanned_by ?? '', arrivedStation: '', contents: [], photos: [], receiptPrinted: false, processedAt: w.received_at ?? undefined, processedBy: w.received_by ?? undefined, notes: w.memo ?? undefined, client: null, estimate: null } as unknown as PackageWithRefs);
export const getPackages = async (status?: PackageStatus): Promise<PackageWithRefs[]> => { const r = await get<WireList<WirePackage>>(`/intake/packages${status ? `?status=${status}` : ''}`); return r.items.map(pkg); };
export const getToday = async (userId?: string): Promise<TodayView> => {
  const uid = (userId ?? localStorage.getItem('rollisuite.currentUser') ?? 'u-michael').replace(/^u-/, '');
  const r = await get<{ items: Record<string, unknown>[] }>(`/today?user_id=${encodeURIComponent(uid)}`);
  return { pinned: [], rows: r.items.map((x, i) => ({ id: String(x.id ?? i), source: 'task', title: String(x.title ?? x.summary ?? ''), detail: String(x.detail ?? ''), via: 'API', overdue: false, urgent: false } as unknown as TodayView['rows'][number])), waitingOn: [] };
};
export const resolveIdentifier = async (query: string): Promise<SearchResults> => {
  const r = await get<{ clients: Record<string, string>[]; estimates: WireEstimate[]; jobs: WireJob[]; watches: Record<string, string>[]; q: string }>(`/search?q=${encodeURIComponent(query.trim())}`);
  const hit = (kind: SearchHit['kind'], id: string, label: string, detail: string, path: string, c?: WireCustomer | null): SearchHit => ({ kind, id, hitKey: `${kind}-${id}`, label, detail, matched: query, clientId: c?.id ?? '', clientName: c ? (c.full_name ?? `${c.first_name ?? ''} ${c.last_name ?? ''}`.trim()) : '', path } as SearchHit);
  const groups: SearchResults['groups'] = [];
  if (r.clients.length) groups.push({ kind: 'client', label: 'Clients', hits: r.clients.map((c) => hit('client', c.id, c.full_name ?? `${c.first_name} ${c.last_name}`, c.email ?? '', `/clients/${c.id}`, c as unknown as WireCustomer)) });
  if (r.estimates.length) groups.push({ kind: 'estimate', label: 'Estimates', hits: r.estimates.map((e) => hit('estimate', e.id, e.estimate_number, e.status, `/estimates/${e.id}`, e.customer)) });
  if (r.jobs.length) groups.push({ kind: 'job', label: 'Jobs', hits: r.jobs.map((j) => hit('job', j.id, j.estimate_number ?? j.id.slice(0, 8), j.status, `/jobs/${j.id}`)) });
  if (r.watches.length) groups.push({ kind: 'watch', label: 'Watches', hits: r.watches.map((w) => hit('watch', w.id, `${w.brand ?? ''} ${w.model ?? ''}`.trim(), w.serial ?? w.reference ?? '', `/clients/${w.customer_id ?? ''}`)) });
  return { query, groups, total: groups.reduce((t, g) => t + g.hits.length, 0) };
};
// No KPI / activity endpoints in the contract — derived from the three list endpoints (flagged in the report)
export const getDashboardStats = async (): Promise<DashboardStats> => {
  const [est, jobs, sos] = await Promise.all([getEstimates(), getJobs(), getSalesOrders()]); const month = new Date().toISOString().slice(0, 7);
  return { watchesInHouse: jobs.filter((j) => j.status !== 'closed').length, openEstimates: est.filter((e) => ['draft', 'sent'].includes(e.status)).length, awaitingApproval: est.filter((e) => e.status === 'sent').length, inProgress: jobs.filter((j) => ['in_service', 'testing'].includes(j.status)).length, awaitingPickup: sos.filter((o) => o.status === 'fulfilled').length, revenueThisMonth: sos.filter((o) => o.isPaid && o.orderDate.startsWith(month)).reduce((t, o) => t + o.total, 0), departments: [] };
};
export const getRecentActivity = async (limit = 10): Promise<ActivityEvent[]> => {
  const [est, jobs, sos] = await Promise.all([getEstimates(), getJobs(), getSalesOrders()]);
  const ev: ActivityEvent[] = [...est.map((e) => ({ id: `e-${e.id}`, type: 'estimate_sent' as ActivityEvent['type'], message: `Estimate ${e.number} · ${e.status} · ${e.client.firstName} ${e.client.lastName}`.trim(), actor: 'API', timestamp: e.createdAt })), ...jobs.map((j) => ({ id: `j-${j.id}`, type: 'job_started' as ActivityEvent['type'], message: `Job ${j.number} · ${j.status}${j.workflow.length ? ` · [${j.workflow.join('')}]` : ''}`, actor: j.createdBy || 'API', timestamp: j.createdAt })), ...sos.map((o) => ({ id: `o-${o.id}`, type: 'pickup' as ActivityEvent['type'], message: `${o.number} · ${o.status}${o.isPaid ? ' · paid' : ''}`, actor: 'API', timestamp: o.createdAt }))];
  return ev.filter((e) => e.timestamp).sort((a, b) => b.timestamp.localeCompare(a.timestamp)).slice(0, limit);
};
