import { ArrowDownToLine, ArrowUpFromLine, CheckCircle2, Copy, MapPin, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import * as api from '@/api/client';
import type { LabelPrep, ShipAddress, ShipCarrierName, ShipmentWithRefs } from '@/api/client';
import { Button } from '@/components/ui/Button';
import { fmtDate, fmtMoney, fmtTime } from '@/lib/format';

export const AgeChip = ({ days, testId, green = 7, red = 30 }: { days: number; testId?: string; green?: number; red?: number }) => (
  <span data-testid={testId} className={`rounded-full px-1.5 py-0.5 text-[10px] font-semibold ${days > red ? 'bg-rose-100 text-rose-800' : days >= green ? 'bg-amber-100 text-amber-800' : 'bg-moss-50 text-moss-700'}`}>{days}d</span>
);

// Slide-over the concierge reads top to bottom to a caller: status + ETA large, direction, label details, timeline newest-first, copyable one-liner
export const TrackingPanel = ({ id, others = [], onSelect, onClose }: { id: string; others?: ShipmentWithRefs[]; onSelect?: (id: string) => void; onClose: () => void }) => {
  const [s, setS] = useState<ShipmentWithRefs | null>(null); const [copied, setCopied] = useState(false); const [msg, setMsg] = useState<string | null>(null);
  const load = () => api.getShipment(id).then(setS); useEffect(() => { void load(); }, [id]); // eslint-disable-line react-hooks/exhaustive-deps
  if (!s) return null;
  const rest = others.filter((o) => o.id !== s.id);
  const line = api.clientStatusLine(s); const status = s.lastEvent?.status ?? api.SHIP_STAGE_LABEL[s.stage];
  const copy = async () => { try { await navigator.clipboard.writeText(line); } catch { /* clipboard blocked in some contexts */ } setCopied(true); setTimeout(() => setCopied(false), 2000); };
  return <div className="fixed inset-0 z-50 flex justify-end bg-ink/40" onClick={onClose}><aside data-testid="tracking-panel" onClick={(e) => e.stopPropagation()} className="flex h-full w-[460px] flex-col overflow-y-auto bg-surface shadow-pop animate-rise">
    <div className="flex items-start justify-between border-b border-line px-5 py-4"><div><div data-testid="tracking-direction" className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[11px] font-semibold ${s.direction === 'inbound' ? 'bg-sky-50 text-sky-700' : 'bg-violet-50 text-violet-700'}`}>{s.direction === 'inbound' ? <ArrowDownToLine size={11} /> : <ArrowUpFromLine size={11} />} {s.direction === 'inbound' ? 'Inbound · to us' : 'Outbound · to client'}</div>
      <div data-testid="tracking-status" className="mt-2 text-2xl font-semibold tracking-tight text-ink">{status}</div><div data-testid="tracking-eta" className="text-sm text-ink-600">{s.eta ? `ETA ${fmtDate(s.eta)}${s.arrivingToday ? ' · today' : ''}` : s.stage === 'label_sent' ? `label sent ${fmtDate(s.labelSentAt!)} · not yet scanned` : s.stage === 'label_requested' ? 'label not yet created' : s.deliveredAt ? `delivered ${fmtDate(s.deliveredAt)} ${fmtTime(s.deliveredAt)}` : ''}</div></div><button data-testid="tracking-close" onClick={onClose} className="rounded-sm p-1 text-ink-400 hover:bg-canvas"><X size={16} /></button></div>
    <div className="space-y-4 px-5 py-4 text-xs">
      <div className="rounded-md border border-line bg-canvas/50 p-3"><div className="font-semibold text-ink">{s.client.firstName} {s.client.lastName} · <span className="font-mono">{s.estimate.number}</span></div><div className="text-ink-600">{s.watch ? `${s.watch.brand} ${s.watch.model} · ${s.watch.reference}` : 'no watch on estimate'}</div>
        <dl className="mt-2 grid grid-cols-2 gap-x-3 gap-y-1 text-[11px]"><dt className="text-ink-400">Carrier · service</dt><dd data-testid="tracking-carrier" className="text-ink">{s.carrier} · {s.service}</dd><dt className="text-ink-400">Tracking #</dt><dd className="font-mono text-ink">{s.trackingNumber ?? '—'}</dd><dt className="text-ink-400">Insured value</dt><dd data-testid="tracking-insured" className="font-semibold text-ink">{fmtMoney(s.declaredValue)}</dd><dt className="text-ink-400">Label cost</dt><dd className="text-ink">{s.cost !== undefined ? fmtMoney(s.cost) : '—'}</dd>{s.labelUrl && <><dt className="text-ink-400">Label</dt><dd><a href={s.labelUrl} target="_blank" rel="noreferrer" className="text-brand hover:underline">PDF (mock)</a></dd></>}</dl></div>
      <div data-testid="tracking-client-line" className="rounded-md border border-amber-200 bg-amber-50 p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-amber-800">Say / paste this</div><p className="mt-1 text-[13px] leading-snug text-ink">{line}</p><Button size="sm" data-testid="tracking-copy" className="mt-2" onClick={copy}>{copied ? <><CheckCircle2 size={12} /> Copied</> : <><Copy size={12} /> Copy status for client</>}</Button></div>
      <div><div className="mb-1.5 font-semibold text-ink">Travel timeline · newest first</div><ol data-testid="tracking-events" className="space-y-2">{[...s.events].reverse().map((e, i) => <li key={i} data-testid={`tracking-event-${i}`} className="flex gap-2"><MapPin size={12} className="mt-0.5 shrink-0 text-ink-400" /><div><div className="font-medium text-ink">{e.status}</div><div className="text-ink-500">{e.location}{e.note && ` · ${e.note}`}</div><div className="text-[10px] text-ink-400">{fmtDate(e.at)} {fmtTime(e.at)}</div></div></li>)}{!s.events.length && <li className="text-ink-400">No carrier scans yet.</li>}</ol></div>
      {s.stage !== 'delivered_unscanned' && s.stage !== 'arrived' && s.trackingNumber && <Button size="sm" data-testid="tracking-simulate" onClick={() => api.simulateTrackingEvent(s.id).then(() => { setMsg('Tracking event added'); void load(); }).catch((e) => setMsg(e.message))}>Simulate next carrier scan</Button>}{msg && <span className="ml-2 text-ink-500">{msg}</span>}
      <div><div className="mb-1 font-semibold text-ink">Our stamps</div><ul className="space-y-0.5 text-[11px] text-ink-500">{[...s.stamps].reverse().map((st, i) => <li key={i}>{fmtDate(st.at)} {fmtTime(st.at)} · <b className="text-ink-700">{st.by}</b> · {st.station} · {st.action}</li>)}</ul></div>
      {rest.length > 0 && <div data-testid="tracking-others" className="border-t border-line pt-3"><div className="mb-1.5 font-semibold text-ink">Also for {s.client.firstName} · {rest.length} more</div><ul className="space-y-1">{rest.map((o) => <li key={o.id}><button data-testid={`tracking-other-${o.id}`} onClick={() => onSelect?.(o.id)} className="flex w-full items-center gap-2 rounded-sm border border-line bg-canvas/50 px-2 py-1.5 text-left hover:bg-canvas">{o.direction === 'inbound' ? <ArrowDownToLine size={11} className="text-sky-700" /> : <ArrowUpFromLine size={11} className="text-violet-700" />}<span className="font-mono text-ink">{o.estimate.number}</span><span className="text-ink-600">{o.lastEvent?.status ?? api.SHIP_STAGE_LABEL[o.stage]}</span><span className="ml-auto text-[10px] text-ink-400">{fmtDate(o.requestedAt)}</span></button></li>)}</ul></div>}
    </div></aside></div>;
};

// "Track package" affordance for Client 360 / Inbox — one button; anchored estimate's shipment first, else the client's shipments (most recent on top, rest listed in the panel)
export const TrackButton = ({ clientId, estimateId, testId = 'track-package' }: { clientId?: string; estimateId?: string; testId?: string }) => {
  const [rows, setRows] = useState<ShipmentWithRefs[]>([]); const [open, setOpen] = useState<string | null>(null);
  useEffect(() => {
    let live = true;
    (async () => {
      const [hit, mine] = await Promise.all([estimateId ? api.getShipmentForEstimate(estimateId) : Promise.resolve(null), clientId ? api.getShipmentsForClient(clientId) : Promise.resolve([] as ShipmentWithRefs[])]);
      const list = hit ? [hit, ...mine.filter((m) => m.id !== hit.id)] : mine;
      if (live) setRows(list);
    })();
    return () => { live = false; };
  }, [clientId, estimateId]);
  if (!rows.length) return null;
  const s = rows[0];
  return <><button data-testid={`${testId}-${s.id}`} onClick={() => setOpen(s.id)} className="inline-flex items-center gap-1 rounded-sm border border-line bg-surface px-2 py-0.5 text-[11px] text-ink hover:bg-canvas">{s.direction === 'inbound' ? <ArrowDownToLine size={11} /> : <ArrowUpFromLine size={11} />} Track {s.estimate.number} · {api.SHIP_STAGE_LABEL[s.stage]}{rows.length > 1 && <span data-testid={`${testId}-more`} className="ml-1 rounded-full bg-canvas px-1.5 text-[10px] text-ink-500">+{rows.length - 1}</span>}</button>{open && <TrackingPanel id={open} others={rows} onSelect={setOpen} onClose={() => setOpen(null)} />}</>;
};

// Create-label sheet: prefilled from the client record + estimate, (mock) address validation shown before the label is created
export const CreateLabelSheet = ({ id, onClose, onDone }: { id: string; onClose: () => void; onDone: (m: string) => void }) => {
  const [prep, setPrep] = useState<LabelPrep | null>(null); const [addr, setAddr] = useState<ShipAddress | null>(null); const [value, setValue] = useState(0); const [carrier, setCarrier] = useState<ShipCarrierName>('UPS'); const [err, setErr] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { api.prepareLabel(id).then((p) => { setPrep(p); setAddr(p.validation.cleaned); setValue(p.declaredValue); setCarrier(p.shipment.carrier); }); }, [id]);
  if (!prep || !addr) return null;
  const f = 'h-8 w-full rounded-sm border border-line bg-canvas px-2 text-[13px] focus:border-ink focus:outline-none';
  return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/60 p-6" onClick={onClose}><div data-testid="create-label-sheet" onClick={(e) => e.stopPropagation()} className="w-[520px] rounded-md bg-surface p-5 shadow-pop animate-rise">
    <div className="flex items-start justify-between"><div><h2 className="text-base font-semibold text-ink">Create prepaid label · <span className="font-mono">{prep.shipment.estimate.number}</span></h2><p className="text-xs text-ink-500">{prep.shipment.client.firstName} {prep.shipment.client.lastName} · {prep.shipment.watch ? `${prep.shipment.watch.brand} ${prep.shipment.watch.model}` : ''}</p></div><button onClick={onClose} className="p-1 text-ink-400"><X size={16} /></button></div>
    <div data-testid="label-declared-value" className="mt-3 rounded-md border border-amber-200 bg-amber-50 p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-amber-800">Insured / declared value</div><div className="flex items-center gap-2"><span className="text-xl font-semibold text-ink">$</span><input data-testid="label-value-input" type="number" value={value} onChange={(e) => setValue(Number(e.target.value))} className="h-9 w-40 rounded-sm border border-amber-300 bg-surface px-2 font-mono text-xl font-semibold text-ink" /><span className="text-xs text-ink-500">from estimate {prep.shipment.estimate.number}</span></div></div>
    <div className="mt-3 grid grid-cols-2 gap-2 text-xs"><label className="col-span-2">Recipient<input data-testid="label-name" value={addr.name} onChange={(e) => setAddr({ ...addr, name: e.target.value })} className={f} /></label><label className="col-span-2">Street<input data-testid="label-street" value={addr.street} onChange={(e) => setAddr({ ...addr, street: e.target.value })} className={f} /></label><label>City<input data-testid="label-city" value={addr.city} onChange={(e) => setAddr({ ...addr, city: e.target.value })} className={f} /></label><div className="grid grid-cols-2 gap-2"><label>State<input data-testid="label-state" value={addr.state} onChange={(e) => setAddr({ ...addr, state: e.target.value })} className={f} /></label><label>ZIP<input data-testid="label-zip" value={addr.zip ?? ''} onChange={(e) => setAddr({ ...addr, zip: e.target.value })} className={f} /></label></div></div>
    <div data-testid="label-address-validation" className={`mt-2 flex items-center gap-2 rounded-sm px-2 py-1.5 text-[11px] ${prep.validation.valid ? 'bg-moss-50 text-moss-700' : 'bg-rose-50 text-rose-700'}`}><CheckCircle2 size={12} /> {prep.validation.valid ? `Address verified (Parcel Pro) · cleaned to ${prep.validation.cleaned.street}, ${prep.validation.cleaned.city} ${prep.validation.cleaned.state} ${prep.validation.cleaned.zip}` : `Address problem: ${prep.validation.riskFlag}`}{prep.validation.riskFlag && prep.validation.valid && <span className="text-amber-800">· {prep.validation.riskFlag}</span>}</div>
    <div className="mt-3 flex items-center gap-2 text-xs"><span className="text-ink-500">Carrier</span>{(['UPS', 'FedEx'] as ShipCarrierName[]).map((c) => <button key={c} data-testid={`label-carrier-${c.toLowerCase()}`} onClick={() => setCarrier(c)} className={`rounded-sm border px-2.5 py-1 ${carrier === c ? 'border-ink bg-ink text-white' : 'border-line text-ink'}`}>{c}</button>)}<span className="ml-auto text-ink-400">Label + tracking → Outbox email with portal link</span></div>
    {err && <p data-testid="label-error" className="mt-2 text-xs text-rose-700">{err}</p>}
    <div className="mt-4 flex justify-end gap-2"><Button onClick={onClose}>Cancel</Button><Button variant="primary" data-testid="label-confirm" disabled={busy} onClick={async () => { setBusy(true); try { const s = await api.createInboundLabel(id, addr, value, carrier); onDone(`Label created · ${s.carrier} ${s.trackingNumber} · insured ${fmtMoney(s.declaredValue)} · email queued`); onClose(); } catch (x) { setErr(x instanceof Error ? x.message : 'Failed'); } finally { setBusy(false); } }}>{busy ? 'Calling Parcel Pro…' : 'Confirm & create label'}</Button></div>
  </div></div>;
};
