import clsx from 'clsx';
import { Megaphone, Phone, PhoneOff, Radio } from 'lucide-react';
import { useEffect, useState } from 'react';
import * as ic from '@/api/intercom';
import type { IntercomState, IntercomStation, PageZone } from '@/api/types';
import { useAuth } from '@/auth/AuthContext';

export const useIntercom = () => { const [s, setS] = useState<IntercomState>(ic.getIntercomState()); useEffect(() => ic.subscribeIntercom(() => setS(ic.getIntercomState())), []); return s; };
const KIND_LABEL: Record<IntercomStation['kind'], string> = { station: 'Stations', room: 'Rooms', pad: 'Pads' };

// INTERCOM tab (MH 2026-10-02): Page — zone at the top, then the station / room / pad grid with presence dots (tap = voice call), live-call row, recent log. MOCK · voice only until Daily.co. One component: Inbox → Intercom (desktop) and the pad's Intercom tab (dark).
export const IntercomSection = ({ dark, pad = false }: { dark?: boolean; pad?: boolean }) => {
  const { user, station } = useAuth(); const s = useIntercom(); const [page, setPage] = useState(''); const [zone, setZone] = useState<PageZone>('all'); const [err, setErr] = useState<string | null>(null); const [ok, setOk] = useState<string | null>(null);
  useEffect(() => { if (station) ic.setIntercomMe(station.id); }, [station?.id]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!ok) return; const t = window.setTimeout(() => setOk(null), 2500); return () => window.clearTimeout(t); }, [ok]);
  const act = (f: () => unknown, okMsg?: string) => { try { setErr(null); f(); if (okMsg) setOk(okMsg); } catch (e) { setErr(e instanceof Error ? e.message : 'Failed'); } };
  const muted = dark ? 'text-slate-400' : 'text-ink-400'; const card = dark ? 'border-white/10 bg-white/[0.03]' : 'border-line bg-surface';
  const zoneLabel = ic.PAGE_ZONES.find((z) => z.key === zone)!.label; const log = ic.getPageLog().slice(0, 6);
  return <div data-testid="intercom-section" className="space-y-3">
    <div className={`flex flex-wrap items-center gap-2 text-xs ${muted}`}><Phone size={13} /><span className={`font-semibold ${dark ? 'text-white' : 'text-ink'}`}>Intercom</span><span data-testid="intercom-mock-badge" className={clsx('rounded px-1 text-[10px] font-semibold', dark ? 'bg-amber-400/15 text-amber-200' : 'bg-amber-50 text-amber-800')}>MOCK · voice only</span><span>·</span><span data-testid="intercom-from">From <b className={dark ? 'text-slate-200' : 'text-ink-700'}>{ic.intercomLabel(s.me)}</b></span><span className="ml-auto text-[10px]">Daily.co audio rooms replace this in Keeper · pages are logged under Team → Pages</span></div>
    <form data-testid="intercom-page" className={`rounded-md border p-3 ${card}`} onSubmit={(e) => { e.preventDefault(); act(() => { ic.pageAll(user?.shortName ?? 'Front desk', page, zone); setPage(''); }, `Paged ${zoneLabel}`); }}>
      <div className={`mb-1.5 flex items-center gap-1 text-xs font-semibold ${dark ? 'text-white' : 'text-ink'}`}><Megaphone size={13} className="text-amber-500" /> Page <span className={`font-normal ${muted}`}>— pick the zone, say it once; only stations in the zone see the banner</span></div>
      <div data-testid="intercom-page-zones" className="mb-2 flex flex-wrap gap-1">{ic.PAGE_ZONES.map((z) => <button key={z.key} type="button" data-testid={`intercom-zone-${z.key}`} data-selected={zone === z.key} aria-pressed={zone === z.key} title={z.blurb} onClick={() => setZone(z.key)} className={clsx('rounded-md border px-3 font-semibold', pad ? 'min-h-[48px] text-base' : 'h-7 text-[11px]', zone === z.key ? (dark ? 'border-accent bg-accent/15 text-white' : 'border-ink bg-ink text-white') : dark ? 'border-white/15 text-slate-200' : 'border-line text-ink-600 hover:bg-canvas')}>{z.label}</button>)}</div>
      <div className="flex gap-1.5"><input data-testid="intercom-page-input" value={page} onChange={(e) => setPage(e.target.value)} placeholder={zone === 'all' ? 'Say it once, everywhere…' : `Say it once — ${zoneLabel} only…`} className={clsx('flex-1 rounded-md border px-2', pad ? 'min-h-[48px] text-base' : 'h-8 text-xs', dark ? 'border-white/15 bg-white/5 text-white placeholder:text-slate-500 focus:outline-none' : 'border-line bg-canvas focus:border-ink focus:outline-none')} /><button type="submit" data-testid="intercom-page-send" className={clsx('inline-flex items-center gap-1 rounded-md px-3 font-semibold', pad ? 'min-h-[48px] text-base' : 'h-8 text-xs', dark ? 'bg-accent text-[#161b22]' : 'bg-ink text-white')}><Megaphone size={pad ? 16 : 12} /> Page {zoneLabel}</button></div>
      <div className="mt-1.5 flex flex-wrap gap-1">{ic.PAGE_PRESETS.map((p) => <button key={p} type="button" data-testid="intercom-page-preset" onClick={() => setPage(p)} className={clsx('rounded-full border px-2 py-0.5 text-[10px]', dark ? 'border-white/15 text-slate-300 hover:bg-white/10' : 'border-line text-ink-600 hover:bg-canvas')}>{p}</button>)}</div>
    </form>
    {s.call && <div data-testid="intercom-call" className={clsx('flex items-center gap-2 rounded-md border px-3 py-2 text-xs', dark ? 'border-emerald-400/40 bg-emerald-400/10 text-white' : 'border-emerald-200 bg-emerald-50')}><Radio size={14} className={s.call.state === 'ringing' ? 'animate-pulse text-amber-500' : 'text-emerald-600'} /><span className="flex-1"><b>{ic.intercomLabel(s.call.to)}</b> · <span data-testid="intercom-call-state">{s.call.state === 'ringing' ? 'ringing…' : 'live'}</span></span><button type="button" data-testid="intercom-hangup" onClick={() => act(ic.hangUp)} className="inline-flex items-center gap-1 rounded-md bg-rose-600 px-2.5 py-1 font-semibold text-white"><PhoneOff size={12} /> Hang up</button></div>}
    <div className={`rounded-md border p-3 ${card}`}>
      <div className={`mb-2 flex items-center gap-1 text-xs font-semibold ${dark ? 'text-white' : 'text-ink'}`}><Phone size={13} /> Tap to call <span className={`font-normal ${muted}`}>— one live call at a time · green free · amber busy · grey offline</span></div>
      {(['station', 'room', 'pad'] as IntercomStation['kind'][]).map((k) => { const list = s.stations.filter((st) => st.kind === k && !/kiosk/i.test(st.label)); return list.length ? <div key={k} className="mb-2 last:mb-0"><div className={`mb-1 text-[10px] font-semibold uppercase tracking-wide ${muted}`}>{KIND_LABEL[k]}</div><ul data-testid={`intercom-stations-${k}`} className={clsx('grid gap-1.5', pad ? 'grid-cols-2 sm:grid-cols-3' : 'grid-cols-2 md:grid-cols-3 xl:grid-cols-4')}>{list.map((st) => <li key={st.id}><button type="button" data-testid={`intercom-call-${st.id}`} data-online={st.online} data-busy={st.busy} disabled={!st.online || !!s.call} onClick={() => act(() => ic.ring(st.id))} className={clsx('flex w-full items-center gap-2 rounded-md border px-2.5 text-left disabled:opacity-40', pad ? 'min-h-[48px] text-sm' : 'h-9 text-[11px]', dark ? 'border-white/15 text-slate-200 hover:bg-white/10' : 'border-line hover:bg-canvas')}><span className={clsx('h-2 w-2 shrink-0 rounded-full', !st.online ? (dark ? 'bg-slate-500' : 'bg-ink-300') : st.busy ? 'bg-amber-500' : 'bg-emerald-500')} /><span className="flex-1 truncate">{st.label}</span><span className={`text-[9px] uppercase ${muted}`}>{st.kind}</span></button></li>)}</ul></div> : null; })}
    </div>
    {(ok || err) && <p data-testid={err ? 'intercom-error' : 'intercom-ok'} className={`text-[11px] ${err ? 'text-rose-600' : dark ? 'text-emerald-300' : 'text-moss-700'}`}>{err ?? ok}</p>}
    {(s.history.length > 0 || log.length > 0) && <div data-testid="intercom-history" className={`text-[10px] ${muted}`}>{s.history[0] && <span>Last call: {ic.intercomLabel(s.history[0].to)} · {Math.max(1, Math.round((new Date(s.history[0].endedAt!).getTime() - new Date(s.history[0].startedAt).getTime()) / 1000))}s</span>}{s.history[0] && log[0] && <span> · </span>}{log[0] && <span>Last page: {log[0].by} → {ic.PAGE_ZONES.find((z) => z.key === log[0].zone)?.label}: “{log[0].text}”</span>}</div>}
  </div>;
};
