import clsx from 'clsx';
import { Archive, ArchiveRestore, Check, ChevronDown, ChevronUp, Copy, Mail, MonitorSmartphone, PanelRight, Pin, Send, Share2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import * as api from '@/api/client';
import type { ConvMessage, MessageTemplate, PackagePhoto, RenderedTemplate, TemplateKey, ThreadView } from '@/api/client';
import * as hl from '@/api/hitlist';
import { useAuth } from '@/auth/AuthContext';
import { RatingBadge } from '@/components/clients/RatingBadge';
import { ViewAsClientButton } from '@/components/clients/ViewAsClientButton';
import { AskDraftCard } from '@/components/comms/AskDraftCard';
import { TemplateBar } from '@/components/comms/TemplateBar';
import { TemplateSourceBadge } from '@/components/comms/TemplateEdit';
import { Provisional } from '@/components/estimates/EstimateBits';
import { INBOX_DRAFT_EVENT } from '@/components/inbox/InboxJobCard';
import { TagDots, ThreadContextMenu, useRowMenu } from '@/components/inbox/ThreadContextMenu';
import { PhotoCapture } from '@/components/intake/ReceiveBits';
import { BUBBLE_COMPOSE_EVENT, type BubbleComposeDetail } from '@/components/layout/MessageBubble';
import { field } from '@/components/rs/RsBits';
import { WbpClientRows } from '@/components/shared/WbpDots';
import { TrackButton } from '@/components/shipping/ShippingBits';
import { Button } from '@/components/ui/Button';
import { fmtDate, fmtTime } from '@/lib/format';
import { age, SOURCE_TONE } from './inboxBits';
import type { ActionsFor } from './ThreadList';

export type Run = (f: () => Promise<unknown>, ok?: string) => Promise<void>;

// One collapsible card per thread for this client (threads per request / job / estimate). Collapsed = identity + badges + unreplied count; expanded = full history + composer inside the same card.
export function ThreadStack({ t, run, onFolder, onPick, panelOpen, onPanel, actionsFor }: { t: ThreadView; run: Run; onFolder: () => void; onPick: (id: string) => void; panelOpen: boolean; onPanel: () => void; actionsFor: ActionsFor }) {
  const cards = [...t.folder].sort((a, b) => b.lastAt.localeCompare(a.lastAt)); const [open, setOpen] = useState<Set<string>>(new Set([t.conversation.id])); const [views, setViews] = useState<Record<string, ThreadView>>({});
  useEffect(() => { setOpen(new Set([t.conversation.id])); setViews((v) => ({ ...v, [t.conversation.id]: t })); }, [t]);
  const toggle = async (id: string) => { const n = new Set(open); if (n.has(id)) n.delete(id); else { n.add(id); if (!views[id]) setViews((v) => ({ ...v, [id]: undefined as unknown as ThreadView })); const tv = await api.getThread(id); setViews((v) => ({ ...v, [id]: tv })); } setOpen(n); };
  return <div data-testid="thread-stack" className="space-y-2">{cards.map((c) => { const isOpen = open.has(c.id); const tv = c.id === t.conversation.id ? t : views[c.id]; return <div key={c.id} data-testid={`thread-card-${c.id}`} data-expanded={isOpen} className={`rounded-md border bg-surface ${c.id === t.conversation.id ? 'border-ink' : 'border-line'}`}>
    <button data-testid={`thread-card-toggle-${c.id}`} onClick={() => { void toggle(c.id); if (!isOpen && c.id !== t.conversation.id) onPick(c.id); }} className="flex w-full flex-wrap items-center gap-2 px-3 py-2 text-left text-xs"><span className="text-sm font-semibold text-ink">{c.subject}</span>{c.anchorLabel && <span className="rounded bg-canvas px-1.5 py-0.5 font-mono text-[11px] text-ink-700">{c.anchorLabel}</span>}<span className={`rounded px-1.5 py-0.5 text-[10px] font-semibold ${c.status === 'open' ? 'bg-moss-50 text-moss-700' : c.status === 'snoozed' ? 'bg-amber-50 text-amber-800' : 'bg-canvas text-ink-500'}`}>{c.status === 'closed' ? 'archived' : c.status}</span>{c.needsReply && <span className="rounded bg-rose-50 px-1.5 py-0.5 text-[10px] font-semibold text-rose-700">reply owed · {age(c.ageHours)}</span>}<span className="text-[10px] text-ink-400">last {fmtDate(c.lastAt)} {fmtTime(c.lastAt)}</span>
      <span className="ml-auto" />{isOpen ? <ChevronUp size={14} className="text-ink-400" /> : <ChevronDown size={14} className="text-ink-400" />}</button>
    {isOpen && (tv ? <div className="border-t border-line p-2"><Thread t={tv} run={run} onFolder={onFolder} panelOpen={panelOpen} onPanel={onPanel} actions={actionsFor(tv.conversation)} /></div> : <div className="border-t border-line p-3 text-xs text-ink-400">Loading…</div>)}
  </div>; })}</div>;
}

function Thread({ t, run, onFolder, panelOpen, onPanel, actions }: { t: ThreadView; run: Run; onFolder: () => void; panelOpen: boolean; onPanel: () => void; actions: ReturnType<ActionsFor> }) {
  const c = t.conversation; const { user } = useAuth();
  const [text, setText] = useState(''); const [subject, setSubject] = useState(''); const [tpl, setTpl] = useState<TemplateKey | ''>(''); const [preview, setPreview] = useState<RenderedTemplate | null>(null); const [photos, setPhotos] = useState<PackagePhoto[]>([]); const [note, setNote] = useState(''); const [snooze, setSnooze] = useState(''); const [sim, setSim] = useState(''); const [copied, setCopied] = useState<string | null>(null);
  const { menu, close, rowProps } = useRowMenu();
  useEffect(() => { setText(''); setPreview(null); setTpl(''); setPhotos([]); }, [c.id]);
  // "Generate summary" in the job-card panel drops its draft straight into this reply box
  useEffect(() => { const h = (e: Event) => { const d = (e as CustomEvent<{ threadId: string; text: string }>).detail; if (d.threadId === c.id) { setText(d.text); setSubject((s) => s || `Re: ${c.subject}`); } }; window.addEventListener(INBOX_DRAFT_EVENT, h); return () => window.removeEventListener(INBOX_DRAFT_EVENT, h); }, [c.id, c.subject]);
  const pickTemplate = async (k: TemplateKey | '') => { setTpl(k); if (!k) { setPreview(null); return; } const r = await api.renderTemplate(c.id, k); setPreview(r); setText(r.body); setSubject(r.subject); };
  // Pinned chip / Templates sheet → body + subject rendered for this client, attachments ride along (appended once by id)
  const useTemplate = async (t: MessageTemplate) => { await pickTemplate(t.key); if (t.attachments?.length) setPhotos((ps) => [...ps, ...t.attachments!.filter((a) => !ps.some((p) => p.id === a.id))]); };
  const copy = async (m: ConvMessage) => { const plain = `${m.by} · ${fmtDate(m.at)} ${fmtTime(m.at)}\n${m.text}`; try { await navigator.clipboard.writeText(plain); } catch { /* clipboard blocked */ } setCopied(m.id); window.setTimeout(() => setCopied(null), 1500); };
  // Share with staff → the bubble's one-shot composer opens with the client's message QUOTED + thread link; recipients picked there; logged on the thread after send
  const share = (m: ConvMessage) => window.dispatchEvent(new CustomEvent<BubbleComposeDetail>(BUBBLE_COMPOSE_EVENT, { detail: { share: { conversationId: c.id, messageId: m.id, quote: hl.quoteClientMessage(m, c.id), photo: m.photos?.[0], jobId: c.anchor?.kind === 'job' ? c.anchor.id : undefined, clientName: m.by } } }));
  const signature = `— ${user?.shortName ?? 'Front desk'}, ${api.entityName(c.division)}`;
  const channel = api.replyChannelSync(c.id);
  return <div data-testid="thread-view" className="flex h-full flex-col gap-2">
    <div data-testid="thread-header" className="sticky top-0 z-10 rounded-md border border-line bg-surface p-3 shadow-sm" {...rowProps(c.id)}>
      <div className="flex flex-wrap items-center gap-2 text-xs"><span className="text-sm font-semibold text-ink">{c.pinned && <Pin size={12} data-testid="thread-pinned" className="mr-1 inline text-ink-500" />}{c.subject}</span><TagDots tags={c.tags} testId="thread-tags" size="md" /><RatingBadge clientId={c.clientId} testId="thread-rating" /><WbpClientRows clientId={c.clientId} currentJobId={c.anchor?.kind === 'job' ? c.anchor.id : undefined} testId="thread-wbp" />{c.anchorLabel && <Link data-testid="thread-anchor" to={c.anchorPath ?? '#'} className="rounded bg-canvas px-1.5 py-0.5 font-mono text-[11px] text-brand hover:underline">{c.anchorLabel} →</Link>}{c.linkedEstimate && <Link data-testid="thread-estimate-chip" to={`/estimates/${c.linkedEstimate.id}`} className="rounded bg-moss-50 px-1.5 py-0.5 font-mono text-[11px] text-moss-700 hover:underline">{c.linkedEstimate.number} →</Link>}<span className={`rounded px-1.5 py-0.5 text-[10px] font-semibold ${c.needsReply ? 'bg-rose-50 text-rose-700' : 'bg-canvas text-ink-500'}`} data-testid="thread-status">{c.needsReply ? `reply owed · ${age(c.ageHours)}` : c.status === 'closed' ? 'archived' : c.lane ? c.lane : 'we spoke last'}</span><button data-testid="thread-folder" onClick={onFolder} className="text-[11px] text-brand hover:underline">{c.client.firstName} {c.client.lastName}’s folder ({t.folder.length})</button><Link to={`/clients/${c.clientId}`} className="text-[11px] text-ink-400 hover:underline">Client 360</Link><button type="button" data-testid="thread-job-card" aria-pressed={panelOpen} onClick={onPanel} className={`inline-flex h-6 items-center gap-1 rounded-sm border px-2 text-[11px] font-semibold ${panelOpen ? 'border-ink bg-ink text-white' : 'border-line bg-surface text-ink hover:bg-canvas'}`}><PanelRight size={12} /> Job card</button><TrackButton clientId={c.clientId} estimateId={c.anchor?.kind === 'estimate' ? c.anchor.id : undefined} testId="thread-track" /><ViewAsClientButton clientId={c.clientId} testId="thread-view-as-client" /></div>
      <div className="mt-2 flex flex-wrap items-center gap-2 text-[11px]">
        <span className="inline-flex items-center gap-1 text-ink-500">Tags:{api.CONV_TAGS.map((tg) => { const on = c.tags?.includes(tg.key); return <button key={tg.key} type="button" data-testid={`thread-tag-${tg.key}`} aria-pressed={!!on} title={`${on ? 'Untag' : 'Tag'} ${tg.label}`} onClick={() => actions.tag(tg.key, !on)} className={clsx('inline-flex items-center gap-1 rounded-full border px-1.5 py-0.5', on ? 'border-ink bg-ink text-white' : 'border-line text-ink-600 hover:bg-canvas')}><span className={clsx('inline-block h-2 w-2 rounded-full', tg.dot)} />{tg.label}</button>; })}</span>
        {c.status !== 'snoozed' && c.status !== 'closed' && <><input data-testid="thread-snooze-date" type="date" value={snooze} onChange={(e) => setSnooze(e.target.value)} className={field} /><Button size="sm" data-testid="thread-snooze" onClick={() => run(() => api.snoozeConversation(c.id, snooze ? `${snooze}T09:00:00.000Z` : ''), 'Snoozed')}>Snooze</Button></>}
        {c.status === 'snoozed' && <Button size="sm" data-testid="thread-wake" onClick={() => run(() => api.wakeConversation(c.id), 'Woken')}>Wake now</Button>}
        {c.anchor?.kind === 'request' && (c.linkedEstimate ? <Link to={`/estimates/${c.linkedEstimate.id}`}><Button size="sm" data-testid="thread-open-estimate">Open estimate</Button></Link> : <Link to={`/estimates/new?request=${c.anchor.id}`}><Button size="sm" variant="primary" data-testid="thread-create-estimate">Create estimate</Button></Link>)}
        <span className="ml-auto" />
        {c.status !== 'closed' && <Button size="sm" data-testid="thread-pin" onClick={() => actions.pin(!c.pinned)}><Pin size={12} /> {c.pinned ? 'Unpin' : 'Pin'}</Button>}
        {c.status !== 'closed' ? <Button size="sm" data-testid="thread-close" onClick={actions.archive}><Archive size={12} /> Archive</Button> : <Button size="sm" data-testid="thread-reopen" onClick={actions.unarchive}><ArchiveRestore size={12} /> Un-archive</Button>}
      </div>
    </div>
    {menu && <ThreadContextMenu pos={menu.pos} conv={c} actions={actions} onClose={close} testId="thread-header-menu" />}
    <ol data-testid="thread-messages" className="space-y-2">{t.messages.map((m) => <li key={m.id} data-testid={`msg-${m.id}`} data-msg={m.id} className={`rounded-md border p-2 text-xs ${m.direction === 'internal' ? 'border-yellow-200 bg-yellow-50/60' : m.direction === 'out' ? 'ml-10 border-line bg-canvas/50' : 'mr-10 border-rose-100 bg-rose-50/40'}`}>
      <div className="mb-1 flex flex-wrap items-center gap-1.5 text-[10px] text-ink-500"><span className={`rounded px-1 font-semibold ${SOURCE_TONE[m.source]}`} data-testid={`msg-source-${m.id}`}>{m.direction === 'internal' ? (m.event?.kind === 'shared' ? 'shared with staff · logged' : 'internal note · never sent') : m.source}</span><b className="text-ink-700">{m.by}</b>{m.station && <span>· {m.station}</span>}<span>· {fmtDate(m.at)} {fmtTime(m.at)}</span>{m.token && <span data-testid={`msg-token-${m.id}`} className="rounded bg-ink px-1 font-mono text-white">{m.token}</span>}{m.matchedToken && <span data-testid={`msg-matched-${m.id}`} className="rounded bg-moss-50 px-1 font-mono text-moss-700">↩ matched {m.matchedToken}</span>}{m.event && m.event.kind !== 'shared' && <span data-testid={`msg-event-${m.id}`} className="rounded bg-moss-100 px-1 text-moss-800">{m.event.label}</span>}{m.templateKey && <span className="rounded bg-canvas px-1">template {m.templateKey}</span>}{m.channel && <span data-testid={`msg-channel-${m.id}`} data-channel={m.channel} className={`rounded px-1 ${m.channel === 'portal' ? 'bg-moss-50 text-moss-800' : 'bg-canvas text-ink-600'}`}>via {m.channel}</span>}{m.emailId && <Link to="/intake/sent" className="text-brand hover:underline">Sent</Link>}{m.direction === 'in' && !m.readByStaff && <span className="rounded bg-brand px-1 text-white">new</span>}
        {m.direction === 'in' && <span className="ml-auto inline-flex items-center gap-1"><button type="button" data-testid={`msg-share-${m.id}`} onClick={() => share(m)} title="Share with staff — quoted, with a link only MH · VC · CM can open" className="inline-flex items-center gap-1 rounded-sm border border-line bg-surface px-1.5 py-0.5 font-medium text-ink-700 hover:bg-canvas"><Share2 size={10} /> Share with staff</button><button type="button" data-testid={`msg-copy-${m.id}`} onClick={() => void copy(m)} title="Copy message (plain text)" className="inline-flex items-center gap-1 rounded-sm border border-line bg-surface px-1.5 py-0.5 font-medium text-ink-700 hover:bg-canvas"><Copy size={10} /> {copied === m.id ? 'Copied' : 'Copy message'}</button></span>}</div>
      <div className="whitespace-pre-line text-ink-800">{m.text}</div>
      {m.ask && <AskDraftCard m={m} onDone={(ok) => void run(async () => undefined, ok)} />}
      {m.direction === 'in' && (m.cleared ? <div data-testid={`msg-cleared-${m.id}`} className="mt-1 text-[10px] text-ink-400">Cleared · no reply needed · {m.cleared.by} · {fmtDate(m.cleared.at)} {fmtTime(m.cleared.at)}</div> : m.at > (c.lastOutboundAt ?? '') && <button data-testid={`msg-clear-${m.id}`} onClick={() => run(() => api.clearMessage(c.id, m.id), 'Cleared — no reply sent')} className="mt-1 inline-flex items-center gap-1 rounded-sm border border-line px-1.5 py-0.5 text-[10px] font-medium text-ink-600 hover:bg-canvas"><Check size={10} /> Clear · no reply needed</button>)}
      {m.photos?.length ? <div className="mt-1 flex gap-1">{m.photos.map((p) => <img key={p.id} src={p.dataUrl} alt="" className="h-12 rounded border border-line" />)}</div> : null}
    </li>)}</ol>
    <div data-testid="composer" className="rounded-md border border-line bg-surface p-3">
      <div className="flex items-center gap-2 text-xs"><span className="font-semibold text-ink">Reply</span><span data-testid="composer-channel" data-channel={channel} title="Follows the client's last message: portal thread → portal reply · otherwise email · never SMS" className={`inline-flex items-center gap-1 rounded-sm px-1.5 py-0.5 text-[10px] font-semibold ring-1 ${channel === 'portal' ? 'bg-moss-50 text-moss-800 ring-moss-200' : 'bg-canvas text-ink-600 ring-line'}`}>{channel === 'portal' ? <MonitorSmartphone size={10} /> : <Mail size={10} />} → {channel === 'portal' ? 'portal' : 'email'}</span>{tpl && <span data-testid="composer-template" data-key={tpl} className="rounded-sm bg-canvas px-1.5 py-0.5 font-mono text-[10px] text-ink-600">template {tpl}</span>}{c.linkedEstimate && tpl !== 'estimate_sent' && <button data-testid="composer-quote-template" onClick={() => void pickTemplate('estimate_sent')} className="rounded-sm border border-moss-200 bg-moss-50 px-2 py-0.5 text-[11px] font-medium text-moss-700 hover:bg-moss-100">Reply with the quote · {c.linkedEstimate.number} (estimate_sent + portal link)</button>}<span data-testid="composer-signature" className="ml-auto text-[10px] text-ink-400">signs as <b>{signature}</b></span></div>
      <div className="mt-1.5"><TemplateBar channel={channel} active={tpl} ctx={{ conversationId: c.id }} draft={{ subject, text, photos }} onUse={(t) => void useTemplate(t)} /></div>
      {preview && <div data-testid="composer-preview" className="mt-2 rounded border border-line bg-canvas/60 p-2 text-[11px]"><div className="font-semibold text-ink">Preview · {preview.subject}</div><pre className="mt-1 whitespace-pre-wrap font-sans text-ink-700">{preview.body}</pre>{preview.missing.length > 0 && <div data-testid="composer-missing" className="mt-1 text-amber-800">Unfilled: {preview.missing.join(' ')}</div>}</div>}
      <input data-testid="composer-subject" value={subject} onChange={(e) => setSubject(e.target.value)} placeholder={`Re: ${c.subject}`} className={`${field} mt-2 block w-full`} />
      <textarea data-testid="composer-text" rows={4} value={text} onChange={(e) => setText(e.target.value)} placeholder="Write to the client…" className={`${field} mt-1 block w-full`} />
      <div className="mt-2 flex items-center justify-between gap-2"><div className="flex items-center gap-2">{photos.length > 0 && <span data-testid="composer-photos" data-count={photos.length} className="inline-flex items-center gap-1.5 text-[11px] text-ink-500">{photos.length} attached{photos.map((p, i) => <img key={p.id ?? i} src={p.dataUrl} alt="" title={p.note ?? p.fileName} data-testid={`composer-photo-${i}`} className="h-7 w-8 rounded-sm border border-line object-cover" />)}<button type="button" data-testid="composer-photos-clear" onClick={() => setPhotos([])} className="text-ink-400 hover:text-rose-700">clear</button></span>}<details className="text-[11px]"><summary className="cursor-pointer text-brand">Attach photos</summary><div className="mt-1"><PhotoCapture onAdd={(p) => setPhotos([...photos, ...p])} /></div></details></div>{tpl && preview && <InboxTemplateTools tkey={tpl} preview={preview} text={text} subject={subject} conversationId={c.id} onReload={async (shopDefault) => { const r = await api.renderTemplate(c.id, tpl, shopDefault); setPreview(r); setText(r.body); setSubject(r.subject); }} />}<Button variant="primary" data-testid="composer-send" onClick={() => run(async () => { await api.replyInThread(c.id, { text, subject, templateKey: tpl || undefined, photos }); setText(''); setPhotos([]); setPreview(null); setTpl(''); }, 'Sent · thread updated')}><Send size={12} /> Send</Button></div>
      <div className="mt-3 flex items-center gap-2 border-t border-line pt-2"><input data-testid="note-text" value={note} onChange={(e) => setNote(e.target.value)} placeholder="Internal note — never sent, audited" className={`${field} flex-1 bg-yellow-50/50`} /><Button size="sm" data-testid="note-save" onClick={() => run(async () => { await api.addThreadNote(c.id, note); setNote(''); }, 'Note added')}>Add note</Button></div>
      <div className="mt-2 flex items-center gap-2 text-[11px]"><Provisional note="Mock: emulates a client email reply routed back by the last outbound reply token" /><input data-testid="simulate-text" value={sim} onChange={(e) => setSim(e.target.value)} placeholder="simulate client reply…" className={`${field} flex-1`} /><Button size="sm" data-testid="simulate-inbound" onClick={() => run(async () => { await api.simulateInboundReply(c.id, sim); setSim(''); }, 'Inbound matched by token')}>Simulate inbound</Button></div>
    </div>
  </div>;
}

// Point-of-use template tools in the reply composer: the textarea IS the inline editor ("just this send" = edit and send); save it as my template or flip to the shop default
const InboxTemplateTools = ({ tkey, preview, text, subject, conversationId, onReload }: { tkey: TemplateKey; preview: RenderedTemplate; text: string; subject: string; conversationId: string; onReload: (shopDefault?: boolean) => Promise<void> }) => {
  const [note, setNote] = useState<string | null>(null);
  const edited = text !== preview.body || subject !== preview.subject; const mode = edited ? 'one_off' : preview.source;
  const saveMine = async () => { const vals = await api.mergeValuesForConversation(conversationId); const p = await api.savePersonalTemplate(tkey, api.unrenderTemplate(subject, vals), api.unrenderTemplate(text, vals)); setNote(`Saved as ${p.owner}’s template`); await onReload(); };
  return <span className="flex flex-wrap items-center gap-1.5">
    <TemplateSourceBadge mode={mode} owner={preview.owner} testId="composer-tpl-source" />
    {edited && <button type="button" data-testid="composer-tpl-save-mine" onClick={() => void saveMine()} className="rounded-sm border border-amber-300 bg-amber-50 px-2 py-0.5 text-[11px] font-medium text-amber-900 hover:bg-amber-100">Save as my template</button>}
    {!edited && preview.source === 'personal' && <button type="button" data-testid="composer-tpl-use-shop" onClick={() => void onReload(true)} className="text-[11px] text-ink-500 hover:text-ink">Use shop default</button>}
    {!edited && preview.source === 'shop' && api.personalTemplateFor(tkey) && <button type="button" data-testid="composer-tpl-use-mine" onClick={() => void onReload(false)} className="text-[11px] text-amber-800 hover:underline">Use my template</button>}
    {note && <span data-testid="composer-tpl-note" className="text-[11px] text-emerald-700">{note}</span>}
  </span>;
};
