import { Archive, Check, Lock, MousePointerClick, Search, Trash2, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import * as api from '@/api/client';
import type { BinTarget, BinView, BulkResult, BulkRow, Client, FloorDot, JobWithRefs, LtsNotice, RwStationKey } from '@/api/client';
import { PART_NAME, PartDot, ScanInput } from '@/components/rw/RwBits';
import { roomCode, type MapNode } from '@/components/rw/StationMap';
import RwBulkAssignPage from '@/pages/rw/RwBulkAssignPage';
import { fmtTime, fullName } from '@/lib/format';

const stationLabel = (k?: RwStationKey) => (k ? api.RW_STATIONS.find((s) => s.key === k)?.label ?? k : '—');
const GATE_DEST = new Set<RwStationKey>(['polish_room', 'movement_service', 'refinish', 'band_qc']);

// Bulk assign — destination = a card clicked on the map; scan many; review; Commit once. Gate destinations obey the manager-gate rules per item.
// JV bin nodes: Assign = desk queue (nothing moves) · Vienna's safe / JV's bench = BIN-JV must be in the session, then the tickets enter / rejoin.
const binTargetOf = (node: MapNode | null, target?: RwStationKey): BinTarget | null => (node?.id === 'jv_bin_assign' ? 'assign' : target === 'vc_safe' ? 'vc_safe' : target === 'jv_bench' ? 'jv_bench' : null);
const BinStrip = ({ binTarget, scanned, view }: { binTarget: BinTarget; scanned: boolean; view: BinView | null }) => <div data-testid="bulk-bin-strip" data-bin-scanned={scanned} className={`flex flex-wrap items-center gap-2 rounded-md border px-3 py-1.5 text-xs ${scanned ? 'border-emerald-400/50 bg-emerald-400/10 text-emerald-100' : 'border-amber-400/40 bg-amber-400/10 text-amber-100'}`}>
  <Archive size={13} />
  {binTarget === 'assign' ? <span>Desk queue — tickets scanned here are <b>assigned</b> to JV bin. Nothing moves; each enters the bin by the scan at Vienna's safe.</span>
    : scanned ? <span><b>{api.BIN_CODE} scanned ✓</b> · JV bin {view ? `· ${view.holderLabel} · ${api.binCountLine(view)}` : ''} · Commit {binTarget === 'vc_safe' ? (view?.holder === 'person:JV' ? 'moves the bin + everything inside into the safe, then enters the scanned tickets' : 'enters the scanned tickets into the bin') : (view?.holder === 'safe:VC' ? "takes the bin out — every ticket inside lands at JV's bench, custody JV workshop" : 'puts the scanned tickets back in the bin')}</span>
    : <span>Scan <b>{api.BIN_CODE}</b> first — {binTarget === 'vc_safe' ? 'tickets enter the bin only with the bin at the safe' : "tickets rejoin only with the bin at JV's bench"}.{view ? ` JV bin now: ${view.holderLabel} · ${api.binCountLine(view)}` : ''}</span>}
</div>;
// Long-term storage strip (MH 2026-10-02): destination-first — the LTS safe is armed, every scanned ticket (or BIN-JV = everything inside) goes to storage on Commit; status In storage, client notice queued
const LtsStrip = () => <div data-testid="bulk-lts-strip" className="flex flex-wrap items-center gap-2 rounded-md border border-indigo-400/50 bg-indigo-400/10 px-3 py-1.5 text-xs text-indigo-100"><Archive size={13} /><span><b>Long-term storage</b> · scan the ticket — or <b>{api.BIN_CODE}</b> to take every ticket riding in the bin · Commit moves all components into the LTS safe (custody VC), sets <b>In storage</b> and queues the client notice. Any later scan out returns the job to active.</span></div>;
const LtsNotices = ({ notices }: { notices: LtsNotice[] }) => <ul data-testid="bulk-lts-notices" className="space-y-2">{notices.map((n) => <li key={n.emailId} data-testid={`lts-notice-${n.jobId}`} className="rounded-md border border-indigo-400/40 bg-[#0f131a] p-3 text-xs">
  <div className="flex flex-wrap items-center gap-2 text-[10px] uppercase tracking-wide text-indigo-200"><Archive size={11} /> Client notice queued · Sent record <span className="font-mono normal-case text-slate-400">{n.emailId}</span><span className="ml-auto normal-case text-slate-400">to {n.clientName} · {n.to}</span></div>
  <div className="mt-1 font-semibold text-slate-100" data-testid={`lts-notice-subject-${n.jobId}`}>{n.subject}</div>
  <pre className="mt-1 whitespace-pre-wrap font-sans text-[11px] leading-relaxed text-slate-300" data-testid={`lts-notice-body-${n.jobId}`}>{n.body}</pre>
</li>)}</ul>;
export const BulkPanel = ({ node, target, onClear, onCommitted, showHandout = true }: { node: MapNode | null; target?: RwStationKey; onClear: () => void; onCommitted: (m: string) => void; showHandout?: boolean }) => {
  const [rows, setRows] = useState<BulkRow[]>([]); const [results, setResults] = useState<BulkResult[] | null>(null); const [handTo, setHandTo] = useState(''); const [busy, setBusy] = useState(false); const [mode, setMode] = useState<'map' | 'handout'>('map');
  const [binScanned, setBinScanned] = useState(false); const [binView, setBinView] = useState<BinView | null>(null); const [binNote, setBinNote] = useState<string | null>(null); const [notices, setNotices] = useState<LtsNotice[]>([]);
  const binTarget = binTargetOf(node, target); const lts = target === api.LTS_KEY;
  useEffect(() => { setRows([]); setResults(null); setBinScanned(false); setBinNote(null); setNotices([]); if (binTarget) void api.getBin().then(setBinView); }, [node?.id]); // eslint-disable-line react-hooks/exhaustive-deps
  if (mode === 'handout') return <div data-testid="bulk-handout" className="space-y-2"><div className="flex items-center justify-between text-xs"><span className="text-slate-400">Narrow mode: Morning handout — distribute heads to several watchmakers by scanning TECH-codes (auto-commits per label).</span><button data-testid="bulk-mode-map" onClick={() => setMode('map')} className="rounded-full border border-white/15 px-3 py-1 text-slate-200 hover:bg-white/10">← Back to Bulk assign</button></div><div className="rounded-md border border-white/10 p-2"><RwBulkAssignPage /></div></div>;
  const gate = target && GATE_DEST.has(target); const needsHand = gate && (target === 'polish_room' || target === 'refinish');
  const scan = async (label: string) => {
    if (lts) { const r = await api.resolveLtsLabel(label); setRows((v) => [...r.filter((x) => !v.some((y) => y.jobId === x.jobId)), ...v]); setResults(null); return; }
    if (binTarget) { if (api.isBinCode(label)) { if (binTarget === 'assign') throw new Error(`${api.BIN_CODE} doesn't scan here — assigning is a queue; the bin itself scans at Vienna's safe or JV's bench`); setBinScanned(true); setResults(null); return; } const r = await api.resolveBinLabel(label); setRows((v) => [r, ...v]); setResults(null); return; }
    if (api.isBinCode(label)) throw new Error(`${api.BIN_CODE} scans only at Vienna's safe or JV's bench`);
    const r = await api.resolveBulkLabel(label, target!); setRows((v) => [r, ...v]); setResults(null);
  };
  const commit = async () => { setBusy(true); try {
    if (lts) { const r = await api.ltsCommit([...rows].reverse()); setResults(r.results); setNotices(r.notices); setRows(r.results.filter((x) => !x.ok).map((x) => x.row)); onCommitted(`${r.results.filter((x) => x.ok).length}/${r.results.length} job${r.results.length === 1 ? '' : 's'} → long-term storage · ${r.notices.length} client notice${r.notices.length === 1 ? '' : 's'} queued`); return; }
    if (binTarget) { const r = await api.binCommit([...rows].reverse(), binTarget, binScanned); setResults(r.results); setRows(r.results.filter((x) => !x.ok).map((x) => x.row)); setBinView(r.view); setBinNote(r.binNote ?? null); setBinScanned(false); onCommitted(`${r.binNote ? `${r.binNote} · ` : ''}${r.results.filter((x) => x.ok).length}/${r.results.length} ticket${r.results.length === 1 ? '' : 's'} ${binTarget === 'assign' ? 'assigned' : binTarget === 'vc_safe' ? 'entered' : 'back in'}`); return; }
    const res = await api.bulkCommit([...rows].reverse(), target!, handTo || undefined); setResults(res); setRows(res.filter((x) => !x.ok).map((x) => x.row)); onCommitted(`${res.filter((x) => x.ok).length}/${res.length} moved → ${stationLabel(target)}`); } finally { setBusy(false); } };
  const canCommit = binTarget ? (rows.length > 0 || (binScanned && binTarget !== 'assign')) : rows.length > 0;
  return <div data-testid="bulk-panel" data-bin-target={binTarget ?? undefined} className="space-y-2">
    <div className="flex flex-wrap items-center justify-between gap-2 text-xs">
      {node ? <div data-testid="bulk-destination" className="inline-flex items-center gap-2 rounded-md border border-accent/60 bg-accent/10 px-3 py-1.5 text-amber-100"><MousePointerClick size={13} /> Assigning to <b>{node.label}</b>{node.owner && <span className="text-amber-200/70">· {node.owner}'s safe</span>}{node.keys.length > 1 && <span className="font-mono text-amber-200/70">→ {stationLabel(target)}</span>}{gate && <span className="rounded bg-amber-400/20 px-1.5 text-[10px] font-semibold uppercase">manager gate rules</span>}{binTarget && <span className="rounded bg-amber-400/20 px-1.5 text-[10px] font-semibold uppercase">{binTarget === 'assign' ? 'queue · no custody move' : 'JV bin · container scan'}</span>}{lts && <span data-testid="bulk-lts-tag" className="rounded bg-indigo-400/25 px-1.5 text-[10px] font-semibold uppercase text-indigo-100">long-term storage · scan only</span>}<button data-testid="bulk-clear" onClick={onClear} className="ml-1 text-amber-200/70 hover:text-white"><X size={12} /></button></div>
        : <div data-testid="bulk-pick-hint" className="inline-flex items-center gap-2 rounded-md border border-white/15 px-3 py-1.5 text-slate-300"><MousePointerClick size={13} className="text-amber-300" /> Click a station or safe card on the map to choose the destination, then scan labels.</div>}
      {showHandout && <button data-testid="bulk-mode-handout" onClick={() => setMode('handout')} className="text-slate-400 underline-offset-2 hover:text-white hover:underline">Morning handout (TECH-code mode) →</button>}
    </div>
    {node && <>
      {binTarget && <BinStrip binTarget={binTarget} scanned={binScanned} view={binView} />}
      {lts && <LtsStrip />}
      <div className="grid gap-3 md:grid-cols-[1fr_260px]">
        <div className="space-y-2">
          <ScanInput testId="bulk-scan" placeholder={lts ? `Scan tickets for long-term storage · E02098 · or ${api.BIN_CODE}` : binTarget === 'assign' ? 'Scan tickets to assign · E02034' : binTarget ? `Scan ${api.BIN_CODE}, then tickets · E02034` : `Scan labels for ${node.label} · E02016 · BAND-E02031`} onScan={scan} big />
          {!binTarget && !lts && <div className="flex items-center gap-2 text-xs"><span className="text-slate-400">{needsHand ? 'Hand to (required for gate IN)' : 'Hand custody to (optional)'}</span><select data-testid="bulk-handto" value={handTo} onChange={(e) => setHandTo(e.target.value)} className="rounded-md border border-white/10 bg-[#0f131a] px-2 py-1 text-slate-100"><option value="">{needsHand ? '— pick —' : 'keep / by rule'}</option>{[...new Set([...api.POLISHERS, 'MM', 'Leo', 'JV', 'Walter', 'MH'])].map((p) => <option key={p}>{p}</option>)}</select></div>}
        </div>
        <div className="rounded-md border border-white/10 bg-[#0f131a] p-3 text-xs"><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Session</div><div data-testid="bulk-count" className="text-2xl font-semibold text-white">{rows.length}</div><div className="text-slate-400">{binTarget === 'assign' ? 'tickets · queued on Commit, no custody move' : 'scanned · nothing moves until Commit'}</div>
          <button data-testid="bulk-commit" disabled={!canCommit || busy || (needsHand && !handTo)} onClick={() => void commit()} className="mt-2 inline-flex w-full items-center justify-center gap-1 rounded-md bg-amber-400 py-2 text-sm font-semibold text-[#161b22] disabled:opacity-40"><Check size={14} /> Commit {rows.length ? `${rows.length} item${rows.length === 1 ? '' : 's'}` : binScanned ? 'bin move' : ''}</button></div>
      </div>
      <table className="w-full text-xs"><thead><tr className="text-left text-[10px] uppercase tracking-wide text-slate-500"><th className="py-1">Time</th><th>Job</th><th>Client</th><th>Watch</th><th>Part</th><th /></tr></thead>
        <tbody data-testid="bulk-rows">{rows.map((r) => <tr key={r.id} data-testid={`bulk-row-${r.id}`} className="border-t border-white/5"><td className="py-1.5 text-slate-400">{fmtTime(r.at)}</td><td className="font-mono font-semibold text-amber-300">{r.jobNumber}</td><td className="text-slate-300">{r.clientName}</td><td className="text-slate-300">{r.watchLabel}</td><td className="inline-flex items-center gap-1 py-1.5 text-slate-200"><PartDot k={r.key} size={10} /> {PART_NAME[r.key]}</td><td className="text-right"><button data-testid={`bulk-remove-${r.id}`} onClick={() => setRows((v) => v.filter((x) => x.id !== r.id))} title="Remove mis-scan" className="rounded p-1 text-slate-500 hover:bg-white/10 hover:text-rose-300"><Trash2 size={12} /></button></td></tr>)}{!rows.length && !results && <tr><td colSpan={6} className="py-4 text-center text-slate-500">Nothing scanned yet.</td></tr>}</tbody></table>
      {binNote && <div data-testid="bulk-bin-note" className="rounded-md border border-white/10 bg-[#0f131a] px-3 py-1.5 text-xs text-amber-100"><Archive size={12} className="mr-1 inline" />{binNote}</div>}
      {results && <ul data-testid="bulk-results" className="divide-y divide-white/5 rounded-md border border-white/10 bg-[#0f131a] text-xs">{results.map((x) => <li key={x.row.id} data-testid={`bulk-result-${x.row.id}`} data-ok={x.ok} className="flex items-center gap-2 px-3 py-1.5"><span className={`rounded px-1.5 text-[10px] font-semibold uppercase ${x.ok ? 'bg-emerald-900/60 text-emerald-200' : 'bg-rose-900/60 text-rose-200'}`}>{x.ok ? (binTarget === 'assign' ? 'queued' : lts ? 'stored' : 'moved') : 'blocked'}</span><span className="font-mono text-amber-300">{x.row.jobNumber}</span><span className="text-slate-300">{PART_NAME[x.row.key]}</span><span className="text-slate-400">{x.detail}</span></li>)}</ul>}
      {notices.length > 0 && <LtsNotices notices={notices} />}
    </>}
  </div>;
};

// Component lookup — one bar: est# / ref# / barcode / client name (type-ahead). A client → every component, badge-coded by room + custodian, est# per job, item label (1/3…) from Receive Watch.
export const LookupPanel = ({ dots, onOpen, onFocus }: { dots: FloorDot[]; onOpen: (d: FloorDot) => void; onFocus: (ids: Set<string> | undefined) => void }) => {
  const [q, setQ] = useState(''); const [sugg, setSugg] = useState<Client[]>([]); const [client, setClient] = useState<Client | null>(null); const [job, setJob] = useState<JobWithRefs | null>(null); const [err, setErr] = useState<string | null>(null);
  useEffect(() => { const s = q.trim(); if (s.length < 2 || /^\d|^E\d|^BAND-/i.test(s) || (client && s === fullName(client))) { setSugg([]); return; } const t = setTimeout(() => api.searchClients(s).then((c) => setSugg(c.slice(0, 8))), 150); return () => clearTimeout(t); }, [q, client]);
  const pick = (c: Client) => { setClient(c); setJob(null); setSugg([]); setQ(fullName(c)); setErr(null); onFocus(new Set(dots.filter((d) => d.clientId === c.id).map((d) => d.jobId))); };
  const go = async (e: React.FormEvent) => { e.preventDefault(); const s = q.trim(); if (!s) return; if (sugg.length === 1) return pick(sugg[0]);
    const j = await api.findJobByLabel(s.replace(/^BAND-/i, '')) ?? (await api.searchJobs(s)).find((x) => x.watch.reference.toUpperCase() === s.toUpperCase() || x.estimate?.number.toUpperCase() === s.toUpperCase());
    if (j) { setJob(j); setClient(null); setErr(null); onFocus(new Set([j.id])); return; } const cs = await api.searchClients(s); if (cs.length) return pick(cs[0]); setErr(`Nothing matches “${s}”`); onFocus(undefined); };
  const clear = () => { setQ(''); setClient(null); setJob(null); setSugg([]); setErr(null); onFocus(undefined); };
  const mine = client ? dots.filter((d) => d.clientId === client.id) : job ? dots.filter((d) => d.jobId === job.id) : []; const jobs = [...new Set(mine.map((d) => d.jobId))];
  return <div data-testid="lookup-panel" className="space-y-2">
    <form onSubmit={go} className="relative flex gap-2"><div className="relative flex-1"><Search size={14} className="pointer-events-none absolute left-2.5 top-2.5 text-slate-500" /><input data-testid="lookup-input" value={q} onChange={(e) => { setQ(e.target.value); if (client) { setClient(null); onFocus(undefined); } }} placeholder="Estimate # · ref # · scan a barcode · client name" autoComplete="off" className="w-full rounded-md border border-white/10 bg-[#0f131a] py-2 pl-8 pr-3 text-sm text-slate-100" />
      {sugg.length > 0 && <ul data-testid="lookup-suggestions" className="absolute left-0 right-0 top-full z-30 mt-1 overflow-hidden rounded-md border border-white/10 bg-[#0f131a] shadow-2xl">{sugg.map((c) => <li key={c.id}><button type="button" data-testid={`lookup-suggest-${c.id}`} onClick={() => pick(c)} className="flex w-full items-center gap-2 px-3 py-1.5 text-left text-sm text-slate-100 hover:bg-white/10"><span className="font-medium">{fullName(c)}</span><span className="text-xs text-slate-500">{c.company ?? c.email}</span><span className="ml-auto text-[10px] text-slate-500">{dots.filter((d) => d.clientId === c.id).length} part{dots.filter((d) => d.clientId === c.id).length === 1 ? '' : 's'} on floor</span></button></li>)}</ul>}</div>
      <button data-testid="lookup-go" className="rounded-md bg-amber-400 px-4 text-sm font-semibold text-[#161b22]">Look up</button>{(client || job) && <button type="button" data-testid="lookup-clear" onClick={clear} className="rounded-md border border-white/15 px-3 text-sm text-slate-200">Clear</button>}</form>
    {err && <div data-testid="lookup-error" className="text-xs text-rose-300">{err}</div>}
    {(client || job) && <div data-testid="lookup-result" className="rounded-md border border-white/10 bg-[#0f131a] p-3 text-xs">
      <div className="flex flex-wrap items-center gap-2"><span className="text-base font-semibold text-white">{client ? fullName(client) : job ? `${job.client.firstName} ${job.client.lastName}` : ''}</span>{job && <><Link to={`/rw/jobs/${job.id}`} className="font-mono text-amber-300 hover:underline">{job.number}</Link><span className="text-slate-300">{job.watch.brand} {job.watch.model}</span><span className="rounded bg-white/10 px-1.5 text-[10px] uppercase text-slate-300">{job.workflow.join('')}</span><span className="text-slate-500">{api.isSplitFlow(job) ? 'split · bracelet on its own track' : 'not split · bracelet rides the case off-ramp'}</span></>}<span className="ml-auto text-slate-500">{jobs.length} job{jobs.length === 1 ? '' : 's'} · {mine.length} component{mine.length === 1 ? '' : 's'} on the floor · highlighted on the map</span></div>
      <ul className="mt-2 divide-y divide-white/5">{mine.map((d) => <li key={`${d.jobId}-${d.key}`} data-testid={`lookup-part-${d.jobId}-${d.key}`} className="flex flex-wrap items-center gap-2 py-1.5">
        <span data-testid={`lookup-badge-${d.jobId}-${d.key}`} className="rounded bg-amber-400/20 px-1.5 py-0.5 font-mono text-[11px] font-semibold text-amber-200">{roomCode(d)}</span>
        {jobs.length > 1 && <span className="font-mono text-slate-300">{d.estimateNumber ?? d.jobNumber}</span>}{d.itemLabel && <span data-testid={`lookup-item-${d.jobId}-${d.key}`} className="rounded bg-white/10 px-1.5 font-mono text-[11px] text-white">{d.itemLabel}</span>}
        <PartDot k={d.key} size={10} /><span className="w-20 text-slate-200">{PART_NAME[d.key]}</span><span className="text-slate-400">{d.watchLabel}</span><span className="flex-1 text-slate-300">{api.isSafeStation(d.station) && <Lock size={10} className="mr-1 inline text-amber-300" />}{stationLabel(d.station)}</span><span className="text-slate-500">{d.partStatus}</span><button data-testid={`lookup-history-${d.jobId}-${d.key}`} onClick={() => onOpen(d)} className="rounded-full border border-white/15 px-2 py-0.5 text-[10px] hover:bg-white/10">history</button></li>)}{!mine.length && <li className="py-2 text-slate-500">No components on the floor.</li>}</ul>
    </div>}
  </div>;
};
