import clsx from 'clsx';
import { Plus, X } from 'lucide-react';
import { useState } from 'react';
import * as bz from '@/api/bonus';
import type { BasisKind, BonusBasis, BonusPlan, BonusPlanInput } from '@/api/bonus';
import type { User } from '@/api/client';
import { field } from '@/components/rs/RsBits';
import { Button } from '@/components/ui/Button';

// Setup → Bonus plans — add / edit form. Target is entered in dollars for revenue bases (stored cents) and as a whole number for counts.
type Draft = { id?: string; userId: string; basis: BonusBasis; customName: string; customKind: BasisKind; periodMonths: 1 | 2 | 3; anchorMonth: string; target: string; flatPayout: string; tiers: { pct: string; payout: string }[]; showToStaff: boolean; showPayout: boolean; active: boolean; note: string };
export const blankDraft = (userId: string): Draft => ({ userId, basis: 'band_room_total', customName: '', customKind: 'revenue', periodMonths: 1, anchorMonth: '2026-10', target: '', flatPayout: '', tiers: [], showToStaff: true, showPayout: true, active: true, note: '' });
export const draftFromPlan = (p: BonusPlan): Draft => { const kind = bz.planKind(p); return { id: p.id, userId: p.userId, basis: p.basis, customName: p.customView?.name ?? '', customKind: p.customView?.kind ?? 'revenue', periodMonths: p.periodMonths, anchorMonth: p.anchorMonth, target: kind === 'revenue' ? String(p.target / 100) : String(p.target), flatPayout: String(p.flatPayout), tiers: p.tiers.map((t) => ({ pct: String(t.pct), payout: String(t.payout) })), showToStaff: p.showToStaff, showPayout: p.showPayout, active: p.active, note: p.note ?? '' }; };
const kindOf = (d: Draft): BasisKind => (d.basis === 'custom_view' ? d.customKind : bz.BASIS_META[d.basis].kind);
export const toInput = (d: Draft): BonusPlanInput => { const kind = kindOf(d); return { id: d.id, userId: d.userId, basis: d.basis, customView: d.basis === 'custom_view' ? { name: d.customName.trim(), kind: d.customKind } : undefined, periodMonths: d.periodMonths, anchorMonth: d.anchorMonth, target: kind === 'revenue' ? Math.round(Number(d.target) * 100) : Math.round(Number(d.target)), flatPayout: Number(d.flatPayout) || 0, tiers: d.tiers.map((t) => ({ pct: Number(t.pct), payout: Number(t.payout) || 0 })), showToStaff: d.showToStaff, showPayout: d.showPayout, active: d.active, note: d.note.trim() || undefined }; };

const Toggle = ({ on, onChange, testId, children }: { on: boolean; onChange: (v: boolean) => void; testId: string; children: string }) => <label className="inline-flex items-center gap-1.5 text-[11px] text-ink-700"><input type="checkbox" data-testid={testId} checked={on} onChange={(e) => onChange(e.target.checked)} /> {children}</label>;

export const BonusPlanForm = ({ initial, users, onSaved, onCancel }: { initial: Draft; users: User[]; onSaved: (p: BonusPlan) => void; onCancel: () => void }) => {
  const [d, setD] = useState<Draft>(initial); const [err, setErr] = useState<string | null>(null);
  const kind = kindOf(d); const meta = bz.BASIS_META[d.basis]; const sel = `${field} w-full`;
  const save = async () => { try { setErr(null); onSaved(await bz.saveBonusPlan(toInput(d))); } catch (e) { setErr(e instanceof Error ? e.message : 'Could not save'); } };
  return <form data-testid="bonus-plan-form" data-editing={d.id || undefined} onSubmit={(e) => { e.preventDefault(); void save(); }} className="space-y-3 rounded-md border border-ink bg-surface p-3 text-xs">
    <div className="flex items-center gap-2"><span className="text-[10px] font-semibold uppercase tracking-wide text-ink-500">{d.id ? 'Edit plan' : 'New plan'}</span><button type="button" data-testid="bonus-plan-cancel" onClick={onCancel} aria-label="Cancel" className="ml-auto text-ink-400 hover:text-ink"><X size={13} /></button></div>
    <div className="grid gap-3 md:grid-cols-[180px_1fr_1fr]">
      <label className="block"><span className="text-[10px] text-ink-500">Staff</span><select data-testid="bonus-plan-user" value={d.userId} onChange={(e) => setD({ ...d, userId: e.target.value })} className={`${sel} mt-0.5`}>{users.map((u) => <option key={u.id} value={u.id}>{u.shortName} · {u.dutyLabel}</option>)}</select></label>
      <label className="block"><span className="text-[10px] text-ink-500">Basis (the report it reads)</span><select data-testid="bonus-plan-basis" value={d.basis} onChange={(e) => setD({ ...d, basis: e.target.value as BonusBasis })} className={`${sel} mt-0.5`}>{bz.BASES.map((k) => <option key={k} value={k}>{bz.BASIS_META[k].label}</option>)}</select><span className="mt-0.5 block text-[10px] text-ink-400">{meta.note} · <span className="font-mono">{d.basis === 'custom_view' ? d.customName || meta.view : meta.view}</span> · by {meta.dated} date</span></label>
      {d.basis === 'custom_view' ? <div className="grid grid-cols-[1fr_auto] gap-2"><label className="block"><span className="text-[10px] text-ink-500">View name</span><input data-testid="bonus-plan-custom-name" value={d.customName} onChange={(e) => setD({ ...d, customName: e.target.value })} placeholder="v_bonus_…" className={`${sel} mt-0.5 font-mono`} /></label><label className="block"><span className="text-[10px] text-ink-500">Returns</span><select data-testid="bonus-plan-custom-kind" value={d.customKind} onChange={(e) => setD({ ...d, customKind: e.target.value as BasisKind })} className={`${sel} mt-0.5`}><option value="revenue">Revenue $</option><option value="count">Count</option></select></label></div>
        : <div><span className="text-[10px] text-ink-500">Period</span><div className="mt-0.5 flex items-center gap-1">{([1, 2, 3] as const).map((n) => <button key={n} type="button" data-testid={`bonus-plan-period-${n}`} aria-pressed={d.periodMonths === n} onClick={() => setD({ ...d, periodMonths: n })} className={clsx('h-7 rounded-sm border px-2 font-medium', d.periodMonths === n ? 'border-ink bg-ink text-white' : 'border-line text-ink-600 hover:bg-canvas')}>{bz.periodMonthsLabel(n)}</button>)}</div></div>}
    </div>
    <div className="grid gap-3 md:grid-cols-4">
      {d.basis === 'custom_view' && <div><span className="text-[10px] text-ink-500">Period</span><div className="mt-0.5 flex items-center gap-1">{([1, 2, 3] as const).map((n) => <button key={n} type="button" data-testid={`bonus-plan-period-${n}`} aria-pressed={d.periodMonths === n} onClick={() => setD({ ...d, periodMonths: n })} className={clsx('h-7 rounded-sm border px-2 font-medium', d.periodMonths === n ? 'border-ink bg-ink text-white' : 'border-line text-ink-600 hover:bg-canvas')}>{bz.periodMonthsLabel(n)}</button>)}</div></div>}
      <label className="block"><span className="text-[10px] text-ink-500">Effective from (first period starts)</span><input data-testid="bonus-plan-anchor" type="month" value={d.anchorMonth} onChange={(e) => setD({ ...d, anchorMonth: e.target.value })} className={`${sel} mt-0.5 font-mono`} /></label>
      <label className="block"><span className="text-[10px] text-ink-500">Target per period {kind === 'revenue' ? '($)' : '(count)'}</span><input data-testid="bonus-plan-target" type="number" min={0} step={kind === 'revenue' ? 100 : 1} value={d.target} onChange={(e) => setD({ ...d, target: e.target.value })} className={`${sel} mt-0.5 font-mono`} /></label>
      <label className={clsx('block', d.tiers.length && 'opacity-50')}><span className="text-[10px] text-ink-500">Flat payout ($) when reached</span><input data-testid="bonus-plan-flat" type="number" min={0} step={50} value={d.flatPayout} disabled={!!d.tiers.length} onChange={(e) => setD({ ...d, flatPayout: e.target.value })} className={`${sel} mt-0.5 font-mono`} /></label>
    </div>
    <div data-testid="bonus-plan-tiers" className="rounded-md bg-canvas p-2">
      <div className="flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-wide text-ink-500">Tiers (optional · replace the flat payout)</span><button type="button" data-testid="bonus-plan-tier-add" onClick={() => setD({ ...d, tiers: [...d.tiers, { pct: d.tiers.length ? '' : '100', payout: '' }] })} className="inline-flex items-center gap-1 text-[11px] font-medium text-brand hover:underline"><Plus size={11} /> Add tier</button></div>
      {d.tiers.map((t, i) => <div key={i} data-testid={`bonus-plan-tier-${i}`} className="mt-1.5 flex items-center gap-2"><input data-testid={`bonus-plan-tier-pct-${i}`} type="number" min={1} value={t.pct} onChange={(e) => setD({ ...d, tiers: d.tiers.map((x, j) => (j === i ? { ...x, pct: e.target.value } : x)) })} className={`${field} w-20 font-mono`} /><span className="text-ink-500">% of target →</span><input data-testid={`bonus-plan-tier-payout-${i}`} type="number" min={0} step={50} value={t.payout} onChange={(e) => setD({ ...d, tiers: d.tiers.map((x, j) => (j === i ? { ...x, payout: e.target.value } : x)) })} className={`${field} w-24 font-mono`} /><span className="text-ink-500">$</span><button type="button" data-testid={`bonus-plan-tier-remove-${i}`} onClick={() => setD({ ...d, tiers: d.tiers.filter((_, j) => j !== i) })} aria-label="Remove tier" className="text-ink-400 hover:text-rose-700"><X size={12} /></button></div>)}
      {!d.tiers.length && <p className="mt-1 text-[10px] text-ink-400">No tiers — the flat payout applies at 100 %.</p>}
    </div>
    <div className="flex flex-wrap items-center gap-4">
      <Toggle on={d.showToStaff} onChange={(v) => setD({ ...d, showToStaff: v })} testId="bonus-plan-show-staff">Show to staff (progress card on their Hitlist)</Toggle>
      <Toggle on={d.showPayout} onChange={(v) => setD({ ...d, showPayout: v })} testId="bonus-plan-show-payout">Show payout $ on the card</Toggle>
      <Toggle on={d.active} onChange={(v) => setD({ ...d, active: v })} testId="bonus-plan-active">Active</Toggle>
    </div>
    <label className="block"><span className="text-[10px] text-ink-500">Note (internal)</span><input data-testid="bonus-plan-note" value={d.note} onChange={(e) => setD({ ...d, note: e.target.value })} className={`${sel} mt-0.5`} /></label>
    <div className="flex items-center gap-3"><Button type="submit" variant="primary" size="sm" data-testid="bonus-plan-save">{d.id ? 'Save plan' : 'Add plan'}</Button>{err && <span data-testid="bonus-plan-error" className="text-rose-700">{err}</span>}</div>
  </form>;
};
