import { ArrowLeft, ArrowRight, Camera, Truck, ChevronRight, ClipboardList, LayoutGrid, List, UserRound, MessageSquare, Mail } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import * as api from '@/api/client';
import { MessagesPanel } from '@/components/jobs/JobMessages';
import { AtRiskTag, ComponentWaitChips } from '@/components/jobs/ComponentWaitChips';
import type { JobEmailRow, JobPhotoView, PadCard, PadConditionView, SendBackReason } from '@/api/client';
import { ClientRequestBadge, ClientRequestList, QcRequestChecklist } from '@/components/jobs/ClientRequests';
import { PartDot, PartLocations } from '@/components/rw/RwBits';
import { Big, Chip, Sheet } from './PadBits';
import { CameraCapture } from './PadCamera';
import { fmtDate, fmtTime } from '@/lib/format';
import { SwoForm } from '@/pages/rs/SwoPage';

type Say = (m: string, tone?: 'ok' | 'learn' | 'err') => void;
const GRADE_TONE: Record<string, string> = { good: 'bg-emerald-700 text-emerald-50', fair: 'bg-amber-500 text-[#161b22]', worn: 'bg-orange-600 text-white', replace: 'bg-rose-600 text-white' };

// Send back requires a reason — logged who / when / why
const SendBackSheet = ({ card, onClose, onDone }: { card: PadCard; onClose: () => void; onDone: Say }) => {
  const [reason, setReason] = useState<SendBackReason | null>(null); const [note, setNote] = useState(''); const [err, setErr] = useState<string | null>(null);
  return <Sheet testId="pad-sendback-modal" title={`Send ${card.job.number} back`} sub={<>From <b className="text-white">{card.stageLabel}</b> to the previous stage — pick a reason.</>} onClose={onClose}>
    <div className="grid grid-cols-2 gap-2">{(Object.entries(api.SEND_BACK_REASONS) as [SendBackReason, string][]).map(([k, l]) => <button key={k} data-testid={`pad-reason-${k}`} onClick={() => setReason(k)} className={`min-h-[60px] rounded-2xl border text-lg font-medium ${reason === k ? 'border-accent bg-accent/15 text-white' : 'border-white/15 text-slate-200'}`}>{l}</button>)}</div>
    <textarea data-testid="pad-reason-note" value={note} onChange={(e) => setNote(e.target.value)} rows={2} placeholder={reason === 'other' ? 'Note (required for Other)' : 'Note (optional)'} className="mt-3 w-full rounded-2xl border border-white/15 bg-[#0f131a] px-4 py-3 text-lg" />
    {err && <p data-testid="pad-sendback-error" className="mt-2 text-sm text-rose-400">{err}</p>}
    <div className="mt-4"><Big full testId="pad-sendback-confirm" tone="danger" disabled={!reason} onClick={async () => { try { await api.padSendBack(card.job.id, reason!, note); onDone(`${card.job.number} sent back · ${api.SEND_BACK_REASONS[reason!]}`); onClose(); } catch (x) { setErr(x instanceof Error ? x.message : 'Failed'); } }}><ArrowLeft size={18} /> Send back</Big></div>
  </Sheet>;
};

// Tech picker — supervisor override of the working tech; reflects on /rw/wm immediately
const TechSheet = ({ card, onClose, onDone }: { card: PadCard; onClose: () => void; onDone: Say }) => {
  const techs = api.getRoomTechs(); const [err, setErr] = useState<string | null>(null);
  return <Sheet testId="pad-tech-sheet" title="Assign tech" sub={<>{card.job.number} · {card.job.watch.brand} {card.job.watch.model} · logged as a supervisor override</>} onClose={onClose}>
    <div className="grid grid-cols-2 gap-3">{techs.map((u) => <button key={u.id} data-testid={`pad-tech-pick-${u.shortName.toLowerCase()}`} onClick={async () => { try { await api.padSetTech(card.job.id, u.shortName); onDone(`${card.job.number} → ${u.shortName} · supervisor override`); onClose(); } catch (x) { setErr(x instanceof Error ? x.message : 'Failed'); } }} className={`min-h-[72px] rounded-2xl border p-4 text-left ${card.job.assignees[0] === u.shortName ? 'border-accent bg-accent/15' : 'border-white/15 hover:bg-white/5'}`}><div className="text-xl font-semibold text-white">{u.shortName}</div><div className="text-sm text-slate-400">{u.dutyLabel}</div></button>)}</div>
    {err && <p className="mt-3 text-sm text-rose-400">{err}</p>}
  </Sheet>;
};

// Detail sheet — photo set (grid + zoom) AND the condition report, read-only. The supervisor never leaves the pad.
const DetailSheet = ({ card, onClose, say }: { card: PadCard; onClose: () => void; say: Say }) => {
  const [photos, setPhotos] = useState<JobPhotoView[]>([]); const [cond, setCond] = useState<PadConditionView | null>(null); const [open, setOpen] = useState<JobPhotoView | null>(null); const [zoom, setZoom] = useState(false);
  const [emails, setEmails] = useState<JobEmailRow[]>([]); const [mailOpen, setMailOpen] = useState<string | null>(null);
  const [tick, setTick] = useState(0); useEffect(() => { api.getJobPhotoViews(card.job.id).then(setPhotos); api.getPadCondition(card.job.id).then(setCond); api.getJobEmails(card.job.id).then(setEmails); }, [card.job.id, tick]);
  return <Sheet wide testId="pad-detail-sheet" title={<span className="font-mono">{card.job.number}</span>} sub={<>{card.job.watch.brand} {card.job.watch.model} · <span className="font-mono">{card.job.watch.reference}</span> · {card.stageLabel} · {card.job.assignees.join(', ') || 'unassigned'}</>} onClose={onClose}>
    <div className="grid gap-6 lg:grid-cols-[1fr_380px]">
      <section><div className="mb-2 flex items-center justify-between"><h3 className="inline-flex items-center gap-2 text-lg font-semibold text-white"><Camera size={18} /> Photos <span className="font-mono text-slate-400">{photos.length}</span></h3><CameraCapture jobId={card.job.id} jobNumber={card.job.number} onDone={(m) => { say(m); setTick((t) => t + 1); }} /></div>
        <div data-testid="pad-photo-groups" className="mb-2 flex flex-wrap gap-2 text-xs">{(['intake', 'inspection', 'completed'] as const).map((k) => <span key={k} data-testid={`pad-photo-group-${k}`} className="rounded-full bg-white/5 px-2.5 py-1 capitalize text-slate-300">{k} photos <span className="font-mono text-white">{photos.filter((p) => p.kind === k).length}</span></span>)}</div>
        <div data-testid="pad-detail-photos" className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[...photos].sort((a, b) => ['intake', 'inspection', 'completed'].indexOf(a.kind) - ['intake', 'inspection', 'completed'].indexOf(b.kind)).map((p) => <button key={p.id} data-testid={`pad-photo-${p.id}`} onClick={() => { setOpen(p); setZoom(false); }} className="relative aspect-[4/3] overflow-hidden rounded-2xl bg-white/5"><img src={p.url} alt={p.slot} className="h-full w-full object-cover" /><span className="absolute inset-x-0 bottom-0 bg-black/60 px-2 py-1.5 text-left text-sm"><span className={`mr-1.5 rounded-sm px-1 text-[10px] uppercase ${p.kind === 'intake' ? 'bg-sky-500/80' : 'bg-amber-500/80 text-black'}`}>{p.kind}</span><span data-testid={`pad-photo-class-${p.id}`} data-class={p.dataClass} className={`mr-1.5 rounded-sm px-1 text-[10px] uppercase ${p.dataClass === 'identity' ? 'bg-rose-600/90' : p.dataClass === 'specimen' ? 'bg-indigo-500/80' : 'bg-white/20'}`}>{p.dataClass}</span>{p.slot}</span></button>)}{!photos.length && <p data-testid="pad-detail-nophotos" className="col-span-full py-8 text-center text-slate-500">No photos on this job yet — tap Camera to take the first.</p>}</div></section>
      <section data-testid="pad-detail-condition"><h3 className="mb-2 inline-flex items-center gap-2 text-lg font-semibold text-white"><ClipboardList size={18} /> Inspection report · condition on arrival</h3>
        {cond?.source === 'none' && <p className="text-slate-500">No inspection recorded yet.{cond.notes && <> Intake note: {cond.notes}</>}</p>}
        {cond && cond.source !== 'none' && <><p className="mb-2 text-sm text-slate-400">{cond.source === 'report' ? 'Condition report' : 'Inspection form'} · {cond.issuedBy} · {cond.issuedAt && fmtDate(cond.issuedAt)}</p>
          <ul className="divide-y divide-white/10 rounded-2xl border border-white/10">{cond.rows.map((r) => <li key={r.component} data-testid={`pad-cond-${r.component.toLowerCase().replace(/[^a-z]+/g, '-')}`} className="flex items-start gap-3 px-4 py-3"><span className="w-28 shrink-0 text-base text-slate-200">{r.component}</span><span className={`rounded-full px-2.5 py-0.5 text-sm font-semibold capitalize ${GRADE_TONE[r.grade] ?? 'bg-white/10 text-slate-100'}`}>{r.grade}</span>{r.note && <span className="text-sm text-slate-300">{r.note}</span>}</li>)}</ul>
          {cond.notes && <p className="mt-3 rounded-2xl bg-white/5 px-4 py-3 text-base text-slate-200">{cond.notes}</p>}</>}
      </section>
    </div>
    <section data-testid="pad-detail-emails" className="mt-6"><h3 className="mb-2 inline-flex items-center gap-2 text-lg font-semibold text-white"><Mail size={18} /> Sent emails <span className="text-sm font-normal text-slate-500">read-only · Sent history for this job · parts-approval first</span></h3>
      <ul className="divide-y divide-white/10 rounded-2xl border border-white/10">{[...emails].sort((a, b) => (a.kind === 'parts_approval' ? -1 : b.kind === 'parts_approval' ? 1 : 0)).map((r) => <li key={r.email.id} data-testid={`pad-email-${r.email.id}`} data-kind={r.kind} className="px-4 py-3"><button onClick={() => setMailOpen(mailOpen === r.email.id ? null : r.email.id)} className="flex w-full items-center gap-3 text-left"><span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold uppercase ${r.kind === 'parts_approval' ? 'bg-accent text-[#161b22]' : 'bg-white/10 text-slate-200'}`}>{r.kind.replace('_', ' ')}</span><span className="flex-1 truncate text-base text-slate-100">{r.email.subject}</span>{r.requestNumber && <span className="font-mono text-sm text-slate-400">{r.requestNumber}</span>}<span data-testid={`pad-email-status-${r.email.id}`} className={`rounded-full px-2 py-0.5 text-xs font-semibold ${r.status.startsWith('approved') ? 'bg-emerald-700 text-emerald-50' : r.status === 'declined' ? 'bg-rose-700 text-rose-50' : 'bg-sky-800 text-sky-100'}`}>{r.status}</span><span className="text-xs text-slate-500">{fmtDate(r.email.createdAt)} {fmtTime(r.email.createdAt)} · {r.email.createdBy}</span></button>
        {mailOpen === r.email.id && <pre data-testid={`pad-email-body-${r.email.id}`} className="mt-2 whitespace-pre-wrap rounded-xl bg-white/5 px-4 py-3 font-sans text-sm text-slate-300">To: {r.email.toName} &lt;{r.email.to}&gt;{'\n\n'}{r.email.body}</pre>}</li>)}{!emails.length && <li className="px-4 py-4 text-sm text-slate-500">No emails sent for this job yet.</li>}</ul></section>
    <section data-testid="pad-detail-messages" className="mt-6"><h3 className="mb-2 inline-flex items-center gap-2 text-lg font-semibold text-white"><MessageSquare size={18} /> Messages <span className="text-sm font-normal text-slate-500">threaded · @ to route · internal only</span></h3><MessagesPanel job={card.job} dark /></section>
    {open && <div data-testid="rw-lightbox" className="fixed inset-0 z-[70] flex flex-col bg-black" onClick={() => setOpen(null)}><div className="flex items-center justify-between px-5 py-3 text-sm text-white"><span>{open.slot} · {open.kind} · {open.by} · {fmtDate(open.at)} {fmtTime(open.at)}</span><span className="text-slate-400">tap image to zoom · tap outside to close</span></div><div className="flex flex-1 items-center justify-center overflow-auto p-4"><img src={open.url} alt={open.slot} onClick={(e) => { e.stopPropagation(); setZoom((z) => !z); }} className={`rounded-lg transition-transform duration-200 ${zoom ? 'scale-[1.8] cursor-zoom-out' : 'max-h-full cursor-zoom-in'}`} /></div></div>}
  </Sheet>;
};

const STAGES = ['approved', 'in_service', 'testing', 'ready_to_ship'];
const Stepper = ({ stage }: { stage: string }) => <div data-testid="pad-stepper" className="flex items-center gap-1">{STAGES.map((s, i) => <span key={s} className={`h-2 flex-1 rounded-full ${i <= STAGES.indexOf(stage) ? 'bg-amber-400' : 'bg-white/10'}`} />)}</div>;

export const PadJobs = ({ cards, hit, say, reload }: { cards: PadCard[]; hit: string | null; say: Say; reload: () => void }) => {
  const nav = useNavigate();
  const [sendBack, setSendBack] = useState<PadCard | null>(null); const [vendorFor, setVendorFor] = useState<PadCard | null>(null); const [tech, setTech] = useState<PadCard | null>(null); const [detail, setDetail] = useState<PadCard | null>(null);
  const run = async (f: () => Promise<unknown>, m: string) => { try { await f(); say(m); } catch (x) { say(x instanceof Error ? x.message : 'Failed', 'err'); } };
  // Card / list view switcher — local state (the main Jobs board keeps its view in the URL; the pad has no URL state, so local is the match)
  const [view, setView] = useState<'cards' | 'list'>('cards');
  const switcher = <div data-testid="pad-view-switch" className="mb-3 flex items-center justify-end gap-1 md:col-span-2 xl:col-span-3"><span className="mr-2 text-xs text-slate-400">{cards.length} jobs</span>{(['cards', 'list'] as const).map((v) => <button key={v} data-testid={`pad-view-${v}`} aria-pressed={view === v} onClick={() => setView(v)} className={`inline-flex h-10 items-center gap-1.5 rounded-xl px-3 text-sm font-semibold ${view === v ? 'bg-accent text-[#161b22]' : 'bg-white/5 text-slate-300'}`}>{v === 'cards' ? <LayoutGrid size={16} /> : <List size={16} />}{v === 'cards' ? 'Cards' : 'List'}</button>)}</div>;
  if (view === 'list') return <div data-testid="pad-jobs-tab" data-view="list">{switcher}
    <table data-testid="pad-jobs-table" className="w-full text-sm text-slate-200"><thead><tr className="text-left text-[11px] uppercase tracking-wide text-slate-500"><th className="px-3 py-2">Job</th><th className="px-3 py-2">Kind</th><th className="px-3 py-2">Client</th><th className="px-3 py-2">Watch</th><th className="px-3 py-2">Workflow</th><th className="px-3 py-2">Stage</th><th className="px-3 py-2">Priority</th><th className="px-3 py-2">Assignees</th><th className="px-3 py-2 text-right">Due</th><th className="px-3 py-2 text-right">Parts</th><th className="px-3 py-2" /></tr></thead>
      <tbody>{cards.map((c) => <tr key={c.job.id} data-testid={`pad-row-${c.job.id}`} onClick={() => setDetail(c)} className={`cursor-pointer border-t border-white/10 hover:bg-white/5 ${hit === c.job.id ? 'bg-accent/15 ring-1 ring-inset ring-accent' : ''}`}><td className="px-3 py-2 font-mono font-bold text-white">{c.job.number}<ComponentWaitChips jobId={c.job.id} dark /></td><td className="px-3 py-2 capitalize text-slate-400">{c.job.kind.replace('_', ' ')}</td><td className="px-3 py-2">{c.job.client.firstName} {c.job.client.lastName}</td><td className="px-3 py-2 text-slate-300">{c.job.watch.brand} {c.job.watch.model} <span className="font-mono text-slate-500">{c.job.watch.reference}</span></td><td className="px-3 py-2 font-mono text-xs text-slate-300">{c.job.workflow.join(' · ')}</td><td className="px-3 py-2"><span className="rounded-full bg-white/10 px-2 py-0.5 text-xs">{c.stageLabel}</span></td><td className="px-3 py-2 capitalize text-slate-400">{c.job.priority}</td><td className="px-3 py-2 text-slate-300">{c.job.assignees.length ? c.job.assignees.map((a) => api.shortNameOf(a)).join(', ') : <span className="text-slate-500">—</span>}</td><td className="px-3 py-2 text-right text-slate-400">{c.job.dueAt ? fmtDate(c.job.dueAt) : '—'}</td><td className="px-3 py-2 text-right">{c.pendingParts ? <span className="rounded-full bg-amber-400 px-2 py-0.5 text-xs font-bold text-[#161b22]">{c.pendingParts} pending</span> : <span className="text-slate-500">{c.parts.length}</span>}</td>
        <td className="px-2 py-1" onClick={(e) => e.stopPropagation()}><div className="flex justify-end gap-1"><button data-testid={`pad-row-sendback-${c.job.id}`} disabled={!c.canSendBack} onClick={() => setSendBack(c)} className="rounded-lg bg-white/10 px-2 py-1.5 text-xs disabled:opacity-30"><ArrowLeft size={14} /></button><button data-testid={`pad-row-advance-${c.job.id}`} disabled={!c.canAdvance} onClick={() => run(() => api.padAdvance(c.job.id), `${c.job.number} advanced`)} className="rounded-lg bg-amber-400 px-2 py-1.5 text-xs text-[#161b22] disabled:opacity-30"><ArrowRight size={14} /></button></div></td></tr>)}</tbody></table>
    {!cards.length && <p className="px-3 py-6 text-center text-sm text-slate-500">No jobs in the room</p>}
    {vendorFor && <SwoForm init={{ jobId: vendorFor.job.id, components: [vendorFor.job.components[0]?.key ?? 'head'], pointPerson: 'Chyna' }} onClose={() => setVendorFor(null)} onSaved={(m, hubId) => { setVendorFor(null); say(`${m} · custody unchanged until the outbound scan`); reload(); nav(`/rw/swo/${hubId}`); }} />}
    {sendBack && <SendBackSheet card={sendBack} onClose={() => setSendBack(null)} onDone={(m) => { say(m); setSendBack(null); reload(); }} />}
    {detail && <DetailSheet card={detail} onClose={() => { setDetail(null); reload(); }} say={say} />}
  </div>;
  return <div data-testid="pad-jobs-tab" data-view="cards" className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
    {switcher}
    {cards.map((c) => { const open = api.openClientRequests(c.job).length; return <article key={c.job.id} data-testid={`pad-card-${c.job.id}`} className={`flex flex-col gap-3 rounded-[28px] border bg-[#1f2630] p-5 ${hit === c.job.id ? 'border-accent ring-2 ring-accent/50' : 'border-white/10'}`}>
      <button data-testid={`pad-open-${c.job.id}`} onClick={() => setDetail(c)} className="flex items-start justify-between gap-2 text-left active:opacity-70"><div><div className="font-mono text-2xl font-bold text-white">{c.job.number}</div><div className="text-lg text-slate-200">{c.job.watch.brand} {c.job.watch.model}</div><div className="font-mono text-sm text-slate-500">{c.job.watch.reference} · cal. {api.caliberOf(c.job.watch.reference) ?? '—'} · {c.job.kind.replace('_', ' ')}{api.activeHold(c.job) && <span className="ml-2 text-rose-300">· on hold</span>}</div></div><ChevronRight size={22} className="mt-1 shrink-0 text-slate-500" /></button>
      <div className="flex flex-wrap items-center gap-2"><Chip testId={`pad-stage-${c.job.id}`}>{c.stageLabel}</Chip><ComponentWaitChips jobId={c.job.id} dark compact /><AtRiskTag jobId={c.job.id} dark /><Chip tone="neutral" testId={`pad-tech-chip-${c.job.id}`} onClick={() => setTech(c)}><UserRound size={16} /> {c.job.assignees[0] ?? 'Assign tech'}{c.job.assignees.length > 1 && <span className="text-slate-400">+{c.job.assignees.length - 1}</span>}</Chip><ClientRequestBadge n={open} testId={`pad-cr-badge-${c.job.id}`} />{c.pendingParts > 0 && <Chip tone="violet">{c.pendingParts} parts pending</Chip>}</div>
      <Stepper stage={c.stage} />
      <div className="flex items-center gap-2">{c.parts.map((p) => <PartDot key={p.key} k={p.key} size={16} hollow={p.partStatus === 'not_started' || p.partStatus === 'in_progress'} title={`${p.label} · ${api.RW_STATIONS.find((s) => s.key === p.station)?.label}`} />)}<span className="text-xs text-slate-500">{c.photos} photos</span></div>
      <PartLocations parts={c.parts} />
      {c.stage === 'testing' && (c.job.clientRequests?.length ?? 0) > 0 ? <div data-testid={`pad-qc-checklist-${c.job.id}`} className="rounded-2xl border border-amber-400/50 bg-amber-400/10 p-3"><div className="mb-2 text-xs font-bold uppercase tracking-wide text-amber-300">Final QC · client requests checklist</div><QcRequestChecklist job={c.job} run={async (f, m) => { await run(f, m); reload(); }} dark /></div> : <ClientRequestList job={c.job} testId={`pad-client-requests-${c.job.id}`} />}
      <div className="mt-auto grid grid-cols-[1fr_1fr_auto_auto] gap-2"><Big testId={`pad-sendback-${c.job.id}`} disabled={!c.canSendBack} onClick={() => setSendBack(c)}><ArrowLeft size={18} /> Send back</Big><Big testId={`pad-advance-${c.job.id}`} tone="primary" disabled={!c.canAdvance} onClick={() => run(() => api.padAdvance(c.job.id), `${c.job.number} advanced`)}>Advance <ArrowRight size={18} /></Big><Big testId={`pad-send-vendor-${c.job.id}`} tone="quiet" disabled={api.jobOnVendorLane(c.job.id)} title={api.jobOnVendorLane(c.job.id) ? 'Already on a vendor lane — one lane at a time' : 'New SWO — open a box for a vendor'} onClick={() => setVendorFor(c)}><Truck size={18} /></Big><CameraCapture compact jobId={c.job.id} jobNumber={c.job.number} onDone={(m) => { say(m); reload(); }} /></div>
    </article>; })}
    {!cards.length && <p className="col-span-full py-16 text-center text-lg text-slate-500">No jobs in the room.</p>}
    {vendorFor && <SwoForm init={{ jobId: vendorFor.job.id, components: [vendorFor.job.components[0]?.key ?? 'head'], pointPerson: 'Chyna' }} onClose={() => setVendorFor(null)} onSaved={(m, hubId) => { setVendorFor(null); say(`${m} · custody unchanged until the outbound scan`); reload(); nav(`/rw/swo/${hubId}`); }} />}
    {sendBack && <SendBackSheet card={sendBack} onClose={() => setSendBack(null)} onDone={say} />}
    {tech && <TechSheet card={tech} onClose={() => setTech(null)} onDone={say} />}
    {detail && <DetailSheet card={detail} onClose={() => { setDetail(null); reload(); }} say={say} />}
  </div>;
};
