import { Cpu, Minus, Plus, ScanLine, Sparkles, Trash2, Wand2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import * as api from '@/api/client';
import type { PadPartsContext, PadSuggestion, PartsRequestItem, PartsRequestWithRefs } from '@/api/client';
import { ScanInput } from '@/components/rw/RwBits';
import { Big, Chip, Price, STATUS_LABEL, statusTone } from './PadBits';
import { fmtMoney, fmtTime } from '@/lib/format';

type Say = (m: string, tone?: 'ok' | 'learn' | 'err') => void;

const SuggestionRow = ({ s, onPick, testId }: { s: PadSuggestion; onPick: () => void; testId: string }) => (
  <button data-testid={testId} onClick={onPick} className="flex min-h-[60px] w-full items-center gap-3 rounded-2xl px-4 text-left active:bg-white/10 hover:bg-white/5">
    <span className="flex-1"><span className="text-lg text-white">{s.part.name}</span><span className="ml-2 font-mono text-sm text-slate-500">{s.part.partNumber}</span><span className="block text-xs text-slate-500">{s.hint}</span></span>
    {s.learned && <span data-testid={`${testId}-learned`} className="inline-flex items-center gap-1 rounded-full bg-violet-600 px-2 py-0.5 text-[11px] font-bold uppercase text-white"><Wand2 size={11} /> learned</span>}
    {s.source !== 'learned' && <span className={`rounded-full px-2 py-0.5 text-[11px] uppercase ${s.source === 'ref' ? 'bg-emerald-800 text-emerald-100' : 'bg-sky-800 text-sky-100'}`}>{s.source === 'ref' ? 'model' : 'caliber'}</span>}
    <span className="w-24 text-right"><Price value={s.part.price} /><span className="block font-mono text-[11px] text-slate-500">{s.part.stock} on hand</span></span>
  </button>
);

// The request composer: scan → job / reference / caliber chip → caliber query (automatic) → reference-scoped description search → generic fallback
export const PadParts = ({ ctx, onCtx, say, requests, reload }: { ctx: PadPartsContext | null; onCtx: (c: PadPartsContext | null) => void; say: Say; requests: PartsRequestWithRefs[]; reload: () => void }) => {
  const [q, setQ] = useState(''); const [items, setItems] = useState<PartsRequestItem[]>([]); const [busy, setBusy] = useState(false);
  useEffect(() => { setItems([]); setQ(''); }, [ctx?.job.id]);
  const results = ctx && q.trim() ? api.padSearchParts(ctx.reference, ctx.caliber, q) : [];
  const add = (s?: PadSuggestion) => { if (!ctx) return; const d = s ? s.part.name : q.trim(); if (!d) return; if (s) api.padRecordSelection(ctx.reference, ctx.caliber, s.part, q); setItems((l) => { const i = l.findIndex((x) => (s ? x.partId === s.part.id : x.description === d && !x.partId)); return i >= 0 ? l.map((x, k) => (k === i ? { ...x, qty: x.qty + 1 } : x)) : [...l, { partId: s?.part.id, partNumber: s?.part.partNumber, description: d, qty: 1, price: s?.part.price, generic: !s }]; }); setQ(''); };
  const total = items.reduce((t, i) => t + (i.price ?? 0) * i.qty, 0);
  return <div data-testid="pad-parts-tab" className="grid gap-5 xl:grid-cols-[1fr_360px]">
    <section className="space-y-4">
      {!ctx ? <div data-testid="pad-parts-empty" className="rounded-[28px] border border-dashed border-amber-400/40 bg-amber-400/5 p-8 text-center"><ScanLine size={40} className="mx-auto text-amber-400" /><h2 className="mt-3 text-2xl font-bold text-white">Scan the watch to start a request</h2><p className="mt-1 text-slate-400">The pad resolves the job, its reference and caliber, then queues the caliber's parts before you type anything.</p><div className="mx-auto mt-5 max-w-lg"><ScanInput big testId="pad-parts-scan" placeholder="Scan watch label (job #, ref/serial)…" onScan={async (code) => onCtx(await api.getPadPartsContext(code))} /></div></div>
      : <>
        <header data-testid="pad-parts-header" className="flex flex-wrap items-center gap-3 rounded-[28px] border border-white/10 bg-[#1f2630] p-4"><Chip tone="amber" testId="pad-parts-job"><span className="font-mono">{ctx.job.number}</span></Chip><Chip testId="pad-parts-ref">{ctx.reference} · {ctx.job.watch.model}</Chip><Chip tone="blue" testId="pad-parts-caliber"><Cpu size={16} /> cal. {ctx.caliber ?? 'unknown'}</Chip><span className="text-sm text-slate-400">{ctx.job.client.firstName} {ctx.job.client.lastName}</span><button data-testid="pad-parts-rescan" onClick={() => onCtx(null)} className="ml-auto min-h-[44px] rounded-full border border-white/15 px-4 text-sm text-slate-200">Scan another</button></header>
        <div className="relative rounded-[28px] border border-white/10 bg-[#1f2630] p-4">
          <label className="text-xs font-bold uppercase tracking-wide text-slate-400">Describe the part · scoped to {ctx.reference}</label>
          <input data-testid="pad-part-input" value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') { e.preventDefault(); add(results[0]); } }} placeholder="e.g. crystal ring, black insert, mainspring…" className="mt-1 min-h-[60px] w-full rounded-2xl border border-white/15 bg-[#0f131a] px-4 text-xl text-slate-100 outline-none focus:border-amber-400" />
          {q.trim() && <div data-testid="pad-suggestions" className="mt-2 divide-y divide-white/5 rounded-2xl border border-white/10 bg-[#161b22]">{results.map((s) => <SuggestionRow key={s.part.id} s={s} onPick={() => add(s)} testId={`pad-suggest-${s.part.id}`} />)}
            <button data-testid="pad-freetype-add" onClick={() => add()} className="flex min-h-[60px] w-full items-center gap-3 rounded-b-2xl px-4 text-left hover:bg-white/5"><Sparkles size={18} className="text-amber-300" /><span className="flex-1"><span className="text-lg text-amber-100">{results.length ? 'None of these — ' : 'No match — '}add “{q.trim()}” as a GENERIC line</span><span className="block text-xs text-slate-500">No part number yet · the manager resolves it at review</span></span></button></div>}
          {!q.trim() && <div data-testid="pad-caliber-suggestions" className="mt-3"><div className="mb-1 inline-flex items-center gap-2 text-sm font-semibold text-sky-300"><Cpu size={16} /> Caliber {ctx.caliber ?? '—'} parts · offered automatically</div><div className="divide-y divide-white/5 rounded-2xl border border-white/10 bg-[#161b22]">{ctx.caliberParts.map((s) => <SuggestionRow key={s.part.id} s={s} onPick={() => add(s)} testId={`pad-cal-${s.part.id}`} />)}{!ctx.caliberParts.length && <p className="px-4 py-6 text-center text-slate-500">No caliber parts on file for this movement.</p>}</div></div>}
        </div>
        <div data-testid="pad-request-lines" className="rounded-[28px] border border-white/10 bg-[#1f2630] p-4">
          <div className="flex items-center justify-between"><h3 className="text-lg font-semibold text-white">Request lines <span className="font-mono text-slate-400">{items.length}</span></h3><span className="text-sm text-slate-400">Sale price · total <span className="font-mono text-white">{fmtMoney(total)}</span>{items.some((i) => i.generic) && <span className="ml-2 text-amber-300">+ generic lines priced at review</span>}</span></div>
          <ul className="mt-2 space-y-2">{items.map((it, i) => <li key={i} data-testid={`pad-item-${i}`} className="flex items-center gap-3 rounded-2xl bg-white/5 px-4 py-2"><span className="flex-1"><span className="text-lg text-white">{it.description}</span>{it.partNumber ? <span className="ml-2 font-mono text-sm text-slate-400">{it.partNumber}</span> : <span data-testid={`pad-item-generic-${i}`} className="ml-2 rounded-full bg-amber-400 px-2 py-0.5 text-[11px] font-bold uppercase text-[#161b22]">generic</span>}</span><Price value={it.price} /><button data-testid={`pad-item-minus-${i}`} onClick={() => setItems((l) => l.map((x, k) => (k === i ? { ...x, qty: Math.max(1, x.qty - 1) } : x)))} className="min-h-[44px] min-w-[44px] rounded-full border border-white/15"><Minus size={16} className="mx-auto" /></button><span data-testid={`pad-item-qty-${i}`} className="w-8 text-center font-mono text-xl">{it.qty}</span><button data-testid={`pad-item-plus-${i}`} onClick={() => setItems((l) => l.map((x, k) => (k === i ? { ...x, qty: x.qty + 1 } : x)))} className="min-h-[44px] min-w-[44px] rounded-full border border-white/15"><Plus size={16} className="mx-auto" /></button><button data-testid={`pad-item-remove-${i}`} onClick={() => setItems((l) => l.filter((_, k) => k !== i))} className="min-h-[44px] min-w-[44px] text-slate-400"><Trash2 size={18} className="mx-auto" /></button></li>)}{!items.length && <li className="px-4 py-4 text-center text-slate-500">Tap a suggestion or add a generic line.</li>}</ul>
          <div className="mt-3"><Big full testId="pad-composer-submit" tone="primary" disabled={!items.length || busy} onClick={async () => { setBusy(true); try { const r = await api.submitPadRequest(ctx.job.id, items); say(`${r.number} → manager review · ${items.length} line(s)`); setItems([]); reload(); } catch (x) { say(x instanceof Error ? x.message : 'Failed', 'err'); } finally { setBusy(false); } }}>Submit to manager review</Big></div>
        </div>
      </>}
    </section>
    <aside data-testid="pad-my-requests" className="rounded-[28px] border border-white/10 bg-[#1f2630] p-4"><h3 className="text-lg font-semibold text-white">Pad requests · stage</h3><p className="text-xs text-slate-500">pending review → awaiting client → approved / declined</p>
      <ul className="mt-2 divide-y divide-white/5">{requests.map((r) => <li key={r.id} data-testid={`pad-req-${r.id}`} className="py-3"><div className="flex items-center gap-2"><span className="font-mono text-base font-semibold text-white">{r.number}</span><span className="text-sm text-slate-400">{r.job.number} · {r.reference}</span><Chip tone={statusTone(r.status)} testId={`pad-req-status-${r.id}`}>{STATUS_LABEL[r.status] ?? r.status}</Chip></div><ul className="mt-1 text-sm text-slate-300">{r.items?.map((i, k) => <li key={k} className="flex justify-between gap-2"><span>{i.description} ×{i.qty}{i.generic && <span className="ml-1 text-amber-300">(generic)</span>}</span><span className="font-mono text-slate-400">{i.partNumber ?? '—'}</span></li>)}</ul><div className="mt-1 text-[11px] text-slate-500">{r.requestedBy} · {fmtTime(r.requestedAt)}{r.sentBy && ` · sent by ${r.sentBy}`}{r.allocatedAt && ' · allocated → picking'}</div></li>)}{!requests.length && <li className="py-6 text-center text-slate-500">No pad requests yet.</li>}</ul></aside>
  </div>;
};
