import { AlertTriangle, BookOpen, Check, Send, Wand2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import * as api from '@/api/client';
import type { M3keEvent, PartsRequestWithRefs } from '@/api/client';
import { Big, Chip, Price, Sheet, STATUS_LABEL, statusTone } from './PadBits';
import { fmtDate, fmtMoney, fmtTime } from '@/lib/format';

type Say = (m: string, tone?: 'ok' | 'learn' | 'err') => void;
type Queue = Awaited<ReturnType<typeof api.getReviewQueue>>;

// One line under review: price (required) + part number (resolve GENERIC → real part#). Resolution fires the M3KE capture.
const ReviewLine = ({ r, i, say, reload }: { r: PartsRequestWithRefs; i: number; say: Say; reload: () => void }) => {
  const it = r.items![i]; const [price, setPrice] = useState(it.price?.toString() ?? ''); const [pn, setPn] = useState(it.partNumber ?? '');
  const save = async (patch: { price?: number; partNumber?: string }) => { try { const res = await api.reviewItem(r.id, i, patch); if (res.learned) say(`M3KE learned: “${res.learned.description}” → ${res.learned.partNumber}`, 'learn'); reload(); } catch (x) { say(x instanceof Error ? x.message : 'Failed', 'err'); } };
  const matches = pn.trim() ? api.padSearchParts(r.reference ?? '', r.caliber, pn).filter((s) => s.part.partNumber.toLowerCase().includes(pn.trim().toLowerCase()) || !it.partId).slice(0, 4) : [];
  return <li data-testid={`review-line-${r.id}-${i}`} className={`rounded-2xl border p-3 ${it.generic ? 'border-amber-400/60 bg-amber-400/10' : 'border-white/10 bg-white/5'}`}>
    <div className="flex flex-wrap items-center gap-2"><span className="text-lg text-white">{it.description}</span><span className="font-mono text-slate-400">×{it.qty}</span>{it.generic ? <span data-testid={`review-generic-${r.id}-${i}`} className="inline-flex items-center gap-1 rounded-full bg-amber-400 px-2 py-0.5 text-[11px] font-bold uppercase text-[#161b22]"><AlertTriangle size={11} /> generic — no part #</span> : <span className="font-mono text-sm text-emerald-300">{it.partNumber}</span>}</div>
    <div className="mt-2 grid gap-2 sm:grid-cols-2">
      <label className="block"><span className="text-xs font-bold uppercase tracking-wide text-slate-400">Sale price · required</span><div className="mt-1 flex items-center gap-2"><span className="text-lg text-slate-400">$</span><input data-testid={`review-price-${r.id}-${i}`} inputMode="decimal" value={price} onChange={(e) => setPrice(e.target.value)} onBlur={() => { const n = Number(price); if (price.trim() && Number.isFinite(n) && n !== it.price) void save({ price: n }); }} placeholder="0.00" className={`min-h-[52px] w-full rounded-2xl border bg-[#0f131a] px-4 font-mono text-xl text-white outline-none focus:border-amber-400 ${it.price === undefined ? 'border-rose-500/60' : 'border-white/15'}`} /></div></label>
      <label className="block"><span className="text-xs font-bold uppercase tracking-wide text-slate-400">Part number {it.generic && '· resolve'}</span><input data-testid={`review-pn-${r.id}-${i}`} value={pn} onChange={(e) => setPn(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') void save({ partNumber: pn }); }} onBlur={() => { if (pn.trim() !== (it.partNumber ?? '')) void save({ partNumber: pn }); }} placeholder="e.g. 25-16610" className="mt-1 min-h-[52px] w-full rounded-2xl border border-white/15 bg-[#0f131a] px-4 font-mono text-xl text-white outline-none focus:border-amber-400" /></label>
    </div>
    {matches.length > 0 && pn.trim().toLowerCase() !== (it.partNumber ?? '').toLowerCase() && <div data-testid={`review-pn-matches-${r.id}-${i}`} className="mt-2 flex flex-wrap gap-2">{matches.map((s) => <button key={s.part.id} data-testid={`review-pn-pick-${r.id}-${i}-${s.part.id}`} onClick={() => { setPn(s.part.partNumber); if (!price.trim()) setPrice(String(s.part.price)); void save({ partNumber: s.part.partNumber, ...(it.price === undefined ? { price: s.part.price } : {}) }); }} className="inline-flex min-h-[44px] items-center gap-2 rounded-full border border-white/15 px-3 text-sm text-slate-100 hover:bg-white/10"><span className="font-mono">{s.part.partNumber}</span><span className="text-slate-400">{s.part.name}</span>{s.learned && <Wand2 size={12} className="text-violet-300" />}</button>)}</div>}
  </li>;
};

const ReviewCard = ({ r, say, reload }: { r: PartsRequestWithRefs; say: Say; reload: () => void }) => {
  const total = (r.items ?? []).reduce((t, i) => t + (i.price ?? 0) * i.qty, 0); const ready = (r.items ?? []).every((i) => i.price !== undefined);
  return <article data-testid={`review-card-${r.id}`} className="space-y-3 rounded-[28px] border border-white/10 bg-[#1f2630] p-5">
    <div className="flex flex-wrap items-center gap-3"><span className="font-mono text-2xl font-bold text-white">{r.number}</span><Chip tone={statusTone(r.status)}>{STATUS_LABEL[r.status]}</Chip><span className="text-sm text-slate-400">{r.requestedBy} · {fmtTime(r.requestedAt)} · <span className="font-mono">{r.job.number}</span> · {r.watch.brand} {r.watch.model} <span className="font-mono">{r.reference}</span>{r.caliber && ` · cal. ${r.caliber}`}</span></div>
    <ul className="space-y-2">{r.items?.map((_, i) => <ReviewLine key={`${r.id}-${i}-${r.items![i].partNumber ?? ''}-${r.items![i].price ?? ''}`} r={r} i={i} say={say} reload={reload} />)}</ul>
    <div className="flex flex-wrap items-center justify-between gap-3"><span className="text-base text-slate-300">Total for the client <span className="font-mono text-xl text-white">{fmtMoney(total)}</span></span><Big testId={`review-send-${r.id}`} tone="primary" disabled={!ready} title={ready ? undefined : 'Every line needs a price'} onClick={async () => { try { await api.sendForClientApproval(r.id); say(`${r.number} sent for client approval · email queued to Outbox`); reload(); } catch (x) { say(x instanceof Error ? x.message : 'Failed', 'err'); } }}><Send size={18} /> Send for client approval</Big></div>
    {!ready && <p data-testid={`review-missing-${r.id}`} className="text-sm text-rose-300">Price required on every line before sending.</p>}
  </article>;
};

const M3keSheet = ({ onClose }: { onClose: () => void }) => {
  const [rows, setRows] = useState<M3keEvent[]>([]); useEffect(() => { api.getM3keEvents().then(setRows); }, []);
  return <Sheet wide testId="m3ke-sheet" title="M3KE learning log" sub="Append-only · every manager resolution and supervisor selection · inspectable training data" onClose={onClose}>
    <table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500"><th className="py-2">when</th><th>kind</th><th>description</th><th>reference</th><th>caliber</th><th>part #</th><th>price</th><th>by</th></tr></thead>
      <tbody className="divide-y divide-white/5">{rows.map((e) => <tr key={e.id} data-testid={`m3ke-row-${e.id}`}><td className="py-2 font-mono text-slate-400">{fmtDate(e.ts)} {fmtTime(e.ts)}</td><td><Chip tone={e.kind === 'resolved' ? 'violet' : 'neutral'}>{e.kind}</Chip></td><td className="text-white">“{e.description}”</td><td className="font-mono">{e.reference}</td><td className="font-mono">{e.caliber ?? '—'}</td><td className="font-mono text-emerald-300">{e.partNumber}</td><td className="font-mono">{e.price !== undefined ? fmtMoney(e.price) : '—'}</td><td>{e.resolvedBy}</td></tr>)}</tbody></table>
  </Sheet>;
};

// Manager gate: price + part# per line → Send for client approval → (simulated) client decision → allocate to picking
export const PadReview = ({ q, say, reload, isManager }: { q: Queue | null; say: Say; reload: () => void; isManager: boolean }) => {
  const [log, setLog] = useState(false);
  if (!q) return null;
  if (!isManager) return <div data-testid="pad-review-readonly" className="rounded-[28px] border border-white/10 bg-[#1f2630] p-8 text-center text-lg text-slate-400">Manager review is manager-tier. Your requests' stages show on the Parts tab.</div>;
  const act = (f: () => Promise<unknown>, m: string) => f().then(() => { say(m); reload(); }).catch((x) => say(x instanceof Error ? x.message : 'Failed', 'err'));
  return <div data-testid="pad-review-tab" className="space-y-6">
    <section><div className="mb-2 flex items-center justify-between"><h2 className="text-xl font-bold text-white">Needs price &amp; part # <span className="font-mono text-slate-400">{q.review.length}</span></h2><button data-testid="m3ke-open" onClick={() => setLog(true)} className="inline-flex min-h-[44px] items-center gap-2 rounded-full border border-violet-400/40 px-4 text-sm text-violet-200"><BookOpen size={16} /> M3KE log</button></div>
      <div className="grid gap-4 lg:grid-cols-2">{q.review.map((r) => <ReviewCard key={r.id} r={r} say={say} reload={reload} />)}{!q.review.length && <p className="col-span-full rounded-[28px] border border-dashed border-white/10 py-8 text-center text-slate-500">Nothing waiting for review.</p>}</div></section>
    <section><h2 className="mb-2 text-xl font-bold text-white">Awaiting client <span className="font-mono text-slate-400">{q.awaitingClient.length}</span></h2>
      <div className="grid gap-4 lg:grid-cols-2">{q.awaitingClient.map((r) => <article key={r.id} data-testid={`awaiting-card-${r.id}`} className="space-y-3 rounded-[28px] border border-sky-500/30 bg-[#1f2630] p-5"><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-2xl font-bold text-white">{r.number}</span><Chip tone="blue">Awaiting client</Chip><span className="text-sm text-slate-400">{r.job.number} · {r.client.firstName} {r.client.lastName} · sent {r.sentForApprovalAt && fmtTime(r.sentForApprovalAt)} by {r.sentBy}</span></div>
        <ul className="text-base text-slate-200">{r.items?.map((i, k) => <li key={k} className="flex justify-between"><span>{i.description} ×{i.qty} <span className="font-mono text-sm text-slate-500">{i.partNumber}</span></span><Price value={i.price} /></li>)}</ul>
        <div className="flex flex-wrap gap-2"><Big testId={`sim-approve-${r.id}`} tone="quiet" onClick={() => act(() => api.simulateClientPartsDecision(r.id, 'approve'), `${r.number} approved by client (simulated)`)}><Check size={16} /> Simulate: client approves</Big><Big testId={`sim-decline-${r.id}`} tone="quiet" onClick={() => act(() => api.simulateClientPartsDecision(r.id, 'decline'), `${r.number} declined by client (simulated)`)}>Simulate: client declines</Big></div></article>)}{!q.awaitingClient.length && <p className="col-span-full rounded-[28px] border border-dashed border-white/10 py-6 text-center text-slate-500">No requests out with clients.</p>}</div></section>
    <section><h2 className="mb-2 text-xl font-bold text-white">Client approved · allocate <span className="font-mono text-slate-400">{q.toAllocate.length}</span></h2>
      <div className="grid gap-4 lg:grid-cols-2">{q.toAllocate.map((r) => { const short = (r.items ?? []).some((i) => i.partId && (api.partsOnHand(i.partId) < i.qty)); return <article key={r.id} data-testid={`allocate-card-${r.id}`} className={`space-y-3 rounded-[28px] border p-5 ${short ? 'border-rose-500/60 bg-rose-950/30' : 'border-emerald-500/30 bg-[#1f2630]'}`}><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-2xl font-bold text-white">{r.number}</span><Chip tone="green">Client approved</Chip><span className="text-sm text-slate-400">{r.job.number} · {r.watch.brand} {r.watch.model}</span></div>
        <ul className="text-base text-slate-200">{r.items?.map((i, k) => <li key={k} className="flex items-center justify-between gap-2"><span>{i.description} ×{i.qty} <span className="font-mono text-sm text-slate-500">{i.partNumber}</span></span><span className={`font-mono text-sm ${i.partId && api.partsOnHand(i.partId) < i.qty ? 'text-rose-300' : 'text-slate-400'}`}>{i.partId ? `${api.partsOnHand(i.partId)} on hand` : 'no part #'}</span></li>)}</ul>
        {short && <p data-testid={`allocate-oos-${r.id}`} className="inline-flex items-center gap-2 text-base font-bold text-rose-300"><AlertTriangle size={18} /> OUT OF STOCK</p>}
        <div className="flex flex-wrap gap-2">{short ? <Big testId={`allocate-order-${r.id}`} tone="warn" onClick={() => act(() => api.approvalAction(r.id, 'on_order'), `${r.number} → on order`)}>Order part</Big> : <Big testId={`allocate-${r.id}`} tone="primary" onClick={() => act(() => api.padAllocate(r.id), `${r.number} allocated → picking queue`)}><Check size={18} /> Allocate → Picking</Big>}</div></article>; })}{!q.toAllocate.length && <p className="col-span-full rounded-[28px] border border-dashed border-white/10 py-6 text-center text-slate-500">Nothing approved awaiting allocation.</p>}</div></section>
    <section><h2 className="mb-2 text-xl font-bold text-white">Bench requests (WM room) <span className="font-mono text-slate-400">{q.bench.length}</span></h2>
      <div className="grid gap-4 lg:grid-cols-2">{q.bench.map((r) => { const out = !!r.partId && r.onHand <= 0; return <article key={r.id} data-testid={`pad-approval-${r.id}`} className={`space-y-3 rounded-[28px] border p-5 ${out ? 'border-rose-500/60 bg-rose-950/30' : 'border-white/10 bg-[#1f2630]'}`}>
        <div className="flex flex-wrap items-center gap-3"><span className="font-mono text-xl font-semibold text-white">{r.number}</span><span className="text-sm text-slate-400">{r.requestedBy} · {r.job.number} · {r.watch.brand} {r.watch.model}</span>{r.status === 'on_order' && <Chip tone="violet">On order</Chip>}</div>
        <div className="text-lg text-white">{r.part?.name ?? r.items?.map((i) => i.description).join(', ') ?? 'Free-typed part'} <span className="font-mono text-base text-slate-400">×{r.qty}</span>{r.part && <span className="ml-3"><Price value={r.part.price} /></span>}</div>
        <div className="flex items-center gap-3 text-base"><span data-testid={`pad-onhand-${r.id}`} className={`rounded-full px-3 py-1 font-mono ${out ? 'bg-rose-600 text-white' : 'bg-white/10 text-slate-100'}`}>{r.partId ? `${r.onHand} on hand` : 'not in catalog'}</span>{r.part?.location && <span className="text-sm text-slate-400">{r.part.location}</span>}{out && <span data-testid={`pad-out-of-stock-${r.id}`} className="inline-flex items-center gap-1 font-bold text-rose-300"><AlertTriangle size={18} /> OUT OF STOCK</span>}</div>
        <div className="flex flex-wrap gap-2">{r.status === 'pending' && (out || !r.partId ? <Big testId={`pad-order-${r.id}`} tone="warn" onClick={() => act(() => api.approvalAction(r.id, 'on_order'), `${r.number} → on order`)}>Order part</Big> : <Big testId={`pad-approve-${r.id}`} tone="primary" onClick={() => act(() => api.approvalAction(r.id, 'approve'), `${r.number} approved · allocated → picking`)}><Check size={18} /> Approve</Big>)}{r.status === 'pending' && <Big testId={`pad-decline-${r.id}`} onClick={() => act(() => api.approvalAction(r.id, 'decline'), `${r.number} declined`)}>Decline</Big>}{r.status === 'on_order' && <Big testId={`pad-received-${r.id}`} tone="primary" onClick={() => act(() => api.approvalAction(r.id, 'received'), `${r.number} received`)}>Received</Big>}</div>
      </article>; })}{!q.bench.length && <p className="col-span-full rounded-[28px] border border-dashed border-white/10 py-6 text-center text-slate-500">Bench queue empty.</p>}</div></section>
    {log && <M3keSheet onClose={() => setLog(false)} />}
  </div>;
};
