import { Camera, FileScan, Plus, Printer, Save, ScanLine } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import * as api from '@/api/client';
import type { Authenticity, BraceletRepairLine, Condition, InspComponent, InspComponentEntry, InspectionForm } from '@/api/client';
import * as ai from '@/api/ai';
import { InspectionCameraFlow } from '@/components/inspection/InspectionCameraFlow';
import { InspectionReportView } from '@/components/inspection/InspectionReportView';
import { Flash, Head } from '@/components/rs/RsBits';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { fmtMoney } from '@/lib/format';

const inp = 'h-8 rounded-sm border border-line bg-surface px-2 text-xs focus:border-ink focus:outline-none';
const chip = (on: boolean, tone = 'bg-ink text-white') => `rounded-full border px-2.5 py-1 text-xs font-medium transition-colors ${on ? `${tone} border-transparent` : 'border-line text-ink-600 hover:bg-canvas'}`;
const DEPTS = ['W', 'B', 'P', 'PM', 'SJ'];

// New Inspection form — two-stage (Customer → Watch & Inspection), per-component cards with learned preset notes, bracelet repair options, running total, live report preview
export default function InspectionFormPage({ basePath = '/inspection' }: { basePath?: string }) {
  const { id } = useParams(); const [params] = useSearchParams(); const nav = useNavigate();
  const [f, setF] = useState<InspectionForm | null>(null); const [stage, setStage] = useState<'customer' | 'watch'>('customer'); const [cam, setCam] = useState(params.get('camera') === '1'); const [msg, setMsg] = useState<string | null>(null); const [err, setErr] = useState<string | null>(null);
  const [sheet, setSheet] = useState<api.SheetSuggestion | null>(null); const [accepted, setAccepted] = useState<Set<string>>(new Set()); const [scanning, setScanning] = useState(false); const fileRef = useRef<HTMLInputElement>(null); const [label, setLabel] = useState('');
  useEffect(() => { (id ? api.getInspectionForm(id) : api.newInspectionForm({ jobId: params.get('job') ?? undefined, estimateNumber: params.get('est') ?? undefined })).then((x) => { if (!x) { setErr('Form not found'); return; } setF(x); if (!id && !x.jobId) setStage('customer'); else setStage('watch'); if (!id) nav(`${basePath}/${x.id}${params.get('camera') === '1' ? '?camera=1' : ''}`, { replace: true }); }); }, [id]); // eslint-disable-line react-hooks/exhaustive-deps
  const total = useMemo(() => (f ? api.inspectionTotal(f) : 0), [f]);
  if (!f) return err ? <p className="text-sm text-rose-700">{err}</p> : null;
  const up = (patch: Partial<InspectionForm>) => setF({ ...f, ...patch });
  const upC = (c: InspComponent, patch: Partial<InspComponentEntry>) => up({ components: f.components.map((x) => (x.component === c ? { ...x, ...patch } : x)) });
  const upB = (key: string, patch: Partial<BraceletRepairLine>) => up({ bracelet: f.bracelet.map((l) => (l.key === key ? { ...l, ...patch } : l)) });
  const save = async (commit: boolean) => { try { const r = await api.saveInspectionForm(f, commit); setF(r); setErr(null); setMsg(commit ? `Saved · client report ${r.token}` : 'Draft saved'); } catch (e) { setErr(e instanceof Error ? e.message : 'Failed'); } };
  const scanLabel = async () => { const q = label.trim(); const j = (await api.searchJobs(q)).find((x) => x.number.toUpperCase() === q.toUpperCase() || x.estimate?.number.toUpperCase() === q.toUpperCase()); const est = j ? null : await api.lookupEstimate(q); const hit = j || est ? null : await api.findInspectionPackage(q); const seed = j ? { jobId: j.id } : est ? { estimateNumber: est.number } : hit ? { estimateNumber: hit.estimateNumber } : null; if (!seed) { setErr(`No job / estimate for “${label}”`); return; } const n = await api.newInspectionForm(seed); nav(`${basePath}/${n.id}`); };
  const scanSheet = async (file: File) => { setScanning(true); setErr(null); try { const w = await ai.extractInspectionSheet(file); const s: api.SheetSuggestion = { components: w.components as api.SheetSuggestion['components'], bracelet: w.bracelet as api.SheetSuggestion['bracelet'], additionalNotes: w.additionalNotes ?? undefined, confidence: w.confidence ?? null, raw: w.raw }; setSheet(s); const marked = (v: object | undefined) => !!v && Object.values(v).some((x) => x !== null && x !== undefined && !(Array.isArray(x) && !x.length)); setAccepted(new Set([...Object.keys(s.components).filter((k) => marked(s.components[k as InspComponent])), ...Object.keys(s.bracelet).filter((k) => marked(s.bracelet[k])).map((k) => `bracelet:${k}`), ...(s.additionalNotes ? ['additional'] : [])])); } catch (e) { setErr(e instanceof Error ? e.message : 'Extraction failed'); } finally { setScanning(false); } };
  return <div data-testid="inspection-form-page" className="space-y-4">
    {cam && <InspectionCameraFlow onShot={(p) => api.addInspectionPhoto(f.id, p).then(setF)} onDone={() => { setCam(false); setStage('watch'); }} onClose={() => setCam(false)} />}
    <Head title="New Inspection" sub={<>Legacy RolliWorks structure · learned preset notes · report served at <span className="font-mono">/rc/inspection/{f.token}</span> once saved</>} />
    <div data-testid="inspection-topbar" className="flex flex-wrap items-center gap-2 rounded-md border border-line bg-surface px-3 py-2">
      <form className="flex items-center gap-1" onSubmit={(e) => { e.preventDefault(); void scanLabel(); }}><ScanLine size={14} className="text-ink-400" /><input data-testid="insp-scan-label" value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Scan label · E02041" className={`${inp} w-40 font-mono`} /><Button size="sm" type="submit" data-testid="insp-scan-label-go">Scan Label</Button></form>
      <Button size="sm" data-testid="insp-camera" onClick={() => setCam(true)}><Camera size={13} /> Camera{f.photos.length ? ` (${f.photos.length})` : ''}</Button>
      <Button size="sm" data-testid="insp-scan-sheet" onClick={() => fileRef.current?.click()} disabled={scanning}><FileScan size={13} /> {scanning ? 'Reading sheet…' : 'Scan Sheet'}</Button><input ref={fileRef} data-testid="insp-sheet-file" type="file" accept="image/*,.pdf" className="hidden" onChange={(e) => { const file = e.target.files?.[0]; if (file) void scanSheet(file); e.target.value = ''; }} />
      <span className="mx-2 h-5 w-px bg-line" />
      {(['customer', 'watch'] as const).map((s, i) => <button key={s} data-testid={`insp-stage-${s}`} aria-current={stage === s} onClick={() => setStage(s)} className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-semibold ${stage === s ? 'bg-ink text-white' : 'bg-canvas text-ink-500'}`}><span className="grid h-4 w-4 place-items-center rounded-full bg-white/20 text-[10px]">{i + 1}</span>{s === 'customer' ? 'Customer' : 'Watch & Inspection'}</button>)}
      <span className="ml-auto text-xs text-ink-500">Total <b data-testid="insp-total" className="font-mono text-ink">{fmtMoney(total)}</b> · <span className={`rounded px-1.5 py-0.5 text-[10px] font-semibold ${f.status === 'saved' ? 'bg-moss-50 text-moss-700' : 'bg-amber-50 text-amber-800'}`} data-testid="insp-status">{f.status}</span></span>
    </div>
    <Flash error={err} msg={msg} />
    {sheet && <SheetVerify s={sheet} accepted={accepted} setAccepted={setAccepted} onApply={() => { setF(api.applySheetSuggestion(f, sheet, accepted)); setSheet(null); setMsg('Sheet values applied — review before saving'); }} onDismiss={() => setSheet(null)} />}

    {stage === 'customer' && <Card title="Customer" testId="insp-customer-card"><div className="grid grid-cols-3 gap-3"><label className="text-xs text-ink-500">Name<input data-testid="insp-customer-name" value={f.customer.name} onChange={(e) => up({ customer: { ...f.customer, name: e.target.value } })} className={`${inp} mt-1 block w-full`} /></label><label className="text-xs text-ink-500">Email<input data-testid="insp-customer-email" value={f.customer.email ?? ''} onChange={(e) => up({ customer: { ...f.customer, email: e.target.value } })} className={`${inp} mt-1 block w-full`} /></label><label className="text-xs text-ink-500">Phone<input value={f.customer.phone ?? ''} onChange={(e) => up({ customer: { ...f.customer, phone: e.target.value } })} className={`${inp} mt-1 block w-full`} /></label></div><div className="mt-3 flex justify-end"><Button variant="primary" data-testid="insp-next" onClick={() => setStage('watch')}>Next → Watch & Inspection</Button></div></Card>}

    {stage === 'watch' && <>
      <Card title="Watch details" testId="insp-watch-card">
        <div className="grid grid-cols-4 gap-3">
          {([['brand', 'Brand'], ['model', 'Model'], ['reference', 'Reference Number'], ['estimateNumber', 'Estimate Number']] as const).map(([k, l]) => <label key={k} className="text-xs text-ink-500">{l}<input data-testid={`insp-${k}`} value={f[k]} onChange={(e) => up({ [k]: e.target.value } as Partial<InspectionForm>)} className={`${inp} mt-1 block w-full`} /></label>)}
          <label className="text-xs text-ink-500">Target Weeks<div className="mt-1 flex items-center gap-1"><input data-testid="insp-target-weeks" type="number" min={1} value={f.targetWeeks} onChange={(e) => up({ targetWeeks: Number(e.target.value) })} className={`${inp} w-16`} /><input type="date" value={f.targetFrom ?? ''} onChange={(e) => up({ targetFrom: e.target.value || undefined })} className={inp} /><span className="text-ink-400">–</span><input type="date" value={f.targetTo ?? ''} onChange={(e) => up({ targetTo: e.target.value || undefined })} className={inp} /></div></label>
          <div className="text-xs text-ink-500">Department Tag<div className="mt-1 flex gap-1" data-testid="insp-dept-tags">{DEPTS.map((d) => <button key={d} data-testid={`insp-dept-${d}`} aria-pressed={f.deptTags.includes(d)} onClick={() => up({ deptTags: f.deptTags.includes(d) ? f.deptTags.filter((x) => x !== d) : [...f.deptTags, d] })} className={`h-8 rounded-sm border px-2 font-mono text-xs font-semibold ${f.deptTags.includes(d) ? 'border-ink bg-ink text-white' : 'border-line text-ink-500'}`}>{d}</button>)}</div></div>
          <label className="text-xs text-ink-500">Inspection Type<select data-testid="insp-type" value={f.inspectionType} onChange={(e) => up({ inspectionType: e.target.value })} className={`${inp} mt-1 block w-full`}>{['Complete Watch', 'Watch Head Only', 'Band Only', 'Movement Only'].map((o) => <option key={o}>{o}</option>)}</select></label>
          <label className="text-xs text-ink-500">Job Type<select data-testid="insp-job-type" value={f.jobType} onChange={(e) => up({ jobType: e.target.value })} className={`${inp} mt-1 block w-full`}>{['Service', 'Small job', 'Warranty', 'Trade', 'Estimate only'].map((o) => <option key={o}>{o}</option>)}</select></label>
        </div>
      </Card>
      <div className="grid grid-cols-[1fr_420px] gap-4">
        <div className="space-y-3">
          {f.components.map((c) => <ComponentCard key={c.component} c={c} onChange={(p) => upC(c.component, p)} />)}
          <Card title="Bracelet repair options" subtitle="Itemised · qty × price or hours @ rate" testId="insp-bracelet-options">
            <ul className="divide-y divide-line">{f.bracelet.map((l) => <li key={l.key} data-testid={`insp-br-${l.key}`} className="flex flex-wrap items-center gap-2 py-2 text-xs"><span className="w-5 font-mono text-ink-400">{l.n}</span><span className="w-64 text-ink">{l.label}{l.note && <div className="text-[10px] text-ink-400">{l.note}</div>}</span>
              {l.mode === 'qty_price' && <><input data-testid={`insp-br-${l.key}-qty`} type="number" min={0} value={l.qty ?? 0} onChange={(e) => upB(l.key, { qty: Number(e.target.value) })} className={`${inp} w-16`} /><span className="text-ink-400">×</span><input data-testid={`insp-br-${l.key}-price`} type="number" min={0} value={l.price ?? 0} onChange={(e) => upB(l.key, { price: Number(e.target.value) })} className={`${inp} w-20`} /><label className="inline-flex items-center gap-1"><input type="checkbox" checked={!!l.yesNo} onChange={(e) => upB(l.key, { yesNo: e.target.checked })} /> Y/N?</label></>}
              {l.mode === 'hours_rate' && <><input data-testid={`insp-br-${l.key}-hours`} type="number" min={0} step={0.5} value={l.hours ?? 0} onChange={(e) => upB(l.key, { hours: Number(e.target.value) })} className={`${inp} w-16`} /><span className="text-ink-400">h @</span><input type="number" value={l.rate ?? 98} onChange={(e) => upB(l.key, { rate: Number(e.target.value) })} className={`${inp} w-16`} /><span className="text-ink-400">/h</span>{(['rec', 'not_rec'] as const).map((r) => <button key={r} onClick={() => upB(l.key, { rec: l.rec === r ? undefined : r })} className={chip(l.rec === r, r === 'rec' ? 'bg-moss text-white' : 'bg-rose-600 text-white')}>{r === 'rec' ? 'Rec' : 'Not Rec'}</button>)}</>}
              {l.mode === 'scale' && <><input data-testid="insp-br-band-polish-scale" type="range" min={0} max={10} value={l.scale ?? 0} onChange={(e) => upB(l.key, { scale: Number(e.target.value) })} className="w-32" /><span className="w-8 font-mono">{l.scale}/10</span><button data-testid="insp-br-band-polish-include" onClick={() => upB(l.key, { include: !l.include })} className={chip(!!l.include)}>{l.include ? 'Included in email' : 'Not included in email'}</button></>}
              <span className="ml-auto font-mono text-ink">{l.mode === 'scale' ? '' : fmtMoney(l.mode === 'qty_price' ? (l.qty || 0) * (l.price || 0) : (l.hours || 0) * (l.rate || 0))}</span></li>)}</ul>
          </Card>
          <Card title="Inspection notes" subtitle="Overall · quick tags learn as you type" testId="insp-overall">
            <textarea data-testid="insp-overall-notes" rows={3} value={f.overall.notes} onChange={(e) => up({ overall: { ...f.overall, notes: e.target.value } })} className="w-full rounded-sm border border-line bg-surface px-2 py-1.5 text-xs" placeholder="Overall findings…" />
            <div className="mt-2 flex flex-wrap items-center gap-1.5">{api.inspectionQuickTags().map((t) => <button key={t} data-testid={`insp-quick-${t.replace(/\W+/g, '-')}`} onClick={() => up({ overall: { ...f.overall, quickTags: f.overall.quickTags.includes(t) ? f.overall.quickTags.filter((x) => x !== t) : [...f.overall.quickTags, t] } })} className={chip(f.overall.quickTags.includes(t))}>{t}</button>)}<AddTag testId="insp-quick-add" onAdd={async (t) => { await api.learnQuickTag(t); up({ overall: { ...f.overall, quickTags: [...f.overall.quickTags, t] } }); }} /></div>
            <div className="mt-2 flex flex-wrap items-center gap-3 text-xs"><label className="inline-flex items-center gap-1">Price $<input data-testid="insp-overall-price" type="number" min={0} value={f.overall.price} onChange={(e) => up({ overall: { ...f.overall, price: Number(e.target.value) } })} className={`${inp} w-24`} /></label><label className="inline-flex items-center gap-1"><input type="checkbox" checked={f.overall.yesNo} onChange={(e) => up({ overall: { ...f.overall, yesNo: e.target.checked } })} /> Add “Yes/No?” to summary</label><label data-testid="insp-overall-waiver" className={`inline-flex items-center gap-1 rounded px-1.5 py-0.5 ${f.overall.waiver ? 'bg-amber-100 font-semibold text-amber-900' : ''}`}><input type="checkbox" checked={f.overall.waiver} onChange={(e) => up({ overall: { ...f.overall, waiver: e.target.checked } })} /> Waiver required for this job</label></div>
          </Card>
          <div className="flex items-center justify-between rounded-md border border-line bg-surface px-4 py-3"><span className="text-sm font-semibold text-ink">Total estimate</span><span data-testid="insp-total-bottom" className="font-mono text-xl font-bold text-ink">{fmtMoney(total)}</span></div>
        </div>
        <div className="space-y-2">
          <div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-wide text-ink-500">Inspection report preview</span><span className="flex gap-1"><Button size="sm" data-testid="insp-save-draft" onClick={() => void save(false)}>Draft</Button><Button size="sm" variant="primary" data-testid="insp-save" onClick={() => void save(true)}><Save size={12} /> Save</Button><Button size="sm" data-testid="insp-pdf" onClick={() => window.print()}>PDF</Button><Button size="sm" data-testid="insp-print" onClick={() => window.print()}><Printer size={12} /> Print</Button></span></div>
          {f.status === 'saved' && <Link data-testid="insp-report-link" to={`/rc/inspection/${f.token}`} className="block text-xs text-brand hover:underline">Client link · /rc/inspection/{f.token}</Link>}
          <InspectionReportView f={f} />
        </div>
      </div>
    </>}
  </div>;
}

const ComponentCard = ({ c, onChange }: { c: InspComponentEntry; onChange: (p: Partial<InspComponentEntry>) => void }) => {
  const [open, setOpen] = useState(true); const lib = api.inspectionNoteLibrary(c.component); const [, force] = useState(0);
  return <section data-testid={`insp-comp-${c.component.toLowerCase()}`} className={`rounded-md border bg-surface ${c.waiver ? 'border-amber-400' : 'border-line'}`}>
    <button onClick={() => setOpen(!open)} className="flex w-full items-center gap-2 px-3 py-2 text-left"><span className="text-sm font-semibold text-ink">{c.component}</span>{c.condition && <span className="rounded bg-canvas px-1.5 py-0.5 text-[10px] font-semibold uppercase text-ink-600">{api.CONDITIONS.find((x) => x.key === c.condition)?.label}</span>}{c.waiver && <span className="rounded bg-amber-100 px-1.5 py-0.5 text-[10px] font-bold uppercase text-amber-900">waiver</span>}<span className="ml-auto text-xs text-ink-400">{c.notes.length + c.extraNotes.length} notes · {fmtMoney((c.price || 0) + (c.caseRestorationPrice || 0) + (c.weldingPrice || 0))}</span><span className="text-ink-400">{open ? '−' : '+'}</span></button>
    {open && <div className="space-y-2 border-t border-line px-3 py-2">
      <div className="flex flex-wrap gap-1" data-testid={`insp-cond-${c.component.toLowerCase()}`}>{api.CONDITIONS.filter((x) => x.key !== 'waiver' || ['Dial', 'Hands'].includes(c.component)).map((x) => <button key={x.key} data-testid={`insp-cond-${c.component.toLowerCase()}-${x.key}`} aria-pressed={c.condition === x.key} onClick={() => onChange({ condition: x.key as Condition })} className={chip(c.condition === x.key)}><span className="mr-1 font-mono text-[10px] opacity-60">{x.n}</span>{x.label}</button>)}</div>
      <div className="flex flex-wrap items-center gap-1 text-xs"><span className="mr-1 text-ink-400">Authenticity:</span>{api.AUTHENTICITY.map((a) => <button key={a.key} data-testid={`insp-auth-${c.component.toLowerCase()}-${a.key}`} aria-pressed={c.authenticity === a.key} title={a.blurb} onClick={() => onChange({ authenticity: a.key as Authenticity })} className={chip(c.authenticity === a.key, a.key === 'genuine' ? 'bg-moss text-white' : a.key === 'undetermined' ? 'bg-ink-400 text-white' : 'bg-rose-600 text-white')}>{a.label}</button>)}</div>
      <div className="grid grid-cols-2 gap-1" data-testid={`insp-notes-${c.component.toLowerCase()}`}>{lib.map((n, i) => <button key={i} data-testid={`insp-note-${c.component.toLowerCase()}-${i + 1}`} aria-pressed={c.notes.includes(i)} onClick={() => onChange({ notes: c.notes.includes(i) ? c.notes.filter((x) => x !== i) : [...c.notes, i] })} className={`flex items-start gap-1.5 rounded-sm border px-2 py-1 text-left text-xs ${c.notes.includes(i) ? 'border-ink bg-ink text-white' : 'border-line text-ink-700 hover:bg-canvas'}`}><span className="font-mono text-[10px] opacity-60">{i + 1}</span>{n}</button>)}</div>
      <div className="flex flex-wrap items-center gap-2 text-xs"><input data-testid={`insp-other-${c.component.toLowerCase()}`} value={c.otherNote ?? ''} onChange={(e) => onChange({ otherNote: e.target.value })} placeholder="Other…" className={`${inp} flex-1`} /><Button size="sm" data-testid={`insp-learn-${c.component.toLowerCase()}`} disabled={!c.otherNote?.trim()} onClick={async () => { const i = await api.learnInspectionNote(c.component, c.otherNote!); onChange({ notes: [...c.notes.filter((x) => x !== i), i], otherNote: '' }); force((x) => x + 1); }} title="Save this note into the preset library (learned)"><Plus size={12} /> Add Note</Button>
        <label data-testid={`insp-waiver-${c.component.toLowerCase()}`} className={`inline-flex items-center gap-1 rounded px-1.5 py-0.5 ${c.waiver ? 'bg-amber-100 font-semibold text-amber-900' : ''}`}><input type="checkbox" checked={c.waiver} onChange={(e) => onChange({ waiver: e.target.checked })} /> Waiver Required</label>
        <label className="inline-flex items-center gap-1">$<input data-testid={`insp-price-${c.component.toLowerCase()}`} type="number" min={0} value={c.price} onChange={(e) => onChange({ price: Number(e.target.value) })} className={`${inp} w-20`} /></label>
        <label className="inline-flex items-center gap-1"><input data-testid={`insp-yesno-${c.component.toLowerCase()}`} type="checkbox" checked={c.yesNo} onChange={(e) => onChange({ yesNo: e.target.checked })} /> Add “Yes/No?” to summary</label></div>
      {c.extraNotes.length > 0 && <ul className="text-xs text-ink-700">{c.extraNotes.map((n, i) => <li key={i} className="flex justify-between">• {n}<button onClick={() => onChange({ extraNotes: c.extraNotes.filter((_, j) => j !== i) })} className="text-ink-400">×</button></li>)}</ul>}
      <AddTag testId={`insp-extra-${c.component.toLowerCase()}`} placeholder="+ Add free-form note" onAdd={async (t) => onChange({ extraNotes: [...c.extraNotes, t] })} />
      {c.component === 'Dial' && <div className="flex flex-wrap items-center gap-1 text-xs"><span className="mr-1 text-ink-400">Dial variant:</span>{api.dialVariantTags().map((v) => <button key={v} data-testid={`insp-dial-variant-${v.replace(/\W+/g, '-')}`} onClick={() => onChange({ dialVariants: c.dialVariants?.includes(v) ? c.dialVariants.filter((x) => x !== v) : [...(c.dialVariants ?? []), v] })} className={chip(!!c.dialVariants?.includes(v), 'bg-violet-600 text-white')}>{v}</button>)}<AddTag testId="insp-dial-variant-add" placeholder="+ variant (e.g. BUCKLEY)" onAdd={async (t) => { await api.learnDialVariant(t); onChange({ dialVariants: [...(c.dialVariants ?? []), t] }); force((x) => x + 1); }} /></div>}
      {c.component === 'Case' && <div className="flex flex-wrap items-center gap-3 rounded-sm bg-canvas px-2 py-1.5 text-xs"><label className="inline-flex items-center gap-1"><input data-testid="insp-case-retail-polish" type="checkbox" checked={!!c.retailPolish} onChange={(e) => onChange({ retailPolish: e.target.checked })} /> Retail polish</label><label className="inline-flex items-center gap-1">Retail Case Restoration $<input data-testid="insp-case-restoration" type="number" min={0} value={c.caseRestorationPrice ?? 0} onChange={(e) => onChange({ caseRestorationPrice: Number(e.target.value) })} className={`${inp} w-20`} /></label><label className="inline-flex items-center gap-1">Welding Price $<input data-testid="insp-case-welding" type="number" min={0} value={c.weldingPrice ?? 0} onChange={(e) => onChange({ weldingPrice: Number(e.target.value) })} className={`${inp} w-20`} /></label></div>}
      {c.component === 'Crystal' && <div className="flex flex-wrap items-center gap-3 rounded-sm bg-canvas px-2 py-1.5 text-xs"><span>$<input data-testid="insp-crystal-polish-price" type="number" min={0} value={c.polishUpPrice ?? 0} onChange={(e) => onChange({ polishUpPrice: Number(e.target.value) })} className={`${inp} mx-1 w-20`} /> to polish up</span>{[true, false].map((v) => <button key={String(v)} data-testid={`insp-crystal-polish-${v ? 'yes' : 'no'}`} onClick={() => onChange({ polishUpYesNo: v })} className={chip(c.polishUpYesNo === v)}>{v ? 'Yes' : 'No'}</button>)}</div>}
    </div>}
  </section>;
};

const AddTag = ({ onAdd, testId, placeholder = '+ add new' }: { onAdd: (t: string) => Promise<unknown>; testId: string; placeholder?: string }) => { const [v, setV] = useState(''); return <form className="inline-flex items-center gap-1" onSubmit={(e) => { e.preventDefault(); if (v.trim()) void onAdd(v.trim()).then(() => setV('')); }}><input data-testid={testId} value={v} onChange={(e) => setV(e.target.value)} placeholder={placeholder} className={`${inp} w-44`} /></form>; };

// Suggest → verify: extracted sheet values per section, each accept/reject, then Apply. Nothing is written until Apply.
const SheetVerify = ({ s, accepted, setAccepted, onApply, onDismiss }: { s: api.SheetSuggestion; accepted: Set<string>; setAccepted: (a: Set<string>) => void; onApply: () => void; onDismiss: () => void }) => {
  const tog = (k: string) => { const n = new Set(accepted); if (n.has(k)) n.delete(k); else n.add(k); setAccepted(n); };
  const rows: { key: string; label: string; detail: string }[] = [
    ...Object.entries(s.components).filter(([, v]) => v && Object.values(v).some((x) => x !== null && x !== undefined && !(Array.isArray(x) && !x.length))).map(([k, v]) => ({ key: k, label: k, detail: [v?.condition ? `condition ${v.condition} (${api.CONDITIONS.find((c) => c.n === v.condition)?.label ?? '?'})` : null, v?.notes?.length ? `notes #${v.notes.join(', #')}` : null, v?.other ? `other “${v.other}”` : null, v?.price != null ? `$${v.price}` : null, v?.yesNo != null ? `Y/N ${v.yesNo ? 'Y' : 'N'}` : null, v?.retailPolish ? 'retail polish' : null, v?.caseRestoration != null ? `case restoration $${v.caseRestoration}` : null, v?.polishUp != null ? `polish up ${v.polishUp ? 'yes' : 'no'}` : null].filter(Boolean).join(' · ') || 'nothing marked' })),
    ...Object.entries(s.bracelet).filter(([, v]) => v && Object.values(v).some((x) => x !== null && x !== undefined)).map(([k, v]) => ({ key: `bracelet:${k}`, label: `Bracelet · ${api.BRACELET_LINES.find((l) => l.key === k)?.label ?? k}`, detail: JSON.stringify(v) })),
    ...(s.additionalNotes ? [{ key: 'additional', label: 'Additional notes', detail: s.additionalNotes }] : []),
  ];
  return <Card title="Scan Sheet → suggested values" subtitle={`Claude Vision read the scantron · confidence ${s.confidence != null ? Math.round(s.confidence * 100) + '%' : '—'} · accept each section, then Apply. Nothing is written until you do.`} testId="sheet-verify" accent="none" className="border-l-[3px] border-amber-400">
    <ul className="divide-y divide-line text-xs">{rows.map((r) => <li key={r.key} data-testid={`sheet-row-${r.key.replace(/\W+/g, '-')}`} className="flex items-start gap-2 py-1.5"><input type="checkbox" data-testid={`sheet-accept-${r.key.replace(/\W+/g, '-')}`} checked={accepted.has(r.key)} onChange={() => tog(r.key)} className="mt-0.5" /><span className="w-40 font-semibold text-ink">{r.label}</span><span className="flex-1 text-ink-700">{r.detail}</span></li>)}</ul>
    <div className="mt-3 flex justify-end gap-2"><Button size="sm" data-testid="sheet-dismiss" onClick={onDismiss}>Dismiss</Button><Button size="sm" variant="primary" data-testid="sheet-apply" onClick={onApply}>Apply {accepted.size} accepted</Button></div>
  </Card>;
};
