import { Lock, ScanLine, Unlock } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import * as api from '@/api/client';
import type { CountQueueRow, CycleCount, StockLocation, VarianceReport } from '@/api/client';
import { useAuth } from '@/auth/AuthContext';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { fmtDate, fmtMoneyCents } from '@/lib/format';

const tone = (d: number) => (d === 0 ? 'text-moss-700' : Math.abs(d) <= 2 ? 'text-amber-700' : 'text-rose-700');

// Location-locked fast counting: scan LOC-xx → lock · scan part → row → type qty → Enter → variance · uncounted → zero/skip · Confirm posts adjustments
export default function CycleCountPage() {
  const { user } = useAuth(); const [queue, setQueue] = useState<CountQueueRow[]>([]); const [loc, setLoc] = useState<StockLocation | null>(null); const [count, setCount] = useState<CycleCount | null>(null);
  const [counted, setCounted] = useState<Record<string, number>>({}); const [skipped, setSkipped] = useState<string[]>([]); const [scan, setScan] = useState(''); const [qty, setQty] = useState(''); const [active, setActive] = useState<string | null>(null); const [msg, setMsg] = useState<string | null>(null); const [posted, setPosted] = useState<CycleCount | null>(null); const [switchTo, setSwitchTo] = useState<StockLocation | null>(null); const [report, setReport] = useState<VarianceReport | null>(null);
  const scanRef = useRef<HTMLInputElement>(null); const qtyRef = useRef<HTMLInputElement>(null);
  const load = () => api.getCountQueue().then(setQueue);
  useEffect(() => { void load(); if (user?.accessTier === 'manager') void api.getVarianceReport().then(setReport).catch(() => setReport(null)); }, [posted, user?.accessTier]);
  const lock = async (l: StockLocation) => { try { const c = await api.startCycleCount(l.id); setLoc(l); setCount(c); setCounted({}); setSkipped([]); setPosted(null); setMsg(null); setSwitchTo(null); scanRef.current?.focus(); } catch (e) { setMsg(e instanceof Error ? e.message : 'Failed'); } };
  const onScan = (code: string) => {
    const l = api.resolveLocationScan(code); if (l) { if (!loc) void lock(l); else if (l.id !== loc.id) setSwitchTo(l); setScan(''); return; }
    if (!loc) { setMsg('Scan a location label first (LOC-…)'); setScan(''); return; }
    const p = api.resolvePartScan(code); if (!p) { setMsg(`No part matches ${code}`); setScan(''); return; }
    setActive(p.id); setMsg(null); setScan(''); setQty(''); setTimeout(() => qtyRef.current?.focus(), 0);
  };
  const commitQty = () => { if (!active) return; const n = Number(qty); if (!Number.isFinite(n)) return; setCounted((c) => ({ ...c, [active]: (c[active] ?? 0) + n })); setSkipped((s) => s.filter((x) => x !== active)); setActive(null); setQty(''); scanRef.current?.focus(); };
  const confirm = async () => { if (!count) return; try { const c = await api.postCycleCountV2(count.id, counted, skipped); setPosted(c); setCount(null); setLoc(null); } catch (e) { setMsg(e instanceof Error ? e.message : 'Failed'); } };
  const partOf = (id: string) => api.resolvePartScan(id);
  const lines = count ? [...count.lines.map((l) => l.partId), ...Object.keys(counted).filter((k) => !count.lines.some((l) => l.partId === k))] : [];
  const uncounted = lines.filter((id) => counted[id] === undefined && !skipped.includes(id));
  return <div data-testid="cycle-count-page" className="space-y-4">
    <div data-testid="cc-header" className={`flex flex-wrap items-center gap-4 rounded-md border p-4 ${loc ? 'border-ink bg-ink text-white' : 'border-line bg-surface'}`}>
      {loc ? <><Lock size={22} /><div><div className="text-[10px] uppercase tracking-wide opacity-70">Locked location</div><div data-testid="cc-locked-location" className="text-2xl font-semibold">{loc.name} <span className="font-mono text-base opacity-70">{api.locationBarcode(loc)}</span></div></div><Button data-testid="cc-unlock" className="ml-auto !border-white/30 !bg-transparent !text-white" onClick={() => { setLoc(null); setCount(null); }}><Unlock size={13} /> Unlock</Button></>
        : <><ScanLine size={22} className="text-ink-400" /><div><div className="text-sm font-semibold text-ink">Cycle count</div><div className="text-xs text-ink-500">Scan a location label (LOC-A1 …) or tap one below to lock it. Every scan after that belongs to it.</div></div></>}
    </div>
    <form className="flex gap-2" onSubmit={(e) => { e.preventDefault(); onScan(scan); }}><input ref={scanRef} autoFocus data-testid="cc-scan" value={scan} onChange={(e) => setScan(e.target.value)} placeholder={loc ? 'Scan part barcode (part # / alias)' : 'Scan location label LOC-…'} className="h-10 flex-1 rounded-sm border border-line bg-canvas px-3 font-mono text-sm" /><Button data-testid="cc-scan-go" type="submit">Enter</Button></form>
    {switchTo && <div data-testid="cc-switch-prompt" className="flex items-center gap-2 rounded-sm border border-amber-200 bg-amber-50 px-3 py-2 text-xs">Switch to <b>{switchTo.name}</b>? Current count will be abandoned. <Button size="sm" data-testid="cc-switch-yes" onClick={() => void lock(switchTo)}>Switch</Button><Button size="sm" data-testid="cc-switch-no" onClick={() => setSwitchTo(null)}>Stay</Button></div>}
    {msg && <p data-testid="cc-message" className="text-xs text-rose-700">{msg}</p>}
    {active && <form className="flex items-center gap-2 rounded-sm border border-ink bg-canvas p-3" onSubmit={(e) => { e.preventDefault(); commitQty(); }}><span className="font-mono text-sm font-semibold">{partOf(active)?.partNumber}</span><span className="text-xs text-ink-500">{partOf(active)?.name} · on file {count?.lines.find((l) => l.partId === active)?.expected ?? 0}{counted[active] !== undefined && ` · counted so far ${counted[active]} (adds)`}</span><input ref={qtyRef} data-testid="cc-qty" value={qty} onChange={(e) => setQty(e.target.value)} inputMode="numeric" placeholder="actual" className="ml-auto h-9 w-24 rounded-sm border border-line bg-surface px-2 text-right font-mono" /><Button data-testid="cc-qty-enter" type="submit" variant="primary">Enter</Button></form>}
    {count && <Card title={`${count.number} · ${lines.length} parts on file`} subtitle={`${Object.keys(counted).length} counted · ${lines.filter((id) => counted[id] !== undefined && counted[id] !== (count.lines.find((l) => l.partId === id)?.expected ?? 0)).length} variances · ${uncounted.length} uncounted`} testId="cc-lines" bodyClassName="p-0">
      <ul className="divide-y divide-line text-xs">{lines.map((id) => { const exp = count.lines.find((l) => l.partId === id)?.expected ?? 0; const c = counted[id]; const d = c === undefined ? null : c - exp; return <li key={id} data-testid={`cc-line-${id}`} data-variance={d ?? ''} className="flex items-center gap-3 px-3 py-2"><span className="w-28 font-mono font-semibold">{partOf(id)?.partNumber}</span><span className="flex-1 text-ink-600">{partOf(id)?.name}</span><span className="font-mono text-ink-500">on file {exp}</span>{c !== undefined ? <span className={`w-28 text-right font-mono font-semibold ${tone(d!)}`}>{c} ({d! > 0 ? '+' : ''}{d})</span> : skipped.includes(id) ? <span className="w-28 text-right text-ink-400">skipped</span> : <span className="flex w-28 justify-end gap-1"><button data-testid={`cc-zero-${id}`} onClick={() => setCounted((x) => ({ ...x, [id]: 0 }))} className="rounded-sm border border-line px-1.5 py-0.5 hover:bg-canvas">zero</button><button data-testid={`cc-skip-${id}`} onClick={() => setSkipped((s) => [...s, id])} className="rounded-sm border border-line px-1.5 py-0.5 hover:bg-canvas">skip</button></span>}</li>; })}</ul>
      <div className="flex items-center justify-end gap-2 border-t border-line p-3"><span className="text-xs text-ink-500">Confirm writes append-only adjustment movements ({user?.shortName}) and stamps "last counted".</span><Button data-testid="cc-confirm" variant="primary" disabled={uncounted.length > 0} title={uncounted.length ? 'Zero or skip every uncounted part first' : undefined} onClick={() => void confirm()}>Confirm count</Button></div>
    </Card>}
    {posted && <div data-testid="cc-posted" className="rounded-sm border border-moss-200 bg-moss-50 px-3 py-2 text-xs text-moss-800">{posted.number} posted · {posted.variances} variance(s) · last-counted stamped.</div>}
    <Card title="Count next" subtitle={`Locations cycle so everything is counted monthly · amber = not counted in ${api.CYCLE_STALE_DAYS} days`} testId="cc-queue" bodyClassName="p-0">
      <ul className="divide-y divide-line text-xs">{queue.map((q) => <li key={q.location.id} data-testid={`cc-queue-${q.location.id}`} data-overdue={q.overdue} className="flex items-center gap-3 px-3 py-2"><span className="font-mono text-ink-500">{q.barcode}</span><span className="font-medium text-ink">{q.location.name}</span><span className="text-ink-500">{q.parts} parts</span><span className={`ml-auto ${q.overdue ? 'font-semibold text-amber-700' : 'text-ink-500'}`}>{q.lastCounted ? `counted ${fmtDate(q.lastCounted)} · ${q.daysSince}d` : 'never counted'}</span><Button size="sm" data-testid={`cc-lock-${q.location.id}`} onClick={() => void lock(q.location)}><Lock size={11} /> Lock</Button></li>)}</ul>
    </Card>
    {report && <Card title="Variance report" subtitle={`Manager only · net ${report.totals.dollars < 0 ? '−' : '+'}${fmtMoneyCents(Math.abs(report.totals.dollars))} · shrink ${fmtMoneyCents(Math.abs(report.totals.shrink))} · overage ${fmtMoneyCents(report.totals.overage)}`} testId="cc-variance-report" action={<Button size="sm" data-testid="cc-variance-export" onClick={() => { const csv = ['count,date,by,location,part,expected,counted,qty_var,unit_cost,dollar_var', ...report.rows.map((r) => [r.countNumber, r.at.slice(0, 10), r.by, r.location, r.partNumber, r.expected, r.counted, r.qtyVariance, r.unitCost, r.dollarVariance].join(','))].join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'variance-report.csv'; a.click(); }}>Export CSV</Button>} bodyClassName="p-0">
      <table className="w-full text-xs"><thead><tr className="text-left text-[10px] uppercase text-ink-400"><th className="px-3 py-1">Count</th><th>Location</th><th>Part</th><th className="text-right">On file</th><th className="text-right">Actual</th><th className="text-right">Qty</th><th className="text-right">Unit</th><th className="px-3 text-right">$ var</th></tr></thead><tbody>{report.rows.map((r, i) => <tr key={i} data-testid={`cc-var-${r.countId}-${r.partId}`} className="border-t border-line"><td className="px-3 py-1 font-mono">{r.countNumber}</td><td>{r.location}</td><td className="font-mono">{r.partNumber}</td><td className="text-right font-mono">{r.expected}</td><td className="text-right font-mono">{r.counted}</td><td className={`text-right font-mono ${tone(r.qtyVariance)}`}>{r.qtyVariance > 0 ? '+' : ''}{r.qtyVariance}</td><td className="text-right font-mono">{fmtMoneyCents(r.unitCost)}</td><td className={`px-3 text-right font-mono font-semibold ${r.dollarVariance < 0 ? 'text-rose-700' : 'text-moss-700'}`}>{r.dollarVariance < 0 ? '−' : '+'}{fmtMoneyCents(Math.abs(r.dollarVariance))}</td></tr>)}{!report.rows.length && <tr><td colSpan={8} className="px-3 py-3 text-center text-ink-500">No variances posted yet.</td></tr>}</tbody></table>
    </Card>}
  </div>;
}
