import { Check, Download, Play, SkipForward } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import * as ir from '@/api/inventoryReports';
import type { AdjustmentRow, ReportRun } from '@/api/inventoryReports';
import { useAuth } from '@/auth/AuthContext';
import { field, Head, Tabs } from '@/components/rs/RsBits';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { EmptyRow, Table, Td, Th } from '@/components/ui/Table';
import { fmtDate, fmtMoney } from '@/lib/format';

type Tab = 'adjust' | 'optimize' | 'history' | 'trend';
const money = (n: number) => <span className={n < 0 ? 'text-moss-700' : n > 0 ? 'text-rose-700' : ''}>{n < 0 ? '−' : ''}{fmtMoney(Math.abs(n))}</span>;
const PartCell = ({ r }: { r: { part: { id: string; partNumber: string; name: string } } }) => <Td><Link to={`/inventory?part=${r.part.id}`} data-testid={`part-link-${r.part.id}`} className="font-mono text-xs font-semibold hover:underline">{r.part.partNumber}</Link><div className="max-w-[220px] truncate text-[11px] text-ink-500">{r.part.name}</div></Td>;

// Inventory → Reports (manager tier, dollars visible): consumption adjustment (recalibrates min / order-up-to) + spending optimization
export default function InventoryReportsPage() {
  ir.ensureSeed(); const { user } = useAuth(); const manager = user?.accessTier === 'manager';
  const [tab, setTab] = useState<Tab>('adjust'); const [tick, setTick] = useState(0); const bump = () => setTick((t) => t + 1);
  const [run, setRun] = useState<ReportRun | null>(ir.latestRun()); const [minUnits, setMinUnits] = useState(0); const [minDollars, setMinDollars] = useState(0); const [vendor, setVendor] = useState(''); const [dept, setDept] = useState(''); const [edit, setEdit] = useState<Record<string, { min: number; orderUpTo: number }>>({});
  const [s, setS] = useState({ ...ir.settings });
  useEffect(() => { setRun(ir.latestRun()); }, [tick]);
  const rows = useMemo(() => (run?.rows ?? []).filter((r) => (Math.abs(r.deltaMin) >= minUnits || Math.abs(r.deltaUpTo) >= minUnits) && Math.abs(r.dollarImpact) >= minDollars && (!vendor || r.vendorName === vendor) && (!dept || r.part.category === dept)), [run, minUnits, minDollars, vendor, dept]);
  const vendors = Array.from(new Set((run?.rows ?? []).map((r) => r.vendorName))); const depts = Array.from(new Set((run?.rows ?? []).map((r) => r.part.category)));
  const opt = useMemo(() => ir.optimization(), [tick]); // eslint-disable-line react-hooks/exhaustive-deps
  if (!manager) return <div data-testid="inventory-reports-denied" className="rounded-md border border-line bg-surface p-6 text-sm text-ink-500">Manager tier only — dollars are visible on this page.</div>;
  const saveSettings = () => { ir.updateSettings({ reviewDays: s.reviewDays, cadenceDays: s.cadenceDays, overstockMonths: s.overstockMonths, deadDays: s.deadDays }); bump(); };
  const download = () => { const blob = new Blob([ir.optimizationCsv()], { type: 'text/csv' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = `spending-optimization-${new Date().toISOString().slice(0, 10)}.csv`; a.click(); };
  return <div data-testid="inventory-reports-page" data-tick={tick} className="space-y-4">
    <Head title="Inventory · Reports" sub={<>Consumption adjustment recalibrates min triggers and order-up-to from pick scans + parts requests (never invoices) and PO lead times · Spending optimization finds tied-up dollars · <Link to="/inventory" className="text-brand hover:underline">Inventory</Link></>} />
    <div className="flex flex-wrap items-end gap-2 rounded-md border border-line bg-surface px-3 py-2 text-xs" data-testid="report-settings">
      <label className="text-ink-500">Review period (days)<input data-testid="setting-review-days" type="number" value={s.reviewDays} onChange={(e) => setS({ ...s, reviewDays: Number(e.target.value) })} className={`${field} ml-1 w-16`} /></label>
      <label className="text-ink-500">Cadence (days)<input data-testid="setting-cadence-days" type="number" value={s.cadenceDays} onChange={(e) => setS({ ...s, cadenceDays: Number(e.target.value) })} className={`${field} ml-1 w-16`} /></label>
      <label className="text-ink-500">Over-stock (months)<input data-testid="setting-overstock-months" type="number" value={s.overstockMonths} onChange={(e) => setS({ ...s, overstockMonths: Number(e.target.value) })} className={`${field} ml-1 w-14`} /></label>
      <label className="text-ink-500">Dead stock (days)<input data-testid="setting-dead-days" type="number" value={s.deadDays} onChange={(e) => setS({ ...s, deadDays: Number(e.target.value) })} className={`${field} ml-1 w-16`} /></label>
      <Button size="sm" data-testid="settings-save" onClick={saveSettings}>Save setup values</Button>
      <span className="ml-auto text-ink-400" data-testid="next-due">Next review due {fmtDate(ir.nextDue().toISOString())} · last run {run ? `${fmtDate(run.at)} by ${run.by}` : 'never'}</span>
      <Button variant="primary" size="sm" data-testid="run-report" onClick={() => { setRun(ir.runReport()); bump(); }}><Play size={12} /> Run consumption adjustment</Button>
    </div>
    <Tabs prefix="invrep" active={tab} onChange={(v) => setTab(v as Tab)} tabs={[{ key: 'adjust', label: `Consumption adjustment${run ? ` · ${run.rows.length}` : ''}` }, { key: 'optimize', label: 'Spending optimization' }, { key: 'history', label: `Run history · ${ir.runHistory().length}` }, { key: 'trend', label: 'Monthly snapshot' }]} />
    {tab === 'adjust' && <Card title="Suggested min / order-up-to changes" subtitle={run ? `Run ${run.id} · ${run.rows.length} parts · ${run.approvedCount} approved · ${run.skippedCount} skipped · demand = max(historical, pipeline) — pipeline column goes live with M3KE ref kits` : 'No run yet — tap Run consumption adjustment'} bodyClassName="p-0" testId="adjust-card"
      action={run ? <span className="flex flex-wrap items-center gap-1.5 text-xs"><label className="text-ink-500">Δ ≥<input data-testid="filter-units" type="number" value={minUnits} onChange={(e) => setMinUnits(Number(e.target.value))} className={`${field} ml-1 w-12`} /> units</label><label className="text-ink-500">$ ≥<input data-testid="filter-dollars" type="number" value={minDollars} onChange={(e) => setMinDollars(Number(e.target.value))} className={`${field} ml-1 w-16`} /></label><select data-testid="filter-vendor" value={vendor} onChange={(e) => setVendor(e.target.value)} className={field}><option value="">all vendors</option>{vendors.map((v) => <option key={v}>{v}</option>)}</select><select data-testid="filter-dept" value={dept} onChange={(e) => setDept(e.target.value)} className={field}><option value="">all departments</option>{depts.map((v) => <option key={v}>{v}</option>)}</select><Button variant="primary" size="sm" data-testid="approve-all" disabled={!rows.some((r) => r.status === 'open')} onClick={() => { ir.approveAll(run.id); bump(); }}><Check size={12} /> Approve all ({rows.filter((r) => r.status === 'open').length})</Button></span> : undefined}>
      <Table><thead><tr><Th>Part</Th><Th>Vendor</Th><Th className="text-right">Usage/wk</Th><Th className="text-right">Pipeline/wk</Th><Th className="text-right">Lead (med · p90)</Th><Th className="text-right">Current min / up-to</Th><Th className="text-right">Suggested min / up-to</Th><Th className="text-right">Δ</Th><Th>Reason</Th><Th className="text-right">Stockouts 90d</Th><Th className="text-right">$ impact</Th><Th /></tr></thead>
        <tbody>{rows.map((r) => <AdjustRow key={r.id} r={r} run={run!} edit={edit[r.id]} setEdit={(v) => setEdit({ ...edit, [r.id]: v })} bump={bump} />)}{!rows.length && <EmptyRow colSpan={12} text={run ? 'Nothing matches the filters' : 'Run the report to see suggestions'} />}</tbody></Table>
    </Card>}
    {tab === 'optimize' && <div className="space-y-4" data-testid="optimization">
      <div className="grid grid-cols-4 gap-3" data-testid="opt-totals">{([['Over-stocked', opt.totals.overstock, 'tied up'], ['Dead stock', opt.totals.dead, 'on hand, no movement'], ['Over-ordered', opt.totals.overOrdered, 'beyond the cap'], ['Price drift', opt.totals.drift, 'overpaid last 90d']] as [string, number, string][]).map(([l, v, sub]) => <div key={l} data-testid={`opt-total-${l.toLowerCase().replace(/[^a-z]+/g, '-')}`} className="rounded-md border border-line bg-surface px-3 py-2"><div className="text-[10px] uppercase tracking-wide text-ink-400">{l}</div><div className="text-lg font-semibold tabular text-ink">{fmtMoney(v)}</div><div className="text-[10px] text-ink-400">{sub}</div></div>)}<div className="col-span-4 flex justify-end"><Button size="sm" data-testid="opt-csv" onClick={download}><Download size={12} /> CSV export</Button></div></div>
      <Card title={`Over-stocked · ${opt.overstock.length}`} subtitle={`On hand > ${ir.settings.overstockMonths} months of usage`} bodyClassName="p-0" testId="opt-overstock"><Table><thead><tr><Th>Part</Th><Th className="text-right">On hand</Th><Th className="text-right">Usage/mo</Th><Th className="text-right">Months cover</Th><Th className="text-right">$ tied up</Th><Th className="text-right">Order-up-to</Th></tr></thead><tbody>{opt.overstock.map((r) => <tr key={r.part.id} data-testid={`overstock-${r.part.id}`}><PartCell r={r} /><Td className="text-right tabular">{r.onHand}</Td><Td className="text-right tabular">{r.perMonth}</Td><Td className="text-right tabular">{r.monthsCover}</Td><Td className="text-right tabular">{fmtMoney(r.dollars)}</Td><Td className="text-right text-xs">{r.currentUpTo} → <button type="button" data-testid={`overstock-adjust-${r.part.id}`} onClick={() => setTab('adjust')} className="font-semibold text-brand hover:underline">{r.suggestedUpTo}</button></Td></tr>)}{!opt.overstock.length && <EmptyRow colSpan={6} text="Nothing over-stocked" />}</tbody></Table></Card>
      <Card title={`Dead stock · ${opt.dead.length}`} subtitle={`No movement in ${ir.settings.deadDays} days`} bodyClassName="p-0" testId="opt-dead"><Table><thead><tr><Th>Part</Th><Th className="text-right">On hand</Th><Th className="text-right">$ on hand</Th><Th>Last used</Th><Th>Last bought</Th></tr></thead><tbody>{opt.dead.map((r) => <tr key={r.part.id} data-testid={`dead-${r.part.id}`}><PartCell r={r} /><Td className="text-right tabular">{r.onHand}</Td><Td className="text-right tabular">{fmtMoney(r.dollars)}</Td><Td className="text-xs">{r.lastUsed ? fmtDate(r.lastUsed) : 'never'}</Td><Td className="text-xs">{r.lastBought ? fmtDate(r.lastBought) : '—'}</Td></tr>)}{!opt.dead.length && <EmptyRow colSpan={5} text="No dead stock" />}</tbody></Table></Card>
      <Card title={`Over-ordered · ${opt.overOrdered.length}`} subtitle="PO qty exceeded order-up-to − on hand − on order at the time" bodyClassName="p-0" testId="opt-overordered"><Table><thead><tr><Th>PO</Th><Th>Part</Th><Th>Vendor</Th><Th>Sent by</Th><Th className="text-right">Qty / cap</Th><Th className="text-right">Excess</Th><Th className="text-right">$</Th></tr></thead><tbody>{opt.overOrdered.map((r) => <tr key={`${r.poNumber}-${r.part.id}`} data-testid={`overordered-${r.poNumber}`}><Td className="font-mono text-xs">{r.poNumber} <span className="text-ink-400">{fmtDate(r.at)}</span></Td><PartCell r={r} /><Td className="text-xs">{r.vendorName}</Td><Td className="text-xs">{r.sentBy}</Td><Td className="text-right tabular text-xs">{r.qty} / {r.cap}</Td><Td className="text-right tabular text-rose-700">+{r.excess}</Td><Td className="text-right tabular">{fmtMoney(r.dollars)}</Td></tr>)}{!opt.overOrdered.length && <EmptyRow colSpan={7} text="No over-orders" />}</tbody></Table></Card>
      <Card title={`Price drift · ${opt.drift.length}`} subtitle="Last price >10% over the 12-month average, or another vendor materially lower" bodyClassName="p-0" testId="opt-drift"><Table><thead><tr><Th>Part</Th><Th>Vendor</Th><Th className="text-right">Last</Th><Th className="text-right">12-mo avg</Th><Th className="text-right">Drift</Th><Th className="text-right">$ overpaid 90d</Th><Th>Suggested</Th></tr></thead><tbody>{opt.drift.map((r) => <tr key={r.part.id} data-testid={`drift-${r.part.id}`}><PartCell r={r} /><Td className="text-xs">{r.vendorName}</Td><Td className="text-right tabular">{fmtMoney(r.lastPrice)}</Td><Td className="text-right tabular">{fmtMoney(r.avg12m)}</Td><Td className={`text-right tabular ${r.driftPct > 10 ? 'text-rose-700' : ''}`}>{r.driftPct > 0 ? '+' : ''}{r.driftPct}%</Td><Td className="text-right tabular">{fmtMoney(r.overpaid90)}</Td><Td className="text-xs">{r.cheaperVendor ? <span data-testid={`drift-switch-${r.part.id}`} className="text-moss-700">switch → {r.cheaperVendor.name} @ {fmtMoney(r.cheaperVendor.price)}</span> : 'renegotiate / requote'}</Td></tr>)}{!opt.drift.length && <EmptyRow colSpan={7} text="No price drift" />}</tbody></Table></Card>
      <Card title={`Duplicate orders · ${opt.duplicates.length}`} subtitle="Same part on two open POs to different vendors" bodyClassName="p-0" testId="opt-duplicates"><Table><thead><tr><Th>Part</Th><Th>Open POs</Th></tr></thead><tbody>{opt.duplicates.map((r) => <tr key={r.part.id} data-testid={`duplicate-${r.part.id}`}><PartCell r={r} /><Td className="text-xs">{r.pos.map((p) => <span key={p.number} className="mr-2 font-mono">{p.number} · {p.vendorName} ×{p.qty}</span>)} <Link to="/purchasing" className="text-brand hover:underline">Purchasing</Link></Td></tr>)}{!opt.duplicates.length && <EmptyRow colSpan={2} text="No duplicates" />}</tbody></Table></Card>
    </div>}
    {tab === 'history' && <Card title="Run history" bodyClassName="p-0" testId="run-history"><Table><thead><tr><Th>Run</Th><Th>When</Th><Th>By</Th><Th className="text-right">Suggested</Th><Th className="text-right">Approved</Th><Th className="text-right">Skipped</Th><Th className="text-right">$ impact approved</Th></tr></thead><tbody>{ir.runHistory().map((h) => <tr key={h.id} data-testid={`run-${h.id}`}><Td className="font-mono text-xs">{h.id}</Td><Td className="text-xs">{fmtDate(h.at)}</Td><Td className="text-xs">{h.by}</Td><Td className="text-right tabular">{h.rows.length}</Td><Td className="text-right tabular">{h.approvedCount}</Td><Td className="text-right tabular">{h.skippedCount}</Td><Td className="text-right tabular">{money(h.rows.filter((r) => r.status === 'approved').reduce((t, r) => t + r.dollarImpact, 0))}</Td></tr>)}{!ir.runHistory().length && <EmptyRow colSpan={7} text="No runs yet" />}</tbody></Table></Card>}
    {tab === 'trend' && <Card title="Monthly snapshot · trends" subtitle="Spending optimization totals by month (seeded history + live month)" bodyClassName="p-0" testId="snapshot-card"><Table><thead><tr><Th>Month</Th><Th className="text-right">Over-stocked</Th><Th className="text-right">Dead</Th><Th className="text-right">Over-ordered</Th><Th className="text-right">Price drift</Th></tr></thead><tbody>{ir.snapshotTrend().map((m) => <tr key={m.month} data-testid={`snapshot-${m.month.replace(/[^A-Za-z0-9]+/g, '-')}`}><Td className="text-xs font-medium">{m.month}</Td><Td className="text-right tabular">{fmtMoney(m.overstock)}</Td><Td className="text-right tabular">{fmtMoney(m.dead)}</Td><Td className="text-right tabular">{fmtMoney(m.overOrdered)}</Td><Td className="text-right tabular">{fmtMoney(m.drift)}</Td></tr>)}</tbody></Table></Card>}
  </div>;
}

const AdjustRow = ({ r, run, edit, setEdit, bump }: { r: AdjustmentRow; run: ReportRun; edit?: { min: number; orderUpTo: number }; setEdit: (v: { min: number; orderUpTo: number }) => void; bump: () => void }) => <tr data-testid={`adjust-${r.partId}`} data-status={r.status} className={r.status !== 'open' ? 'opacity-60' : ''}>
  <PartCell r={r} /><Td className="text-xs">{r.vendorName}</Td>
  <Td className="text-right tabular text-xs">{r.usagePerWeek} <span className="text-ink-400">(12m {r.usage12m})</span></Td><Td className="text-right tabular text-xs text-ink-400" title="M3KE ref kits × open jobs — live when kits exist">{r.pipelinePerWeek || '—'}</Td><Td className="text-right tabular text-xs">{r.leadMedian}d · {r.leadP90}d</Td>
  <Td className="text-right tabular text-xs">{r.currentMin} / {r.currentUpTo}</Td>
  <Td className="text-right tabular text-xs font-semibold">{r.status === 'open' ? <span className="inline-flex items-center gap-1"><input data-testid={`edit-min-${r.partId}`} type="number" value={edit?.min ?? r.suggestedMin} onChange={(e) => setEdit({ min: Number(e.target.value), orderUpTo: edit?.orderUpTo ?? r.suggestedUpTo })} className={`${field} w-14 text-right`} /> / <input data-testid={`edit-upto-${r.partId}`} type="number" value={edit?.orderUpTo ?? r.suggestedUpTo} onChange={(e) => setEdit({ min: edit?.min ?? r.suggestedMin, orderUpTo: Number(e.target.value) })} className={`${field} w-14 text-right`} /></span> : `${r.appliedMin ?? r.suggestedMin} / ${r.appliedUpTo ?? r.suggestedUpTo}`}</Td>
  <Td className="text-right tabular text-xs"><span className={r.deltaMin > 0 ? 'text-rose-700' : r.deltaMin < 0 ? 'text-moss-700' : ''}>{r.deltaMin > 0 ? '+' : ''}{r.deltaMin}</span> / <span className={r.deltaUpTo > 0 ? 'text-rose-700' : r.deltaUpTo < 0 ? 'text-moss-700' : ''}>{r.deltaUpTo > 0 ? '+' : ''}{r.deltaUpTo}</span></Td>
  <Td className="text-xs text-ink-600" data-testid={`reason-${r.partId}`}>{r.reason}</Td><Td className={`text-right tabular text-xs ${r.stockouts90 ? 'font-semibold text-rose-700' : ''}`}>{r.stockouts90}</Td><Td className="text-right tabular text-xs">{money(r.dollarImpact)}</Td>
  <Td className="text-right">{r.status === 'open' ? <span className="inline-flex gap-1"><Button size="sm" variant="primary" data-testid={`approve-${r.partId}`} onClick={() => { ir.approveRow(run.id, r.id, edit && (edit.min !== r.suggestedMin || edit.orderUpTo !== r.suggestedUpTo) ? edit : undefined); bump(); }}><Check size={11} /> {edit && (edit.min !== r.suggestedMin || edit.orderUpTo !== r.suggestedUpTo) ? 'Approve edited' : 'Approve'}</Button><Button size="sm" data-testid={`skip-${r.partId}`} onClick={() => { ir.skipRow(run.id, r.id); bump(); }}><SkipForward size={11} /></Button></span> : <span data-testid={`status-${r.partId}`} className="text-[10px] uppercase text-ink-400">{r.status}</span>}</Td>
</tr>;
