import { Camera, Check, Microscope, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useCamera } from '@/hooks/useCamera';

// Inspection camera sequence — reuses the shared useCamera hook (same capture pipeline as PhotoCapture / CameraCapture). 2 shots on the IPEVO, then the microscope. SPACEBAR fires the shutter in both modes.
export const InspectionCameraFlow = ({ onShot, onDone, onClose }: { onShot: (p: { source: 'ipevo' | 'microscope'; dataUrl: string }) => Promise<unknown>; onDone: () => void; onClose: () => void }) => {
  const [step, setStep] = useState(0); const { videoRef, status, capture } = useCamera(true); const [flash, setFlash] = useState(false); const [shots, setShots] = useState<string[]>([]);
  const source: 'ipevo' | 'microscope' = step < 2 ? 'ipevo' : 'microscope';
  const snap = async () => { const s = capture(); const dataUrl = s.dataUrl || placeholder(source, step); setFlash(true); setTimeout(() => setFlash(false), 200); await onShot({ source, dataUrl }); setShots((x) => [...x, dataUrl]); setStep((x) => x + 1); };
  useEffect(() => { const h = (e: KeyboardEvent) => { if (e.code === 'Space') { e.preventDefault(); if (step < 3) void snap(); else onDone(); } }; window.addEventListener('keydown', h); return () => window.removeEventListener('keydown', h); }); // eslint-disable-line react-hooks/exhaustive-deps
  return <div data-testid="inspection-camera" data-step={step} className="fixed inset-0 z-[85] flex flex-col bg-black/90 text-white">
    <div className="flex items-center gap-3 px-5 py-3"><span className="text-sm font-semibold">{step < 2 ? <><Camera size={16} className="mr-1 inline" /> IPEVO · shot {step + 1} of 2</> : step === 2 ? <><Microscope size={16} className="mr-1 inline" /> Microscope · shot 1 of 1</> : <><Check size={16} className="mr-1 inline text-emerald-400" /> Sequence complete</>}</span><span className="text-xs text-white/60">{status === 'ready' ? 'camera live' : status === 'denied' || status === 'unavailable' ? 'no camera — spacebar drops a placeholder frame' : 'starting camera…'}</span><span className="ml-auto rounded bg-white/10 px-2 py-0.5 font-mono text-xs">SPACE = shutter</span><button data-testid="inspection-camera-close" onClick={onClose} className="rounded-full bg-white/10 p-1.5"><X size={16} /></button></div>
    <div className="relative mx-auto flex w-full max-w-3xl flex-1 items-center justify-center px-5"><video ref={videoRef} autoPlay playsInline muted className={`max-h-[60vh] w-full rounded-xl bg-black object-cover ${step === 2 ? 'ring-4 ring-cyan-400/60' : ''}`} />{flash && <div className="absolute inset-0 rounded-xl bg-white/80" />}</div>
    <div className="flex items-center justify-center gap-3 px-5 py-4"><div className="flex gap-2">{shots.map((s, i) => <img key={i} src={s} alt="" className="h-14 w-20 rounded object-cover ring-1 ring-white/20" />)}</div>{step < 3 ? <button data-testid="inspection-camera-shutter" onClick={() => void snap()} className="ml-4 h-16 w-16 rounded-full border-4 border-white bg-white/20" aria-label="Shutter" /> : <button data-testid="inspection-camera-done" onClick={onDone} className="ml-4 rounded-full bg-emerald-500 px-6 py-3 font-semibold text-black">Continue to inspection form</button>}</div>
  </div>;
};
const placeholder = (source: string, n: number) => { const c = document.createElement('canvas'); c.width = 320; c.height = 200; const g = c.getContext('2d')!; g.fillStyle = source === 'ipevo' ? '#1f2630' : '#0e3b4a'; g.fillRect(0, 0, 320, 200); g.fillStyle = '#fff'; g.font = '16px sans-serif'; g.fillText(`${source.toUpperCase()} · shot ${n + 1} (no camera)`, 20, 100); return c.toDataURL('image/jpeg', 0.6); };
