import * as api from '@/api/client';
import type { InspComponentEntry, InspectionForm } from '@/api/client';
import { fmtDate, fmtMoney } from '@/lib/format';

const condLabel = (k?: string) => api.CONDITIONS.find((c) => c.key === k)?.label ?? '—';
const authLabel = (k?: string) => api.AUTHENTICITY.find((a) => a.key === k)?.label;
const compTotal = (c: InspComponentEntry) => (c.price || 0) + (c.caseRestorationPrice || 0) + (c.weldingPrice || 0) + (c.polishUpYesNo ? c.polishUpPrice || 0 : 0);

// Client-facing "ROLLIWORKS — Inspection Notes" report. Rendered live in the form preview and served at /rc/inspection/:token. Print CSS via .print-area.
export const InspectionReportView = ({ f, testId = 'inspection-report' }: { f: InspectionForm; testId?: string }) => {
  const yesNo = [...f.components.filter((c) => c.yesNo).map((c) => ({ label: `${c.component}: ${c.otherNote || api.inspectionNoteLibrary(c.component)[c.notes[0]] || 'recommended work'}`, price: compTotal(c) })), ...f.bracelet.filter((l) => l.yesNo || l.rec === 'rec' || (l.mode === 'scale' && l.include)).map((l) => ({ label: l.label, price: l.mode === 'qty_price' ? (l.qty || 0) * (l.price || 0) : l.mode === 'hours_rate' ? (l.hours || 0) * (l.rate || 0) : 0 })), ...(f.overall.yesNo ? [{ label: f.overall.quickTags[0] || 'Overall service', price: f.overall.price }] : [])];
  return <div data-testid={testId} className="print-area rounded-md border border-line bg-white p-6 text-[13px] text-black">
    <div className="print-header flex items-end justify-between border-b-2 border-black pb-3"><div><div className="text-2xl font-bold tracking-tight">ROLLIWORKS</div><div className="text-sm uppercase tracking-widest text-gray-600">Inspection Notes</div></div><div className="text-right text-xs text-gray-600"><div>{f.savedAt ? fmtDate(f.savedAt) : fmtDate(f.createdAt)}</div><div className="font-mono">{f.token}</div></div></div>
    <div className="mt-4 grid grid-cols-2 gap-4">
      <div className="rounded border border-gray-300 p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-gray-500">Customer</div><div className="mt-1 font-semibold" data-testid={`${testId}-customer`}>{f.customer.name || '—'}</div><div className="text-xs text-gray-600">{[f.customer.email, f.customer.phone].filter(Boolean).join(' · ')}</div></div>
      <div className="rounded border border-gray-300 p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-gray-500">Watch details</div><div className="mt-1 font-semibold">{f.brand} {f.model}</div><div className="text-xs text-gray-600">Ref {f.reference || '—'} · Estimate {f.estimateNumber || '—'} · Target {f.targetTo ? `${fmtDate(f.targetTo)} (${f.targetWeeks} weeks)` : `${f.targetWeeks} weeks`} · {f.inspectionType} · {f.deptTags.join(' / ')}</div></div>
    </div>
    <table className="mt-4 w-full"><thead><tr className="text-left text-[10px] uppercase tracking-wide text-gray-500"><th className="py-1">Component</th><th>Condition</th><th>Findings</th><th className="text-right">Price</th></tr></thead>
      <tbody>{f.components.filter((c) => c.condition || c.notes.length || c.otherNote || c.extraNotes.length).map((c) => <tr key={c.component} data-testid={`${testId}-row-${c.component.toLowerCase()}`} className="border-t border-gray-200 align-top"><td className="py-1.5 font-semibold">{c.component}{c.waiver && <span className="ml-1 rounded bg-amber-100 px-1 text-[9px] font-bold uppercase text-amber-900">waiver</span>}</td><td className="py-1.5">{condLabel(c.condition)}{authLabel(c.authenticity) && c.authenticity !== 'genuine' && <div className="text-[10px] text-rose-700">{authLabel(c.authenticity)}</div>}</td><td className="py-1.5 text-gray-800"><ul className="list-disc pl-4">{c.notes.map((n) => <li key={n}>{api.inspectionNoteLibrary(c.component)[n]}</li>)}{c.otherNote && <li>{c.otherNote}</li>}{c.extraNotes.map((n, i) => <li key={`x${i}`}>{n}</li>)}{c.dialVariants?.length ? <li>Dial variant: {c.dialVariants.join(', ')}</li> : null}{c.component === 'Case' && c.retailPolish && <li>Retail polish recommended</li>}{c.component === 'Crystal' && c.polishUpYesNo && <li>Polish up {fmtMoney(c.polishUpPrice || 0)} — Yes/No?</li>}</ul></td><td className="py-1.5 text-right font-mono">{compTotal(c) ? fmtMoney(compTotal(c)) : ''}</td></tr>)}</tbody></table>
    {f.bracelet.some((l) => (l.qty || 0) > 0 || (l.hours || 0) > 0 || (l.mode === 'scale' && l.include)) && <div className="mt-4"><div className="text-[10px] font-semibold uppercase tracking-wide text-gray-500">Bracelet repair options</div><ul className="mt-1 divide-y divide-gray-200">{f.bracelet.filter((l) => (l.qty || 0) > 0 || (l.hours || 0) > 0 || (l.mode === 'scale' && l.include)).map((l) => <li key={l.key} className="flex justify-between py-1"><span>{l.label}{l.mode === 'scale' ? ` · ${l.scale}/10` : l.mode === 'hours_rate' ? ` · ${l.hours} h @ ${fmtMoney(l.rate || 0)}/h${l.rec ? ` · ${l.rec === 'rec' ? 'recommended' : 'not recommended'}` : ''}` : ` · ${l.qty} × ${fmtMoney(l.price || 0)}`}{l.note && <span className="text-xs text-gray-500"> — {l.note}</span>}</span><span className="font-mono">{l.mode === 'scale' ? '' : fmtMoney(l.mode === 'qty_price' ? (l.qty || 0) * (l.price || 0) : (l.hours || 0) * (l.rate || 0))}</span></li>)}</ul></div>}
    {(f.overall.notes || f.overall.quickTags.length > 0) && <div className="mt-4 rounded border border-gray-300 p-3"><div className="text-[10px] font-semibold uppercase tracking-wide text-gray-500">Inspection notes</div><div className="mt-1 whitespace-pre-line">{f.overall.notes}</div>{f.overall.quickTags.length > 0 && <div className="mt-1 text-xs text-gray-600">{f.overall.quickTags.join(' · ')}</div>}{f.overall.waiver && <div className="mt-1 text-xs font-semibold text-amber-900">A liability waiver is required for this job.</div>}</div>}
    {yesNo.length > 0 && <div className="mt-4"><div className="text-[10px] font-semibold uppercase tracking-wide text-gray-500">Please answer Yes / No</div><ul className="mt-1 divide-y divide-gray-200" data-testid={`${testId}-yesno`}>{yesNo.map((q, i) => <li key={i} className="flex items-center justify-between py-1.5"><span>{q.label}</span><span className="flex items-center gap-3"><span className="font-mono">{q.price ? fmtMoney(q.price) : ''}</span><span className="rounded border border-gray-400 px-2 py-0.5 text-xs">Yes</span><span className="rounded border border-gray-400 px-2 py-0.5 text-xs">No</span></span></li>)}</ul></div>}
    <div className="mt-4 flex justify-end border-t-2 border-black pt-2 text-base font-bold"><span>Total estimate</span><span className="ml-6 font-mono" data-testid={`${testId}-total`}>{fmtMoney(api.inspectionTotal(f))}</span></div>
  </div>;
};
