import { ExternalLink, Globe, Mail, RotateCcw, Truck, Undo2, Wrench } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { Link } from 'react-router-dom';
import * as api from '@/api/client';
import * as cz from '@/api/concierge';
import type { SwoWithRefs } from '@/api/client';
import { field } from '@/components/rs/RsBits';
import { Button } from '@/components/ui/Button';
import { Modal } from '@/components/ui/Modal';
import { fmtDate, fmtMoneyCents } from '@/lib/format';
import { VendorInvoicesPanel } from './VendorInvoices';

export type Run = (fn: () => Promise<unknown>, m: string) => Promise<void>;
export const HEALTH_TONE: Record<cz.SwoHealthView['tone'], string> = { ok: 'bg-moss-50 text-moss-800', amber: 'bg-amber-50 text-amber-900 ring-1 ring-amber-300', red: 'bg-rose-50 text-rose-800 ring-1 ring-rose-300', dark: 'bg-rose-900 text-white', muted: 'bg-canvas text-ink-500' };
const COMP: Record<string, string> = { head: 'Head / dial', case: 'Case / bezel', band: 'Bracelet' };
const fmtMD = (iso: string) => { const d = new Date(iso); return `${d.getMonth() + 1}/${d.getDate()}`; };
export const Mini = ({ testId, title, ok, disabled, onClose, onOk, children }: { testId: string; title: string; ok: string; disabled?: boolean; onClose: () => void; onOk: () => void; children: ReactNode }) => <Modal testId={testId} title={title} width="w-[460px]" onClose={onClose}>{children}<div className="mt-3 flex justify-end gap-2"><Button size="sm" onClick={onClose}>Cancel</Button><Button size="sm" variant="primary" data-testid={`${testId}-go`} disabled={disabled} onClick={onOk}>{ok}</Button></div></Modal>;

// Health + point person + escalation + expected-vs-parent — the header strip shared by the panel card and the Action lookup
export const HealthStrip = ({ w }: { w: SwoWithRefs }) => {
  const h = cz.swoHealth(w); const esc = cz.escalationLevel(w); const paid = cz.paidChip(w); const parts = cz.partsWait(w); const noShip = w.vendor.ships === false;
  return <div className="flex flex-wrap items-center gap-1 text-[10px]">
    <span data-testid={`concierge-health-${w.id}`} className={`rounded-sm px-1 font-semibold ${HEALTH_TONE[h.tone]}`}>{h.label}</span>
    {w.redoCycles.length > 0 && <span data-testid={`concierge-redo-${w.id}`} title={w.redoCycles.map((r) => `#${r.n} ${r.reason}`).join('\n')} className="rounded-sm bg-amber-50 px-1 font-semibold uppercase text-amber-800">Redo ×{w.redoCycles.length}</span>}
    {!noShip && paid.kind !== 'none' && <span data-testid={`concierge-paid-${w.id}`} data-kind={paid.kind} className={`rounded-sm px-1 font-semibold ${paid.kind === 'paid' ? 'bg-moss-50 text-moss-700' : 'bg-canvas text-ink-500'}`}>{paid.text}</span>}
    {parts && <span data-testid={`concierge-parts-${w.id}`} className="rounded-sm bg-sky-50 px-1 font-semibold text-sky-800">PARTS · {parts.label}</span>}
    {w.international && <span className="inline-flex items-center gap-0.5 rounded-sm bg-sky-50 px-1 font-semibold text-sky-800"><Globe size={9} /> INTL</span>}
    {esc.level > 0 && <span data-testid={`concierge-esc-${w.id}`} className="rounded-sm bg-rose-100 px-1 font-semibold text-rose-800">L{esc.level} → {esc.to}</span>}
    <span data-testid={`concierge-point-${w.id}`} className="rounded-sm bg-canvas px-1 text-ink-600">point person <b>{w.pointPerson ?? '—'}</b></span>
    <span data-testid={`concierge-dates-${w.id}`} className="text-ink-500">{w.predictedCompletion ? `back ${fmtMD(w.predictedCompletion)}` : 'no expected date'}{h.parentTarget ? ` · parent due ${fmtMD(h.parentTarget)}` : ''}{h.health !== 'queued' && h.health !== 'fulfilled' ? ` · ${h.health.replace('_', ' ')}` : ''}</span>
  </div>;
};

const Shipment = ({ w, l, direction }: { w: SwoWithRefs; l?: SwoWithRefs['outbound']; direction: 'outbound' | 'return' }) => {
  if (!l) return <div className="rounded-sm border border-dashed border-line px-2 py-3 text-center text-ink-400">{direction === 'outbound' ? 'No outbound label yet' : 'No return label queued'}</div>;
  const st = cz.trackingStatus(w, direction);
  return <div data-testid={`swo-label-${direction}`} className={`rounded-sm border px-2 py-1.5 text-xs ${st.live ? 'border-sky-300 bg-sky-50/40' : 'border-line bg-canvas/60'}`}>
    <div className="flex items-center gap-2"><span className="font-semibold">{direction === 'outbound' ? 'Outbound · shop → vendor' : 'Return · vendor → shop (prepaid)'}</span>{l.international && <span className="inline-flex items-center gap-0.5 rounded-sm bg-sky-50 px-1 text-[10px] font-semibold text-sky-800"><Globe size={9} /> INTL</span>}<span className="ml-auto text-ink-400">{fmtMoneyCents(l.cost)}</span></div>
    <div className="font-mono">{l.carrier} {l.service} · <a data-testid={`swo-tracking-${direction}`} href={cz.trackingUrl(l.carrier, l.tracking)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-0.5 text-brand underline">{l.tracking}<ExternalLink size={9} /></a></div>
    <div data-testid={`swo-tracking-status-${direction}`} className={`text-[11px] ${st.live ? 'font-semibold text-sky-800' : 'text-ink-500'}`}>{st.live ? '● ' : ''}{st.text}</div>
    {l.customs && <div className="mt-0.5 text-[11px] text-ink-500">Customs: {l.customs.contents} · ${l.customs.value} · HS {l.customs.hsCode} · origin {l.customs.origin} · {l.customs.incoterm}</div>}
    <div className="text-[11px] text-ink-400">created {fmtDate(l.createdAt)} by {l.createdBy}{l.emailedAt ? ` · emailed to vendor ${fmtDate(l.emailedAt)}` : ''}</div>
  </div>;
};

// ONE job, full detail inline (was the popup): header strip, work, invoices + read-only QBO, actions, customs, shipments, timeline
export const SwoCard = ({ w, run, compact }: { w: SwoWithRefs; run: Run; compact?: boolean }) => {
  const v = w.vendor; const noShip = v.ships === false; const next = api.nextSwoStage(v, w.stage); const prev = api.prevSwoStage(v, w.stage); const days = api.swoDaysAtStage(w); const h = cz.swoHealth(w); const qbo = cz.qboState(w);
  const [modal, setModal] = useState<'back' | 'redo' | 'edit' | 'reply' | 'resched' | 'parts' | null>(null); const [t, setT] = useState(''); const [d, setD] = useState(''); const [pp, setPp] = useState(w.pointPerson ?? ''); const [qty, setQty] = useState(1); const [reason, setReason] = useState(''); const [showTl, setShowTl] = useState(!compact);
  const [customs, setCustoms] = useState({ contents: '', value: '', hsCode: '9111.20', origin: 'CH', incoterm: 'DAP' as 'DAP' | 'DDP' });
  const close = () => { setModal(null); setT(''); setD(''); setReason(''); };
  const advance = () => { if (!next) return; if ((next === 'inbound' || next === 'redo_inbound') && !w.returnLabel) return void run(() => api.queueSwoReturnLabel(w.id, w.predictedCompletion), 'Return label queued + emailed to vendor — now advance to Returning'); void run(() => api.advanceSwo(w.id, next), next === 'received' ? `${w.number} received back — arrival scan, custody returned` : `${w.number} → ${api.swoStageLabel(next)}`); };
  return <article data-testid={`concierge-card-${w.id}`} data-health={h.health} className="rounded-md border border-line bg-surface p-3 text-xs">
    <div className="flex flex-wrap items-center gap-2">
      <span className="font-mono text-sm font-semibold">{w.number}</span><span className="rounded-sm bg-ink px-2 py-0.5 text-[10px] font-semibold uppercase text-white" data-testid={`swo-stage-${w.id}`}>{api.swoStageLabel(w.stage)}</span>
      <Link to={`/jobs/${w.jobId}`} state={{ from: `${window.location.pathname}${window.location.search}` }} data-testid={`concierge-card-job-${w.id}`} className="font-mono font-semibold text-brand hover:underline">{w.jobNumber.replace(/^E/, '')}</Link><span className="text-ink">{w.clientName} · {w.watchLabel}</span>
      <span className={`ml-auto font-mono text-[10px] ${days >= 7 ? 'text-rose-700' : days >= 3 ? 'text-amber-700' : 'text-ink-400'}`}>{days}d at stage</span>
    </div>
    <div className="mt-1"><HealthStrip w={w} /></div>
    <div className="mt-2 flex flex-wrap items-center gap-2 text-ink-600"><span>{w.components.map((c) => COMP[c] ?? c).join(' + ')}</span><span className="text-ink-300">·</span><span data-testid={`swo-custody-holder-${w.id}`}>Custody: <b>{w.custodyHolder}</b></span></div>
    <div className="mt-2 rounded-sm border border-line px-2 py-1.5"><div className="text-[10px] uppercase text-ink-400">Work</div>{w.work}{w.notes && <div className="mt-0.5 text-ink-500">{w.notes}</div>}</div>
    {!noShip && <div className="mt-2"><VendorInvoicesPanel w={w} run={run} /><div data-testid={`swo-qbo-${w.id}`} data-tone={qbo.tone} className={`mt-1 text-[11px] ${qbo.tone === 'ok' ? 'text-moss-700' : qbo.tone === 'warn' ? 'font-semibold text-rose-700' : 'text-ink-400'}`}>QuickBooks: {qbo.text}{qbo.tone === 'warn' && <button type="button" className="ml-1 underline" onClick={() => void run(async () => undefined, 'Retry queued (stub)')}>retry</button>}</div></div>}
    <div className="mt-2 flex flex-wrap items-center gap-1">
      {w.stage === 'queue' && !noShip && <Button size="sm" variant="primary" data-testid={`swo-create-outbound-${w.id}`} onClick={() => run(() => api.createSwoOutboundLabel(w.id, w.international ? { contents: customs.contents || undefined, value: customs.value ? Number(customs.value) : undefined, hsCode: customs.hsCode, origin: customs.origin, incoterm: customs.incoterm } : undefined), 'Outbound label created · vendor emailed · custody → vendor')}><Truck size={12} /> Create outbound label{w.international ? ' (intl)' : ''} → In route</Button>}
      {next && !/sent$/.test(next) && <Button size="sm" variant="primary" data-testid={`concierge-advance-${w.id}`} onClick={advance}>→ {api.swoStageLabel(next)}{(next === 'inbound' || next === 'redo_inbound') && !w.returnLabel ? ' (queue return label first)' : ''}</Button>}
      {w.stage === 'inspection' && <Button size="sm" data-testid={`concierge-redo-start-${w.id}`} onClick={() => setModal('redo')}><RotateCcw size={11} /> Redo +</Button>}
      {prev && <Button size="sm" variant="ghost" data-testid={`concierge-sendback-${w.id}`} onClick={() => setModal('back')} title="Back one stage (reason required)"><Undo2 size={11} /> Back</Button>}
      {(h.health === 'delayed' || h.health === 'breach') && <>{cz.statusRequestDue(w) && <Button size="sm" data-testid={`concierge-status-${w.id}`} onClick={() => void run(() => cz.sendVendorStatusRequest(w.id), `Status request emailed to ${v.name}`)}><Mail size={11} /> Status request</Button>}<Button size="sm" data-testid={`concierge-reply-${w.id}`} onClick={() => setModal('reply')}>Vendor reply</Button>{h.health === 'breach' && <Button size="sm" data-testid={`concierge-resched-${w.id}`} onClick={() => setModal('resched')}>Reschedule client</Button>}</>}
      <Button size="sm" variant="ghost" data-testid={`concierge-parts-req-${w.id}`} onClick={() => setModal('parts')}><Wrench size={11} /> Parts request</Button>
      <Button size="sm" variant="ghost" data-testid={`concierge-edit-${w.id}`} onClick={() => setModal('edit')}>Expected / point person</Button>
      <Link to={`/jobs/${w.jobId}`} state={{ from: `${window.location.pathname}${window.location.search}` }} data-testid={`concierge-open-job-${w.id}`} className="ml-auto text-[11px] font-medium text-brand hover:underline">Open job →</Link>
    </div>
    {w.stage === 'queue' && w.international && <div data-testid="swo-customs-form" className="mt-2 grid grid-cols-[1fr_80px_80px_60px_70px] gap-1 rounded-sm border border-sky-200 bg-sky-50/50 p-2"><label className="col-span-5 text-[10px] font-semibold uppercase text-sky-800">Customs — international vendor ({v.country})</label><input data-testid="swo-customs-contents" placeholder="Contents (defaults to component + repair & return)" value={customs.contents} onChange={(e) => setCustoms({ ...customs, contents: e.target.value })} className={field} /><input data-testid="swo-customs-value" placeholder="Value $" type="number" value={customs.value} onChange={(e) => setCustoms({ ...customs, value: e.target.value })} className={field} /><input value={customs.hsCode} onChange={(e) => setCustoms({ ...customs, hsCode: e.target.value })} className={field} /><input value={customs.origin} onChange={(e) => setCustoms({ ...customs, origin: e.target.value })} className={field} /><select value={customs.incoterm} onChange={(e) => setCustoms({ ...customs, incoterm: e.target.value as 'DAP' | 'DDP' })} className={field}><option>DAP</option><option>DDP</option></select></div>}
    {!noShip && <div className="mt-2 grid gap-2 lg:grid-cols-2"><Shipment w={w} l={w.outbound} direction="outbound" /><Shipment w={w} l={w.returnLabel} direction="return" /></div>}
    <div className="mt-2"><button type="button" data-testid={`swo-timeline-toggle-${w.id}`} onClick={() => setShowTl((o) => !o)} className="text-[10px] uppercase text-ink-400 hover:text-ink">Timeline · {w.timeline.length} {showTl ? '▾' : '▸'}</button>{showTl && <ul data-testid={`swo-timeline-${w.id}`} className="mt-1 max-h-40 space-y-0.5 overflow-y-auto">{w.timeline.map((x, i) => <li key={i} className="flex gap-2"><span className="w-20 shrink-0 text-ink-400">{fmtDate(x.at)}</span><span className="w-14 shrink-0 font-medium">{x.by}</span><span>{x.text}</span></li>)}</ul>}</div>
    {modal === 'back' && <Mini testId="concierge-back" title={`Move ${w.number} back one stage`} ok="Move back" disabled={!t.trim()} onClose={close} onOk={() => { close(); void run(() => api.sendBackSwo(w.id, t), `${w.number} moved back — ${t}`); }}><label className="block text-xs text-ink-500">Reason (required)<input autoFocus data-testid="concierge-back-reason" value={t} onChange={(e) => setT(e.target.value)} className={`${field} mt-1 w-full`} /></label></Mini>}
    {modal === 'redo' && <Mini testId="concierge-redo-modal" title={`Return ${w.number} to ${v.name} for redo`} ok={`Start redo ×${w.redoCycles.length + 1}`} disabled={!t.trim()} onClose={close} onOk={() => { close(); void run(() => cz.startRedo(w.id, t), `${w.number} → redo ×${w.redoCycles.length + 1} at ${v.name}`); }}><label className="block text-xs text-ink-500">What failed (goes to the vendor in the outbound email) *<textarea autoFocus data-testid="concierge-redo-reason" rows={2} value={t} onChange={(e) => setT(e.target.value)} className={`${field} mt-1 w-full`} /></label><p className="mt-1 text-[11px] text-ink-400">Redo legs reuse the label / customs / return-label flow. Expected at no charge{w.paid ? ' — already PAID; Mark paid stays blocked on the redo' : ''}.</p></Mini>}
    {modal === 'edit' && <Mini testId="concierge-edit-modal" title={`${w.number} · expected date & point person`} ok="Save" onClose={close} onOk={() => { close(); void run(async () => { if (d && d !== w.predictedCompletion) await cz.setExpectedAt(w.id, d, t || undefined); if (pp && pp !== w.pointPerson) await cz.setPointPerson(w.id, pp); }, `${w.number} updated`); }}><div className="grid grid-cols-2 gap-2 text-xs text-ink-500"><label>Expected completion<input type="date" data-testid="concierge-edit-date" defaultValue={w.predictedCompletion ?? ''} onChange={(e) => setD(e.target.value)} className={`${field} mt-1 w-full`} /></label><label>Point person<select data-testid="concierge-edit-point" value={pp} onChange={(e) => setPp(e.target.value)} className={`${field} mt-1 w-full`}>{cz.conciergeStaff().map((u) => <option key={u.id} value={u.shortName}>{u.shortName} · {u.dutyLabel}</option>)}</select></label><label className="col-span-2">Reason for the change (logged)<input data-testid="concierge-edit-reason" value={t} onChange={(e) => setT(e.target.value)} className={`${field} mt-1 w-full`} /></label></div></Mini>}
    {modal === 'reply' && <Mini testId="concierge-reply-modal" title={`Vendor reply · ${v.name}`} ok="Log reply" disabled={!t.trim()} onClose={close} onOk={() => { close(); void run(() => cz.logVendorReply(w.id, t, d || undefined), `Vendor reply logged${d ? ` · new date ${d}` : ''}`); }}><label className="block text-xs text-ink-500">What they said *<textarea autoFocus data-testid="concierge-reply-text" rows={2} value={t} onChange={(e) => setT(e.target.value)} className={`${field} mt-1 w-full`} /></label><label className="mt-2 block text-xs text-ink-500">Vendor's new promised date (resets at-risk / delayed)<input type="date" data-testid="concierge-reply-date" value={d} onChange={(e) => setD(e.target.value)} className={`${field} mt-1 w-full`} /></label></Mini>}
    {modal === 'resched' && <Mini testId="concierge-resched-modal" title="Reschedule client" ok="Log new client date" disabled={!d} onClose={close} onOk={() => { close(); void run(() => cz.rescheduleParentClient(w.id, d, reason === 'email' ? 'email' : 'call'), `Client rescheduled to ${d} · reason vendor delay – ${v.name}`); }}><label className="block text-xs text-ink-500">New date promised to the client *<input type="date" data-testid="concierge-resched-date" value={d} onChange={(e) => setD(e.target.value)} className={`${field} mt-1 w-full`} /></label><div className="mt-2 flex gap-3 text-xs">{['call', 'email'].map((k) => <label key={k} className="inline-flex items-center gap-1"><input type="radio" data-testid={`concierge-resched-${k}`} checked={(reason || 'call') === k} onChange={() => setReason(k)} /> told by {k}</label>)}</div></Mini>}
    {modal === 'parts' && <Mini testId="concierge-parts-modal" title={`Parts request for ${v.name} · ${w.number}`} ok="Request parts" disabled={!t.trim()} onClose={close} onOk={() => { close(); void run(() => cz.requestVendorParts(w.id, t, qty, reason), `Parts request for ${v.name} → estimate addendum → client approval`); }}><div className="grid grid-cols-[1fr_70px] gap-2 text-xs text-ink-500"><label>Part *<input autoFocus data-testid="concierge-parts-desc" value={t} onChange={(e) => setT(e.target.value)} className={`${field} mt-1 w-full`} /></label><label>Qty<input type="number" min={1} inputMode="numeric" data-testid="concierge-parts-qty" value={qty} onChange={(e) => setQty(Number(e.target.value))} className={`${field} mt-1 w-full`} /></label><label className="col-span-2">Reason<input data-testid="concierge-parts-reason" value={reason} onChange={(e) => setReason(e.target.value)} className={`${field} mt-1 w-full`} /></label></div></Mini>}
  </article>;
};
